<a href="https://colab.research.google.com/github/jacobgreen4477/The-4th-ETRI-AI-Human-Understanding-Competition/blob/main/etri_baseline_v5_0_4(%EC%A6%9D%EA%B0%95).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

> title : 제 4회 ETRI 휴먼이해 인공지능 논문경진대회 <br>
> author : hjy <br>

### 📦 LLM

In [ ]:
%%time

# CPU times: user 1.19 s, sys: 188 ms, total: 1.37 s
# Wall time: 4min 36s

try:
  from vllm import LLM, SamplingParams
except:
  !pip install -U langchain-community  >/dev/null
  !pip install bitsandbytes >/dev/null
  !pip install -U transformers accelerate >/dev/null
  !pip install faiss-gpu-cu12 --no-deps >/dev/null
  !pip install datasets >/dev/null
  !pip install vllm >/dev/null
  !pip install --upgrade transformers >/dev/null

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
faiss-gpu-cu12 1.11.0 requires numpy<2, but you have numpy 2.0.2 which is incompatible.
fastai 2.7.19 requires torch<2.7,>=1.10, but you have torch 2.7.0 which is incompatible.
dask-cuda 25.2.0 requires numba<0.61.0a0,>=0.59.1, but you have numba 0.61.2 which is incompatible.
cuml-cu12 25.2.1 requires numba<0.61.0a0,>=0.59.1, but you have numba 0.61.2 which is incompatible.
cudf-cu12 25.2.1 requires numba<0.61.0a0,>=0.59.1, but you have numba 0.61.2 which is incompatible.
distributed-ucxx-cu12 0.42.0 requires numba<0.61.0a0,>=0.59.1, but you have numba 0.61.2 which is incompatible.
CPU times: user 908 ms, sys: 128 ms, total: 1.04 s
Wall time: 4min 22s

In [ ]:
%%time

# CPU times: user 12.7 s, sys: 1.53 s, total: 14.2 s
# Wall time: 3min 24s

import os
os.environ["VLLM_WORKER_MULTIPROC_METHOD"] = "spawn"

from google.colab import drive, files
drive.mount('/content/drive')

from huggingface_hub import login
login(token = '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')

from vllm import LLM, SamplingParams

# 경로
drive_path = "/content/drive/MyDrive/models2/"

# 모델명
# model_id  = 'Qwen/Qwen2.5-14B-Instruct-1M'
# model_id  = "LGAI-EXAONE/EXAONE-3.5-2.4B-Instruct"
model_id   = 'Qwen/Qwen3-8B'

# vllm
llm = LLM(
    model=f"{drive_path}{model_id}",
    tokenizer=f"{drive_path}{model_id}",
    tensor_parallel_size=1,
    dtype="bfloat16",     # "bfloat16"
    # quantization="fp8",   # fp8
    load_format="auto",
    gpu_memory_utilization=0.8,
    max_model_len=38960, # 6144,12288,38960,32768,40960
    enforce_eager=True,  ## 실행 시점에서 즉시 연산을 수행하는 방식(싱크방식)
)

Mounted at /content/drive
INFO 06-08 12:02:00 [__init__.py:243] Automatically detected platform cuda.
INFO 06-08 12:02:04 [__init__.py:31] Available plugins for group vllm.general_plugins:
INFO 06-08 12:02:04 [__init__.py:33] - lora_filesystem_resolver -> vllm.plugins.lora_resolvers.filesystem_resolver:register_filesystem_resolver
INFO 06-08 12:02:04 [__init__.py:36] All plugins in this group will be loaded. Set `VLLM_PLUGINS` to control which plugins to load.
INFO 06-08 12:02:19 [config.py:793] This model supports multiple tasks: {'reward', 'generate', 'embed', 'score', 'classify'}. Defaulting to 'generate'.
INFO 06-08 12:02:19 [config.py:2118] Chunked prefill is enabled with max_num_batched_tokens=8192.
WARNING 06-08 12:02:19 [cuda.py:87] To see benefits of async output processing, enable CUDA graph. Since, enforce-eager is enabled, async output processor cannot be used
CPU times: user 15.4 s, sys: 1.66 s, total: 17 s
Wall time: 3min 42s

In [ ]:
from transformers import AutoTokenizer, AutoModelForCausalLM

model_id = "/content/drive/MyDrive/models2/Qwen/Qwen3-8B"

# Tokenizer 로드
tokenizer = AutoTokenizer.from_pretrained(model_id, trust_remote_code=True)

### 📦 라이브러리

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
! pip install haversine >/dev/null
! pip install optuna >/dev/null
! pip install imbalanced-learn >/dev/null
! pip install category_encoders >/dev/null
! pip install catboost >/dev/null
! pip install h2o >/dev/null
# ! pip install autogluon >/dev/null

In [ ]:
# Core Libraries
import os
import sys
import re
import ast
import glob
import random
from functools import reduce
from io import StringIO
from collections import Counter
from datetime import datetime, timedelta, time

# Numerical Operations
import numpy as np
import pandas as pd

# Math & Geospatial
from math import radians, cos, sin, asin, sqrt
from scipy.stats import entropy
from haversine import haversine

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Machine Learning
from sklearn.model_selection import (
    train_test_split, KFold, StratifiedKFold, cross_val_score
)
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import f1_score, roc_auc_score, roc_curve, log_loss, accuracy_score, precision_score, recall_score
from lightgbm import LGBMClassifier, log_evaluation, early_stopping
from xgboost import XGBClassifier
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from catboost import CatBoostClassifier, CatBoostRegressor
import lightgbm as lgb

# Deep Learning (PyTorch)
import torch
from torch import nn, optim
from torch.utils.data import DataLoader, Dataset
from torch.nn import functional as F

# Progress Tracking
from tqdm import tqdm
from tqdm.auto import tqdm
from category_encoders import TargetEncoder

# Warnings
import warnings
warnings.filterwarnings('ignore')

# seed 고정
SD = 42
random.seed(SD)
np.random.seed(SD)
os.environ['PYTHONHASHSEED'] = str(SD)

# pandas 옵션
pd.set_option('display.max_columns', 999)
pd.set_option('display.max_rows', 999)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.float_format', lambda x: '%0.4f' % x)

In [ ]:
import math
from six.moves import xrange
from catboost import Pool, CatBoostClassifier

class FocalLossObjective(object):
    def calc_ders_range(self, approxes, targets, weights):
        # approxes, targets, weights are indexed containers of floats
        # (containers with only __len__ and __getitem__ defined).
        # weights parameter can be None.
        # Returns list of pairs (der1, der2)
        gamma = 2.
        # alpha = 1.
        assert len(approxes) == len(targets)
        if weights is not None:
            assert len(weights) == len(approxes)

        exponents = []
        for index in xrange(len(approxes)):
            exponents.append(math.exp(approxes[index]))

        result = []
        for index in xrange(len(targets)):
            p = exponents[index] / (1 + exponents[index])

            if targets[index] > 0.0:
                der1 = -((1-p)**(gamma-1))*(gamma * math.log(p) * p + p - 1)/p
                der2 = gamma*((1-p)**gamma)*((gamma*p-1)*math.log(p)+2*(p-1))
            else:
                der1 = (p**(gamma-1)) * (gamma * math.log(1 - p) - p)/(1 - p)
                der2 = p**(gamma-2)*((p*(2*gamma*(p-1)-p))/(p-1)**2 + (gamma-1)*gamma*math.log(1 - p))

            if weights is not None:
                der1 *= weights[index]
                der2 *= weights[index]

            result.append((der1, der2))

        return result

In [ ]:
def seed_everything(seed):
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = True

seed_everything(1)

In [ ]:
def focal_loss_lgb(y_pred, dtrain, alpha=0.25, gamma=2.0):
    y_true = dtrain.get_label()
    p = 1 / (1 + np.exp(-y_pred))  # sigmoid

    grad = alpha * (y_true * (1 - p) ** gamma * (gamma * p * np.log(np.clip(p, 1e-9, 1)) + p - 1) +
                    (1 - y_true) * p ** gamma * (gamma * (1 - p) * np.log(np.clip(1 - p, 1e-9, 1)) - p))

    hess = alpha * (y_true * (1 - p) ** gamma *
                    ((gamma * (1 - p) * (1 - 2 * p) - p * (1 - p)) * np.log(np.clip(p, 1e-9, 1)) +
                     2 * p - 1) +
                    (1 - y_true) * p ** gamma *
                    ((gamma * p * (1 - 2 * p) - (1 - p) * p) * np.log(np.clip(1 - p, 1e-9, 1)) +
                     1 - 2 * p))

    return grad, hess

def f1_eval(y_pred, dtrain):
    y_true = dtrain.get_label()
    y_pred_binary = (y_pred > 0.5).astype(int)
    return 'f1', f1_score(y_true, y_pred_binary), True  # ✅ 반환값: (이름, 점수, 높을수록 좋은지 여부)

In [ ]:
def find_best_threshold(y_true, y_proba):
    thresholds = np.linspace(0.05, 0.95, 200)
    best_f1 = 0
    best_thresh = 0.5
    for t in thresholds:
        preds = (y_proba >= t).astype(int)
        score = f1_score(y_true, preds)
        if score > best_f1:
            best_f1 = score
            best_thresh = t
    return best_thresh, best_f1

def add_noise(series, noise_level, seed=3):
    rng = np.random.default_rng(seed)
    return series * (1 + noise_level * rng.standard_normal(len(series)))

def calculate_averages(data,name):
    variables = ['Q1', 'Q2', 'Q3', 'S1', 'S2', 'S3']
    variable_averages = {}
    total_sum = 0
    total_count = 0

    for var in variables:
        values = []
        for entry in data.values():
            if var in entry:  # 키가 존재하는 경우에만 추가
                values.append(entry[var])
        avg = sum(values) / len(values) if values else None  # 누락된 변수 처리
        variable_averages[var] = round(avg, 6) if avg is not None else 'Missing'
        total_sum += sum(values)
        total_count += len(values)

    overall_avg = round(total_sum / total_count, 6) if total_count > 0 else None
    print(f'# 전체 평균 {name}: {overall_avg} {variable_averages}')

    return variable_averages, overall_avg

In [ ]:
def remove_highly_correlated_features(X, threshold=0.95):
    corr_matrix = X.corr().abs()
    upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))
    to_drop = [column for column in upper.columns if any(upper[column] > threshold)]
    print(f"제거할 feature 개수: {len(to_drop)} / 전체 feature 개수: {X.shape[1]}")
    return X.drop(columns=to_drop), to_drop

In [ ]:
def calculate_circular_mean_sleep_time(sleep_times):
    sleep_times = pd.Series(sleep_times).dropna()
    if len(sleep_times) == 0:
        return np.nan  # 혹은 return 0.0 등 기본값 설정 가능

    def hour_to_radian(hour):
        return (hour % 24) / 24 * 2 * np.pi

    radians = np.array([hour_to_radian(t) for t in sleep_times])
    mean_radian = np.arctan2(np.mean(np.sin(radians)), np.mean(np.cos(radians)))
    mean_hour = (mean_radian / (2 * np.pi)) * 24 % 24

    return mean_hour

In [ ]:
def circular_mean_sleep_time(times):

    # 결측치 제거
    valid_times = [t for t in times if pd.notna(t)]

    # 유효 데이터 개수 확인
    if len(valid_times) == 0:
        return None  # 결측치만 있는 경우

    # 시간 → 라디안 변환
    radians = [(t % 24) / 24 * 2 * np.pi for t in valid_times]

    # 사인/코사인 평균 계산
    sin_sum = np.mean(np.sin(radians))
    cos_sum = np.mean(np.cos(radians))

    # 평균 각도 계산
    if sin_sum == 0 and cos_sum == 0:
        return np.nan  # 불가능한 경우

    mean_radian = np.arctan2(sin_sum, cos_sum)

    # 평균 시간으로 변환
    mean_hour = (mean_radian / (2 * np.pi)) * 24
    if mean_hour < 0:
        mean_hour += 24

    return f'{int(mean_hour):02d}:{int((mean_hour % 1) * 60):02d}'

In [ ]:
def calculate_sleep_duration_min(sleep_time, wake_time):
    """
    취침 시각(sleep_time)과 기상 시각(wake_time)을 입력받아 수면 시간(분) 반환
    단위는 float 시간 (예: 23.5, 6.25)
    """
    if pd.isna(sleep_time) or pd.isna(wake_time):
        return None
    if wake_time < sleep_time:
        wake_time += 24  # 자정 넘긴 경우 보정
    duration = (wake_time - sleep_time) * 60
    return round(duration)

In [ ]:
def fill_missing_dates_by_subject(df, date_col='lifelog_date'):

    df = df.copy()
    df[date_col] = pd.to_datetime(df[date_col])
    result = []

    for sid, group in df.groupby('subject_id'):
        group = group.sort_values(date_col)

        # 연속 날짜 생성
        full_dates = pd.date_range(start=group[date_col].min(), end=group[date_col].max())
        full_df = pd.DataFrame({date_col: full_dates})
        full_df['subject_id'] = sid

        # 병합
        merged = pd.merge(full_df, group, on=['subject_id', date_col], how='left')

        result.append(merged)

    # 병합 및 정렬
    final_df = pd.concat(result, ignore_index=True).sort_values(['subject_id', date_col])

    return final_df

In [ ]:
def get_time_block(hour):
    if 1 <= hour < 5:
        return 'sleeptime'
    else:
        return 'activehour'

In [ ]:
SLEEP_HOURS = tuple(range(0, 5)) ### 수정
MIGHT_GO_TO_SLEEP_HOURS = tuple(range(20, 24)) + tuple(range(0, 2))
MIGHT_WAKEUP_HOURS = tuple(range(6, 10))
ACTIVE_HOURS = tuple(range(7, 24))
WORK_HOURS = tuple(range(7, 19))
FREE_HOURS = tuple(range(19, 24))

HOLIDAY_DATES = [
    pd.Timestamp('2024-08-15'),
    pd.Timestamp('2024-09-16'),
    pd.Timestamp('2024-09-17'),
    pd.Timestamp('2024-09-18'),
    pd.Timestamp('2024-10-03'),
    pd.Timestamp('2024-10-09'),
]

In [ ]:
from pathlib import Path
DATA_DIR = Path("/content/drive/MyDrive/data")

from enum import Enum
class DataType(Enum):
    mACStatus = "mACStatus"
    mActivity = "mActivity"
    mAmbience = "mAmbience"
    mBle = "mBle"
    mGps = "mGps"
    mLight = "mLight"
    mScreenStatus = "mScreenStatus"
    mUsageStats = "mUsageStats"
    mWifi = "mWifi"
    wHr = "wHr"
    wLight = "wLight"
    wPedo = "wPedo"

In [ ]:
def load_data(data_type: DataType):
    file_path = DATA_DIR / f"ch2025_data_items/ch2025_{data_type.value}.parquet"
    df = pd.read_parquet(file_path)
    df["subject_id"] = df["subject_id"].astype("category")
    df["lifelog_date"] = df["timestamp"].dt.normalize()
    df["month"] = df["timestamp"].dt.month
    df["day"] = df["timestamp"].dt.day
    df["hour"] = df["timestamp"].dt.hour
    df["minute"] = df["timestamp"].dt.minute
    df["weekday"] = df["timestamp"].dt.weekday
    fixed_columns = ["subject_id", "timestamp", "lifelog_date", "month", "day", "hour", "minute", "weekday"]
    columns = df.columns.tolist()
    columns = fixed_columns + [col for col in columns if col not in fixed_columns]
    df = df[columns]
    df = df.sort_values(by=["subject_id", "timestamp"])
    return df

def load_train():
    df = pd.read_csv(DATA_DIR / "ch2025_metrics_train.csv")
    df["subject_id"] = df["subject_id"].astype("category")
    df["sleep_date"] = pd.to_datetime(df["sleep_date"]).dt.normalize()
    df["lifelog_date"] = pd.to_datetime(df["lifelog_date"]).dt.normalize()
    return df


def load_val():
    from io import StringIO
    train_df = load_train()
    val_ids = "subject_id,sleep_date\nid01,2024-07-24\nid01,2024-07-27\nid01,2024-08-18\nid01,2024-08-19\nid01,2024-08-20\nid01,2024-08-21\nid01,2024-08-22\nid01,2024-08-24\nid01,2024-08-25\nid01,2024-08-26\nid01,2024-08-27\nid01,2024-08-28\nid01,2024-08-29\nid01,2024-08-30\nid02,2024-08-23\nid02,2024-08-24\nid02,2024-09-16\nid02,2024-09-17\nid02,2024-09-19\nid02,2024-09-20\nid02,2024-09-21\nid02,2024-09-22\nid02,2024-09-23\nid02,2024-09-24\nid02,2024-09-25\nid02,2024-09-26\nid02,2024-09-27\nid02,2024-09-28\nid03,2024-08-30\nid03,2024-09-01\nid03,2024-09-02\nid03,2024-09-03\nid03,2024-09-05\nid03,2024-09-06\nid03,2024-09-07\nid04,2024-09-03\nid04,2024-09-04\nid04,2024-09-05\nid04,2024-09-06\nid04,2024-09-07\nid04,2024-09-08\nid04,2024-09-09\nid04,2024-10-08\nid04,2024-10-09\nid04,2024-10-10\nid04,2024-10-11\nid04,2024-10-12\nid04,2024-10-13\nid04,2024-10-14\nid05,2024-10-19\nid05,2024-10-23\nid05,2024-10-24\nid05,2024-10-25\nid05,2024-10-26\nid05,2024-10-27\nid05,2024-10-28\nid06,2024-07-25\nid06,2024-07-26\nid06,2024-07-27\nid06,2024-07-28\nid06,2024-07-29\nid06,2024-07-30\nid06,2024-07-31\nid07,2024-07-07\nid07,2024-07-08\nid07,2024-07-09\nid07,2024-07-10\nid07,2024-07-11\nid07,2024-07-12\nid07,2024-07-13\nid07,2024-07-30\nid07,2024-08-01\nid07,2024-08-02\nid07,2024-08-03\nid07,2024-08-04\nid07,2024-08-05\nid07,2024-08-06\nid08,2024-08-28\nid08,2024-08-29\nid08,2024-08-30\nid08,2024-08-31\nid08,2024-09-01\nid08,2024-09-02\nid08,2024-09-04\nid09,2024-08-02\nid09,2024-08-22\nid09,2024-08-23\nid09,2024-08-24\nid09,2024-08-25\nid09,2024-08-27\nid09,2024-08-28\nid09,2024-08-29\nid09,2024-08-30\nid09,2024-08-31\nid09,2024-09-01\nid09,2024-09-02\nid09,2024-09-03\nid09,2024-09-04\nid10,2024-08-28\nid10,2024-08-30\nid10,2024-08-31\nid10,2024-09-01\nid10,2024-09-02\nid10,2024-09-03\nid10,2024-09-06\n"
    val_df = pd.read_csv(StringIO(val_ids))
    val_df = val_df.astype({"subject_id": "category", "sleep_date": "datetime64[ns]"})
    val_df = train_df.merge(val_df, on=["subject_id", "sleep_date"], how="inner")
    return val_df


def load_test():
    df = pd.read_csv(DATA_DIR / "ch2025_submission_sample.csv")
    df["subject_id"] = df["subject_id"].astype("category")
    df["sleep_date"] = pd.to_datetime(df["sleep_date"]).dt.normalize()
    df["lifelog_date"] = pd.to_datetime(df["lifelog_date"]).dt.normalize()
    return df

In [ ]:
def describe_df(df):
    print(f"# shape:\n{df.shape}\n")
    print(f"# dtypes:\n{df.dtypes}\n")
    # print(f"# head:\n{df.head(3)}\n")
    display(df.head(3))
    nan_stats = df.isna().sum().to_frame(name='missing_count')
    nan_stats['missing_ratio(%)'] = (df.isna().mean() * 100).round(2)
    print(f"# nan_stats:\n" + nan_stats.to_string() + "\n")

In [ ]:
def shift_lifelog_date(df, target_hours):
    df = df.copy()
    mask = df["hour"].isin(target_hours) & df["hour"].lt(12)
    df.loc[mask, "lifelog_date"] = df.loc[mask, "lifelog_date"] - pd.Timedelta(days=1)
    df.loc[mask, "day"] = df.loc[mask, "day"] - 1
    df = df.sort_values(by=["subject_id", "lifelog_date", "timestamp"])
    return df

In [ ]:
# 검증데이터셋 PK모음
valid_ids1 = ['id012024-07-24', 'id012024-07-27', 'id012024-08-18', 'id012024-08-19', 'id012024-08-20', 'id012024-08-21', 'id012024-08-22', 'id012024-08-24', 'id012024-08-25', 'id012024-08-26', 'id012024-08-27', 'id012024-08-28', 'id012024-08-29', 'id012024-08-30', 'id022024-08-23', 'id022024-08-24', 'id022024-09-16', 'id022024-09-17', 'id022024-09-19', 'id022024-09-20', 'id022024-09-21', 'id022024-09-22', 'id022024-09-23', 'id022024-09-24', 'id022024-09-25', 'id022024-09-26', 'id022024-09-27', 'id022024-09-28', 'id032024-08-30', 'id032024-09-01', 'id032024-09-02', 'id032024-09-03', 'id032024-09-05', 'id032024-09-06', 'id032024-09-07', 'id042024-09-03', 'id042024-09-04', 'id042024-09-05', 'id042024-09-06', 'id042024-09-07', 'id042024-09-08', 'id042024-09-09', 'id042024-10-08', 'id042024-10-09', 'id042024-10-10', 'id042024-10-11', 'id042024-10-12', 'id042024-10-13', 'id042024-10-14', 'id052024-10-19', 'id052024-10-23', 'id052024-10-24', 'id052024-10-25', 'id052024-10-26', 'id052024-10-27', 'id052024-10-28', 'id062024-07-25', 'id062024-07-26', 'id062024-07-27', 'id062024-07-28', 'id062024-07-29', 'id062024-07-30', 'id062024-07-31', 'id072024-07-07', 'id072024-07-08', 'id072024-07-09', 'id072024-07-10', 'id072024-07-11', 'id072024-07-12', 'id072024-07-13', 'id072024-07-30', 'id072024-08-01', 'id072024-08-02', 'id072024-08-03', 'id072024-08-04', 'id072024-08-05', 'id072024-08-06', 'id082024-08-28', 'id082024-08-29', 'id082024-08-30', 'id082024-08-31', 'id082024-09-01', 'id082024-09-02', 'id082024-09-04', 'id092024-08-02', 'id092024-08-22', 'id092024-08-23', 'id092024-08-24', 'id092024-08-25', 'id092024-08-27', 'id092024-08-28', 'id092024-08-29', 'id092024-08-30', 'id092024-08-31', 'id092024-09-01', 'id092024-09-02', 'id092024-09-03', 'id092024-09-04', 'id102024-08-28', 'id102024-08-30', 'id102024-08-31', 'id102024-09-01', 'id102024-09-02', 'id102024-09-03', 'id102024-09-06']
valid_ids2 = ['id012024-07-24', 'id012024-07-27', 'id012024-08-19', 'id012024-08-20', 'id012024-08-21', 'id012024-08-22', 'id012024-08-24', 'id012024-08-25', 'id012024-08-26', 'id012024-08-27', 'id012024-08-28', 'id012024-08-29', 'id012024-08-30', 'id012024-09-01', 'id022024-08-23', 'id022024-08-24', 'id022024-09-13', 'id022024-09-14', 'id022024-09-16', 'id022024-09-17', 'id022024-09-19', 'id022024-09-20', 'id022024-09-21', 'id022024-09-22', 'id022024-09-23', 'id022024-09-24', 'id022024-09-25', 'id022024-09-26', 'id032024-09-02', 'id032024-09-03', 'id032024-09-05', 'id032024-09-06', 'id032024-09-07', 'id032024-09-08', 'id042024-09-07', 'id042024-09-08', 'id042024-09-09', 'id042024-09-11', 'id042024-09-17', 'id042024-09-18', 'id042024-09-28', 'id042024-09-29', 'id042024-10-21', 'id042024-10-23', 'id042024-10-27', 'id052024-08-29', 'id052024-08-30', 'id052024-08-31', 'id052024-09-01', 'id052024-10-10', 'id052024-11-05', 'id052024-11-06', 'id052024-11-10', 'id052024-11-11', 'id052024-11-12', 'id052024-11-15', 'id062024-08-03', 'id062024-08-04', 'id062024-08-05', 'id062024-08-06', 'id062024-08-11', 'id062024-08-16', 'id062024-08-19', 'id072024-07-02', 'id072024-07-03', 'id072024-07-04', 'id072024-07-06', 'id072024-07-07', 'id072024-07-08', 'id072024-07-09', 'id072024-08-02', 'id072024-08-03', 'id072024-08-04', 'id072024-08-05', 'id072024-08-06', 'id072024-08-07', 'id072024-08-08', 'id082024-09-01', 'id082024-09-02', 'id082024-09-04', 'id082024-09-06', 'id082024-09-12', 'id082024-09-16', 'id082024-09-17', 'id092024-07-27', 'id092024-07-28', 'id092024-07-30', 'id092024-07-31', 'id092024-08-02', 'id092024-08-04', 'id092024-08-05', 'id092024-08-22', 'id092024-08-23', 'id092024-08-24', 'id092024-08-25', 'id092024-08-27', 'id092024-08-28', 'id092024-08-29', 'id102024-08-30', 'id102024-08-31', 'id102024-09-01', 'id102024-09-02', 'id102024-09-03', 'id102024-09-06', 'id102024-09-08']
valid_ids3 = ['id012024-07-20', 'id012024-07-23', 'id012024-08-19', 'id012024-08-20', 'id012024-08-21', 'id012024-08-22', 'id012024-08-24', 'id012024-08-25', 'id012024-08-26', 'id012024-08-27', 'id012024-08-28', 'id012024-08-29', 'id012024-08-30', 'id012024-09-01', 'id022024-08-21', 'id022024-08-22', 'id022024-09-11', 'id022024-09-12', 'id022024-09-13', 'id022024-09-14', 'id022024-09-16', 'id022024-09-17', 'id022024-09-19', 'id022024-09-20', 'id022024-09-21', 'id022024-09-22', 'id022024-09-23', 'id022024-09-24', 'id032024-09-05', 'id032024-09-06', 'id032024-09-07', 'id032024-09-08', 'id032024-09-10', 'id032024-09-12', 'id032024-09-13', 'id042024-08-27', 'id042024-08-28', 'id042024-08-29', 'id042024-08-30', 'id042024-08-31', 'id042024-09-01', 'id042024-09-02', 'id042024-10-01', 'id042024-10-02', 'id042024-10-03', 'id042024-10-04', 'id042024-10-05', 'id042024-10-06', 'id042024-10-07', 'id052024-10-28', 'id052024-10-29', 'id052024-10-30', 'id052024-10-31', 'id052024-11-03', 'id052024-11-05', 'id052024-11-06', 'id062024-07-31', 'id062024-08-01', 'id062024-08-02', 'id062024-08-03', 'id062024-08-04', 'id062024-08-05', 'id062024-08-06', 'id072024-06-29', 'id072024-06-30', 'id072024-07-01', 'id072024-07-02', 'id072024-07-03', 'id072024-07-04', 'id072024-07-06', 'id072024-08-07', 'id072024-08-08', 'id072024-08-09', 'id072024-08-10', 'id072024-08-11', 'id072024-08-12', 'id072024-08-13', 'id082024-08-19', 'id082024-08-20', 'id082024-08-22', 'id082024-08-23', 'id082024-08-24', 'id082024-08-25', 'id082024-08-26', 'id092024-08-04', 'id092024-08-22', 'id092024-08-23', 'id092024-08-24', 'id092024-08-25', 'id092024-08-27', 'id092024-08-28', 'id092024-08-29', 'id092024-08-30', 'id092024-08-31', 'id092024-09-01', 'id092024-09-02', 'id092024-09-03', 'id092024-09-04', 'id102024-09-02', 'id102024-09-03', 'id102024-09-06', 'id102024-09-08', 'id102024-09-09', 'id102024-09-12', 'id102024-09-15']
valid_ids4 = ['id012024-07-24', 'id012024-07-27', 'id012024-08-18', 'id012024-08-19', 'id012024-08-20', 'id012024-08-21', 'id012024-08-22', 'id012024-08-24', 'id012024-08-25', 'id012024-08-26', 'id012024-08-27', 'id012024-08-28', 'id012024-08-29', 'id012024-08-30', 'id022024-08-23', 'id022024-08-24', 'id022024-09-12', 'id022024-09-13', 'id022024-09-14', 'id022024-09-16', 'id022024-09-17', 'id022024-09-22', 'id022024-09-23', 'id022024-09-24', 'id022024-09-25', 'id022024-09-26', 'id022024-09-27', 'id022024-09-28', 'id032024-08-30', 'id032024-09-01', 'id032024-09-02', 'id032024-09-07', 'id032024-09-08', 'id032024-09-10', 'id042024-09-03', 'id042024-09-04', 'id042024-09-05', 'id042024-09-11', 'id042024-09-17', 'id042024-09-18', 'id042024-09-28', 'id042024-09-29', 'id042024-10-21', 'id042024-10-23', 'id042024-10-27', 'id052024-08-29', 'id052024-08-30', 'id052024-08-31', 'id052024-09-01', 'id052024-10-10', 'id052024-11-03', 'id052024-11-05', 'id052024-11-10', 'id052024-11-11', 'id052024-11-12', 'id052024-11-15', 'id062024-07-27', 'id062024-07-28', 'id062024-07-29', 'id062024-07-30', 'id062024-08-11', 'id062024-08-16', 'id062024-08-19', 'id072024-07-03', 'id072024-07-04', 'id072024-07-06', 'id072024-07-10', 'id072024-07-11', 'id072024-07-12', 'id072024-07-13', 'id072024-07-29', 'id072024-07-30', 'id072024-08-01', 'id072024-08-02', 'id072024-08-03', 'id072024-08-04', 'id072024-08-05', 'id082024-09-01', 'id082024-09-02', 'id082024-09-04', 'id082024-09-06', 'id082024-09-12', 'id082024-09-16', 'id082024-09-17', 'id092024-07-02', 'id092024-07-04', 'id092024-07-05', 'id092024-07-06', 'id092024-08-02', 'id092024-08-04', 'id092024-08-05', 'id092024-08-22', 'id092024-08-23', 'id092024-08-24', 'id092024-08-25', 'id092024-08-27', 'id092024-08-28', 'id092024-08-29', 'id102024-07-27', 'id102024-07-28', 'id102024-07-29', 'id102024-07-30', 'id102024-08-01', 'id102024-08-02', 'id102024-08-03']

In [ ]:
import pandas as pd
from io import StringIO

string = """
subject_id	sleep_date
id01	2024-07-24
id01	2024-07-27
id01	2024-08-18
id01	2024-08-19
id01	2024-08-20
id01	2024-08-21
id01	2024-08-22
id01	2024-08-24
id01	2024-08-25
id01	2024-08-26
id01	2024-08-27
id01	2024-08-28
id01	2024-08-29
id01	2024-08-30
id02	2024-08-23
id02	2024-08-24
id02	2024-09-16
id02	2024-09-17
id02	2024-09-19
id02	2024-09-20
id02	2024-09-21
id02	2024-09-22
id02	2024-09-23
id02	2024-09-24
id02	2024-09-25
id02	2024-09-26
id02	2024-09-27
id02	2024-09-28
id03	2024-08-30
id03	2024-09-01
id03	2024-09-02
id03	2024-09-03
id03	2024-09-05
id03	2024-09-06
id03	2024-09-07
id04	2024-09-03
id04	2024-09-04
id04	2024-09-05
id04	2024-09-06
id04	2024-09-07
id04	2024-09-08
id04	2024-09-09
id04	2024-10-08
id04	2024-10-09
id04	2024-10-10
id04	2024-10-11
id04	2024-10-12
id04	2024-10-13
id04	2024-10-14
id05	2024-10-19
id05	2024-10-23
id05	2024-10-24
id05	2024-10-25
id05	2024-10-26
id05	2024-10-27
id05	2024-10-28
id06	2024-07-25
id06	2024-07-26
id06	2024-07-27
id06	2024-07-28
id06	2024-07-29
id06	2024-07-30
id06	2024-07-31
id07	2024-07-07
id07	2024-07-08
id07	2024-07-09
id07	2024-07-10
id07	2024-07-11
id07	2024-07-12
id07	2024-07-13
id07	2024-07-30
id07	2024-08-01
id07	2024-08-02
id07	2024-08-03
id07	2024-08-04
id07	2024-08-05
id07	2024-08-06
id08	2024-08-28
id08	2024-08-29
id08	2024-08-30
id08	2024-08-31
id08	2024-09-01
id08	2024-09-02
id08	2024-09-04
id09	2024-08-02
id09	2024-08-22
id09	2024-08-23
id09	2024-08-24
id09	2024-08-25
id09	2024-08-27
id09	2024-08-28
id09	2024-08-29
id09	2024-08-30
id09	2024-08-31
id09	2024-09-01
id09	2024-09-02
id09	2024-09-03
id09	2024-09-04
id10	2024-08-28
id10	2024-08-30
id10	2024-08-31
id10	2024-09-01
id10	2024-09-02
id10	2024-09-03
id10	2024-09-06
"""

# DataFrame 생성
valid_ids = pd.read_csv(StringIO(string), sep='\t')
valid_ids['pk'] = valid_ids['subject_id']+valid_ids['sleep_date']

### 📦 데이터 읽기

In [ ]:
path = '/content/drive/MyDrive/data/ch2025_data_items/'

# 1
mACStatus = pd.read_parquet(path+'ch2025_mACStatus.parquet')
mActivity = pd.read_parquet(path+'ch2025_mActivity.parquet')
mAmbience = pd.read_parquet(path+'ch2025_mAmbience.parquet')
mBle = pd.read_parquet(path+'ch2025_mBle.parquet')
mGps = pd.read_parquet(path+'ch2025_mGps.parquet')
mLight = pd.read_parquet(path+'ch2025_mLight.parquet')
mScreenStatus = pd.read_parquet(path+'ch2025_mScreenStatus.parquet')
mUsageStats = pd.read_parquet(path+'ch2025_mUsageStats.parquet')
mWifi = pd.read_parquet(path+'ch2025_mWifi.parquet')
wHr = pd.read_parquet(path+'ch2025_wHr.parquet')
wLight = pd.read_parquet(path+'ch2025_wLight.parquet')
wPedo = pd.read_parquet(path+'ch2025_wPedo.parquet')

# 2
train = pd.read_csv('/content/drive/MyDrive/data/ch2025_metrics_train.csv')
test = pd.read_csv('/content/drive/MyDrive/data/ch2025_submission_sample.csv')

## 📦 데이터 전처리

### ✔️ mACStatus 핸드폰 충전상태
- Indicates whether the smartphone is currently being charged.
- m_charging : 0/1 상태
- 핸드폰이 오랫 동안 충전했다는 의미?
 - 한 자리에 장시간 머물러 있었다.
 - 핸드폰을 장시간 사용하지 않았다.

In [ ]:
def run_length_encoding(arr):
    """Run-Length Encoding"""
    if len(arr) == 0:
        return []

    diffs = np.diff(np.concatenate(([0], arr, [0])))
    run_starts = np.where(diffs == 1)[0]
    run_ends = np.where(diffs == -1)[0]
    return run_ends - run_starts

def process_mACStatus(df):
    status = df["m_charging"].values

    def _process_feature(status):
        if len(status) == 0:
            return 0., 0., 0., 0., 0.

        # charging 상태 비율, 합
        ratio_charging = status.mean()
        sum_charging = status.sum()

        # 상태전이 횟수
        transitions = (status[1:] != status[:-1]).sum()

        lengths = run_length_encoding(status)
        avg_charging_duration = np.mean(lengths) if len(lengths) > 0 else 0
        max_charging_duration = np.max(lengths) if len(lengths) > 0 else 0

        return ratio_charging, sum_charging, transitions, avg_charging_duration, max_charging_duration

    # 하루
    charging_ratio, charging_sum, chargning_transitions, avg_charging_duration, max_charging_duration = _process_feature(status)

    # 잠자는 시간대
    sleep_status = status[df["hour"].isin(SLEEP_HOURS)]
    sleep_charging_ratio, sleep_charging_sum, sleep_charging_transitions, sleep_avg_charging_duration, sleep_max_charging_duration = _process_feature(sleep_status)

    return pd.Series({
        'charging_ratio': charging_ratio,
        'charging_sum': charging_sum,
        'charging_transitions': chargning_transitions,
        'avg_charging_duration': avg_charging_duration,
        'max_charging_duration': max_charging_duration,
        'sleep_charging_ratio': sleep_charging_ratio,
        'sleep_charging_sum': sleep_charging_sum,
        'sleep_charging_transitions': sleep_charging_transitions,
        'sleep_avg_charging_duration': sleep_avg_charging_duration,
        'sleep_max_charging_duration': sleep_max_charging_duration,
    })

mACStatus_ori = load_data(DataType.mACStatus)
mACStatus_ori = shift_lifelog_date(mACStatus_ori, target_hours=SLEEP_HOURS)

mACStatus2  = (
    mACStatus_ori
    .groupby(["subject_id", "lifelog_date"], group_keys=False, as_index=False, sort=False, observed=True)
    .apply(process_mACStatus)
    .reset_index(drop=True)
)

describe_df(mACStatus2)

# shape:
(803, 12)

# dtypes:
subject_id                           category
lifelog_date                   datetime64[ns]
charging_ratio                        float64
charging_sum                          float64
charging_transitions                  float64
avg_charging_duration                 float64
max_charging_duration                 float64
sleep_charging_ratio                  float64
sleep_charging_sum                    float64
sleep_charging_transitions            float64
sleep_avg_charging_duration           float64
sleep_max_charging_duration           float64
dtype: object

,subject_id,lifelog_date,charging_ratio,charging_sum,charging_transitions,avg_charging_duration,max_charging_duration,sleep_charging_ratio,sleep_charging_sum,sleep_charging_transitions,sleep_avg_charging_duration,sleep_max_charging_duration
0,id01,2024-06-26,0.1498,147.0000,22.0000,13.3636,41.0000,0.0000,0.0000,0.0000,0.0000,0.0000
1,id01,2024-06-27,0.1650,231.0000,33.0000,13.5882,65.0000,0.0300,9.0000,1.0000,9.0000,9.0000
2,id01,2024-06-28,0.3764,527.0000,28.0000,35.1333,356.0000,1.0000,280.0000,0.0000,280.0000,280.0000

# nan_stats:
                             missing_count  missing_ratio(%)
subject_id                               0            0.0000
lifelog_date                             0            0.0000
charging_ratio                           0            0.0000
charging_sum                             0            0.0000
charging_transitions                     0            0.0000
avg_charging_duration                    0            0.0000
max_charging_duration                    0            0.0000
sleep_charging_ratio                     0            0.0000
sleep_charging_sum                       0            0.0000
sleep_charging_transitions               0            0.0000
sleep_avg_charging_duration              0            0.0000
sleep_max_charging_duration              0            0.0000

### ✔️ mActivity 추정행동
- Value calculated by the Google Activity Recognition API.
 - 0 : IN_VEHICLE
 - 1 : ON_BICYCLE
 - 2 : ON_FOOT
 - 3 : STILL (not moving)
 - 4 : UNKNOWN
 - 5 : TILTING (This often occurs when a device is picked up from a desk or a user who is sitting stands up.)
 - 7 : WALKING
 - 8 : RUNNING
- 근무시간   : 오전 7시부터 오후 6시까지
- 근무외시간 : 오후6시부터 12시까지

In [ ]:
def process_mActivity(df):
    activity = df["m_activity"].values.astype("int8")

    EXCLUDE_ACTIVITY = [3, 4]
    WALKING_ACTIVITY = [1, 2, 7, 8]
    VEHICLE_ACTIVITY = [0]

    def _process_feature(activity):
        if len(activity) == 0:
            return 0., 0., 0.

        # Walking minutes
        walking_minutes = np.isin(activity, WALKING_ACTIVITY).sum()

        # Vehicle minutes
        vehicle_minutes = np.isin(activity, VEHICLE_ACTIVITY).sum()

        # Activity minutes
        activity_minutes = (1 - np.isin(activity, EXCLUDE_ACTIVITY)).sum()

        return walking_minutes, vehicle_minutes, activity_minutes

    # 하루
    walking_minutes, vehicle_minutes, activity_minutes = _process_feature(activity)

    # 잠자는 시간대
    sleep_walking_minutes, sleep_vehicle_minutes, sleep_activity_minutes = _process_feature(activity[df["hour"].isin(SLEEP_HOURS)])

    return pd.Series({
        'walking_minutes': walking_minutes,
        'vehicle_minutes': vehicle_minutes,
        'activity_minutes': activity_minutes,
        'sleep_walking_minutes': sleep_walking_minutes,
        'sleep_vehicle_minutes': sleep_vehicle_minutes,
        'sleep_activity_minutes': sleep_activity_minutes,
    })

mActivity_ori = load_data(DataType.mActivity)
mActivity_ori = shift_lifelog_date(mActivity_ori, target_hours=SLEEP_HOURS)

mActivity21 = (
    mActivity_ori
    .groupby(["subject_id", "lifelog_date"], group_keys=False, as_index=False, sort=False, observed=True)
    .apply(process_mActivity)
    .reset_index(drop=True)
)

describe_df(mActivity21)

# shape:
(803, 8)

# dtypes:
subject_id                      category
lifelog_date              datetime64[ns]
walking_minutes                  float64
vehicle_minutes                  float64
activity_minutes                 float64
sleep_walking_minutes            float64
sleep_vehicle_minutes            float64
sleep_activity_minutes           float64
dtype: object

,subject_id,lifelog_date,walking_minutes,vehicle_minutes,activity_minutes,sleep_walking_minutes,sleep_vehicle_minutes,sleep_activity_minutes
0,id01,2024-06-26,32.0000,89.0000,121.0000,0.0000,0.0000,0.0000
1,id01,2024-06-27,31.0000,211.0000,242.0000,0.0000,0.0000,0.0000
2,id01,2024-06-28,37.0000,161.0000,198.0000,0.0000,0.0000,0.0000

# nan_stats:
                        missing_count  missing_ratio(%)
subject_id                          0            0.0000
lifelog_date                        0            0.0000
walking_minutes                     0            0.0000
vehicle_minutes                     0            0.0000
activity_minutes                    0            0.0000
sleep_walking_minutes               0            0.0000
sleep_vehicle_minutes               0            0.0000
sleep_activity_minutes              0            0.0000

### 🔥 mActivity 추정행동2 (NEW)

In [ ]:
mActivity = pd.read_parquet(path+'ch2025_mActivity.parquet')
mActivity['lifelog_date'] = mActivity['timestamp'].astype(str).str[:10]

In [ ]:
# 활동 데이터 원-핫 인코딩
"""활동 코드(m_activity)를 원-핫 인코딩하여 각 활동 유형별 컬럼 생성"""

mActivity = pd.merge(
    mActivity,
    pd.get_dummies(mActivity, columns=["m_activity"], prefix="m_activity", dtype=int),
    how="left",
    on=["subject_id", "timestamp","lifelog_date"],
)

In [ ]:
# 데이터 집계 함수 정의
def fn_love_aespa(
    df_input: pd.DataFrame, # 입력 데이터프레임
    str_value_col: str, # 집계할 컬럼명
    str_agg_func: str = "mean", # 집계 함수 (mean, median, mode, min, max, std, sum)
    str_freq: str = "30min", # 시간 간격 (30min, 60min, 120min, 240min, 360min 등)
) -> pd.DataFrame:
    # 데이터프레임 복사 및 timestamp 열을 datetime 형식으로 변환
    df_input_copy = df_input.copy()
    df_input_copy["timestamp"] = pd.to_datetime(df_input_copy["timestamp"])

    # 집계 결과 컬럼명 생성: @컬럼명@시간간격@집계함수
    str_agg_col_name = f"@{str_value_col}@{str_freq}@{str_agg_func}"

    # 집계 함수 설정 (mode는 별도 처리 필요)
    dict_aggregation = {}
    if str_agg_func == "mode":
        mode_agg_func = lambda x: (x.mode().iloc[0] if not x.mode().empty else np.nan)
        dict_aggregation[str_agg_col_name] = (str_value_col, mode_agg_func)
    else:
        dict_aggregation[str_agg_col_name] = (str_value_col, str_agg_func)

    # 그룹별 데이터 집계 수행
    df_agg = (
        df_input_copy.groupby(["subject_id", pd.Grouper(key="timestamp", freq=str_freq)]).agg(**dict_aggregation).reset_index()
    )

    # 날짜 및 시간 정보 추출
    df_agg["lifelog_date"] = df_agg["timestamp"].dt.date.astype(str)
    df_agg["hh24mi"] = df_agg["timestamp"].dt.strftime("%Hh%Mm")

    # 피벗 테이블로 데이터 재구성 (subject_id, lifelog_date 기준으로 시간대별 값 배치)
    df_pivot = df_agg.pivot_table(
        index=["subject_id", "lifelog_date"],
        columns="hh24mi",
        values=str_agg_col_name,
    )

    # 컬럼 이름 재구성 및 인덱스 초기화
    list_hh23mi_col = list(df_pivot.columns)
    df_pivot = df_pivot.reindex(columns=list_hh23mi_col).reset_index()
    list_hour_col = {hh24mi: f"{str_value_col}@{str_freq}@{str_agg_func}@{hh24mi}" for hh24mi in list_hh23mi_col}
    df_pivot = df_pivot.rename(columns=list_hour_col)

    return df_pivot

In [ ]:
# MET 값 매핑
"""
각 활동 코드에 해당하는 MET(Metabolic Equivalent of Task) 값 할당
MET는 신체 활동의 에너지 소비량을 측정하는 단위

활동 코드별 MET 값:
    0: 1.3 MET (가벼운 좌식 활동)
    1: 8.0 MET (격렬한 활동)
    3: 1.2 MET (매우 가벼운 활동)
    4: 3.0 MET (중간 강도 활동)
    7: 3.5 MET (중간 강도 활동)
    8: 10.0 MET (매우 격렬한 활동)
"""

dict_met_value = {0: 1.3, 1: 8.0, 3: 1.2, 4: 3.0, 7: 3.5, 8: 10.0}
for activity, met in dict_met_value.items():
    mActivity.loc[mActivity["m_activity"].isin([activity]), "m_activity_met"] = met

mActivity.head(5)

,subject_id,timestamp,m_activity,lifelog_date,m_activity_0,m_activity_1,m_activity_3,m_activity_4,m_activity_7,m_activity_8,m_activity_met
0,id01,2024-06-26 12:03:00,4,2024-06-26,0,0,0,1,0,0,3.0000
1,id01,2024-06-26 12:04:00,0,2024-06-26,1,0,0,0,0,0,1.3000
2,id01,2024-06-26 12:05:00,0,2024-06-26,1,0,0,0,0,0,1.3000
3,id01,2024-06-26 12:06:00,0,2024-06-26,1,0,0,0,0,0,1.3000
4,id01,2024-06-26 12:07:00,0,2024-06-26,1,0,0,0,0,0,1.3000

In [ ]:
# 활동 데이터 집계
df_agg_activity_std = fn_love_aespa(df_input=mActivity,
                                    str_value_col="m_activity",
                                    # "mean", "median", "mode", "min", "max", "std"
                                    str_agg_func="std",
                                    # "30min", "60min", "120min", "240min", "360min", "480min", "720min", "1440min"
                                    str_freq="240min",
                                    )

df_agg_activity_met_std = fn_love_aespa(df_input=mActivity,
                                    str_value_col="m_activity_met",
                                    # "mean", "median", "mode", "sum", "min", "max", "std"
                                    str_agg_func="std",
                                    # "30min", "60min", "120min", "240min", "360min", "480min", "720min", "1440min"
                                    str_freq="240min",
                                    )

df_agg_activity_met_sum = fn_love_aespa(df_input=mActivity,
                                    str_value_col="m_activity_met",
                                    # "mean", "median", "mode", "sum", "min", "max", "std"
                                    str_agg_func="sum",
                                    # "30min", "60min", "120min", "240min", "360min", "480min", "720min", "1440min"
                                    str_freq="240min",
                                    )

df_agg_activity_0_std = fn_love_aespa(df_input=mActivity,
                                    str_value_col="m_activity_0",
                                    # "mean", "median", "mode", "sum", "min", "max", "std"
                                    str_agg_func="std",
                                    # "30min", "60min", "120min", "240min", "360min", "480min", "720min", "1440min"
                                    str_freq="240min",
                                    )

df_agg_activity_0_sum = fn_love_aespa(df_input=mActivity,
                                    str_value_col="m_activity_0",
                                    # "mean", "median", "mode", "sum", "min", "max", "std"
                                    str_agg_func="sum",
                                    # "30min", "60min", "120min", "240min", "360min", "480min", "720min", "1440min"
                                    str_freq="240min",
                                    )

In [ ]:
# 병합 기준 key
merge_keys = ['subject_id', 'lifelog_date']

# 세 개 데이터프레임 순차 병합
mActivity22 = (
    df_agg_activity_std
    .merge(df_agg_activity_met_std, on=merge_keys, how='outer')
    .merge(df_agg_activity_met_sum, on=merge_keys, how='outer')
    .merge(df_agg_activity_0_std, on=merge_keys, how='outer')
    .merge(df_agg_activity_0_sum, on=merge_keys, how='outer')
)

# check
print(mActivity22.shape)

(700, 32)

### ✔️ mAmbience 주변소리 (수정)
- Ambient sound identification labels and their respective probabilities.
- 무슨 소리가 난게 중요할까?
- 새벽에 무슨 소리던지 소리가 난게 중요한 걸까?
- 여러 가지 소리 중에 노이즈도 포함되어 있을까?

In [ ]:
def process_mAmbience(df):
    ambience = df["m_ambience"].values  # [[label, prob], ...], [[label, prob], ...]

    def _process_feature(ambience):
        labels = set()

        for amb in ambience:
            labels_, _ = zip(*amb)
            labels.update(labels_)

        unique_label_count = len(labels)
        snor_count = len(list(filter(lambda x: "snor" in x.lower(), labels)))

        return unique_label_count, snor_count

    # 활동시간
    active_hour_unique_label_count, active_hour_snor_count = _process_feature(ambience[df["hour"].isin(ACTIVE_HOURS)])

    # 잠자는시간
    sleep_hour_unique_label_count, sleep_hour_snor_count = _process_feature(ambience[df["hour"].isin(SLEEP_HOURS)])

    return pd.Series({
        'active_hour_unique_label_count': active_hour_unique_label_count,
        'active_hour_snor_count': active_hour_snor_count,
        'sleep_hour_unique_label_count': sleep_hour_unique_label_count,
        'sleep_hour_snor_count': sleep_hour_snor_count,
    })

mAmbience_ori = load_data(DataType.mAmbience)
mAmbience_ori = shift_lifelog_date(mAmbience_ori, target_hours=SLEEP_HOURS)

mAmbience2 = (
    mAmbience_ori
    .groupby(["subject_id", "lifelog_date"], group_keys=False, as_index=False, sort=False, observed=True)
    .apply(process_mAmbience)
    .reset_index(drop=True)
)

describe_df(mAmbience2)

# shape:
(803, 6)

# dtypes:
subject_id                              category
lifelog_date                      datetime64[ns]
active_hour_unique_label_count             int64
active_hour_snor_count                     int64
sleep_hour_unique_label_count              int64
sleep_hour_snor_count                      int64
dtype: object

,subject_id,lifelog_date,active_hour_unique_label_count,active_hour_snor_count,sleep_hour_unique_label_count,sleep_hour_snor_count
0,id01,2024-06-26,265,2,10,0
1,id01,2024-06-27,10,0,10,0
2,id01,2024-06-28,14,0,10,0

# nan_stats:
                                missing_count  missing_ratio(%)
subject_id                                  0            0.0000
lifelog_date                                0            0.0000
active_hour_unique_label_count              0            0.0000
active_hour_snor_count                      0            0.0000
sleep_hour_unique_label_count               0            0.0000
sleep_hour_snor_count                       0            0.0000

### ✔️ mBle 블루투스 (수정)
- Bluetooth devices around individual subject.
 - 7936 : Wearable, Headset, AV Device
 - 1796 : Peripheral (입력장치) 계열
 - 0 : 정보 없음 또는 알 수 없음(Unknown)
 - 1084 : Audio/Video (스피커, 헤드셋, 이어폰, TV 등)
 - 524 : Phone (휴대폰, 스마트폰)
 - 1060 : Headphones
 - 284 : commputer (PC, 노트북, PDA)

In [ ]:
def process_mBle(df):
    ble = df["m_ble"].values  # [[{"address": "xx:xx:xx:xx:xx:xx", "device_class": "0", "rssi": -70}, ...], [...], ...]

    def _process_feature(ble):
        if len(ble) == 0:
            return 0., 0., 0., 0., 0.

        rssi = []
        devices = []
        for ble_data in ble:
            for device in ble_data:
                rssi.append(device["rssi"])
                devices.append(device["device_class"])

        rssi = np.array(rssi)
        rssi_mean = rssi.mean() if len(rssi) > 0 else 0
        rssi_min = rssi.min() if len(rssi) > 0 else 0
        rssi_max = rssi.max() if len(rssi) > 0 else 0

        unknown_count = devices.count("0")
        others_count = len(devices) - unknown_count
        others_ratio = others_count / len(devices) if len(devices) > 0 else 0
        unknown_ratio = unknown_count / len(devices) if len(devices) > 0 else 0

        return rssi_mean, rssi_min, rssi_max, others_ratio, unknown_ratio

    # 일할때
    work_hour_rssi_mean, work_hour_rssi_min, work_hour_rssi_max, work_hour_others_ratio, work_hour_unknown_ratio = _process_feature(ble[df["hour"].isin(WORK_HOURS)])

    # 퇴근후
    free_hour_rssi_mean, free_hour_rssi_min, free_hour_rssi_max, free_hour_others_ratio, free_hour_unknown_ratio = _process_feature(ble[df["hour"].isin(FREE_HOURS)])

    # 잠자는시간
    sleep_hour_rssi_mean, sleep_hour_rssi_min, sleep_hour_rssi_max, sleep_hour_others_ratio, sleep_hour_unknown_ratio = _process_feature(ble[df["hour"].isin(SLEEP_HOURS)])

    return pd.Series({
        'work_hour_rssi_mean': work_hour_rssi_mean,
        'work_hour_rssi_min': work_hour_rssi_min,
        'work_hour_rssi_max': work_hour_rssi_max,
        'work_hour_others_ratio': work_hour_others_ratio,
        'work_hour_unknown_ratio': work_hour_unknown_ratio,
        'free_hour_rssi_mean': free_hour_rssi_mean,
        'free_hour_rssi_min': free_hour_rssi_min,
        'free_hour_rssi_max': free_hour_rssi_max,
        'free_hour_others_ratio': free_hour_others_ratio,
        'free_hour_unknown_ratio': free_hour_unknown_ratio,
        'sleep_hour_rssi_mean': sleep_hour_rssi_mean,
        'sleep_hour_rssi_min': sleep_hour_rssi_min,
        'sleep_hour_rssi_max': sleep_hour_rssi_max,
        'sleep_hour_others_ratio': sleep_hour_others_ratio,
        'sleep_hour_unknown_ratio': sleep_hour_unknown_ratio
    })

mBle_ori = load_data(DataType.mBle)
mBle_ori = shift_lifelog_date(mBle_ori, target_hours=SLEEP_HOURS)

mBle2 = (
    mBle_ori
    .groupby(["subject_id", "lifelog_date"], group_keys=False, as_index=False, sort=False, observed=True)
    .apply(process_mBle)
    .reset_index(drop=True)
)

describe_df(mBle2)

# shape:
(709, 17)

# dtypes:
subject_id                        category
lifelog_date                datetime64[ns]
work_hour_rssi_mean                float64
work_hour_rssi_min                 float64
work_hour_rssi_max                 float64
work_hour_others_ratio             float64
work_hour_unknown_ratio            float64
free_hour_rssi_mean                float64
free_hour_rssi_min                 float64
free_hour_rssi_max                 float64
free_hour_others_ratio             float64
free_hour_unknown_ratio            float64
sleep_hour_rssi_mean               float64
sleep_hour_rssi_min                float64
sleep_hour_rssi_max                float64
sleep_hour_others_ratio            float64
sleep_hour_unknown_ratio           float64
dtype: object

,subject_id,lifelog_date,work_hour_rssi_mean,work_hour_rssi_min,work_hour_rssi_max,work_hour_others_ratio,work_hour_unknown_ratio,free_hour_rssi_mean,free_hour_rssi_min,free_hour_rssi_max,free_hour_others_ratio,free_hour_unknown_ratio,sleep_hour_rssi_mean,sleep_hour_rssi_min,sleep_hour_rssi_max,sleep_hour_others_ratio,sleep_hour_unknown_ratio
0,id01,2024-06-26,-74.0904,-94.0000,-27.0000,0.0590,0.9410,-77.2213,-92.0000,-43.0000,0.0791,0.9209,0.0000,0.0000,0.0000,0.0000,0.0000
1,id01,2024-06-27,-73.7473,-94.0000,-34.0000,0.0614,0.9386,-74.6667,-91.0000,-42.0000,0.1167,0.8833,0.0000,0.0000,0.0000,0.0000,0.0000
2,id01,2024-06-28,-75.7993,-92.0000,-39.0000,0.0467,0.9533,-77.2558,-94.0000,-51.0000,0.3256,0.6744,0.0000,0.0000,0.0000,0.0000,0.0000

# nan_stats:
                          missing_count  missing_ratio(%)
subject_id                            0            0.0000
lifelog_date                          0            0.0000
work_hour_rssi_mean                   0            0.0000
work_hour_rssi_min                    0            0.0000
work_hour_rssi_max                    0            0.0000
work_hour_others_ratio                0            0.0000
work_hour_unknown_ratio               0            0.0000
free_hour_rssi_mean                   0            0.0000
free_hour_rssi_min                    0            0.0000
free_hour_rssi_max                    0            0.0000
free_hour_others_ratio                0            0.0000
free_hour_unknown_ratio               0            0.0000
sleep_hour_rssi_mean                  0            0.0000
sleep_hour_rssi_min                   0            0.0000
sleep_hour_rssi_max                   0            0.0000
sleep_hour_others_ratio               0            0.0000
sleep_hour_unknown_ratio              0            0.0000

### ✔️ mGps, GPS 기반 핸드폰 위치
- Multiple GPS coordinates measured within a single minute using the smartphone.
- speed가 1보다 큰경우 정지 상태가 아니고 움직이고 있다고 판단
 - 0.5-2 : 걸어서 이동하는 경우  
 - 2-5 : 조깅
 - 5 이상 : 차를 타고 이동하는 경우

- speed가 0.5-2사이를 하루에 몇분동안 지속했는지?
- speed가 2-5사이를 하루에 몇분동안 지속했는지? (유산소 운동 시간)
- speed가 5이상을 하루에 몇분동안 지속했는지?

In [ ]:
from datetime import datetime

def haversine_np(lon1, lat1, lon2, lat2, radius=6371):
    lon1, lat1, lon2, lat2 = map(np.radians, [lon1, lat1, lon2, lat2])

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = np.sin(dlat / 2.0)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon / 2.0)**2
    c = 2 * np.arcsin(np.sqrt(a))

    return radius * c

def process_mGps(df):
    gps = df["m_gps"].values  # [[{'altitude': 110.6, 'latitude': 0.2077385, 'longitude': 0.170027, 'speed': 0.0}, ...], ...]
    timestamps = df["timestamp"].values

    def _process_feature(gps, timestamps):
        if len(gps) == 0:
            return 0., 0., 0., 0., 0., 0., 0., np.array([])

        # n-분 단위
        latitudes = []
        longitudes = []
        altitudes = []
        speeds = []
        minutes = []  # 누적 분

        for i, (gps_data, timestamp) in enumerate(zip(gps, timestamps)):
            _latitudes = []
            _longitudes = []
            _altitudes = []
            _speeds = []
            for data in gps_data:
                _latitudes.append(data["latitude"])
                _longitudes.append(data["longitude"])
                _altitudes.append(data["altitude"])
                _speeds.append(data["speed"])

            latitudes.append(np.mean(_latitudes))
            longitudes.append(np.mean(_longitudes))
            altitudes.append(np.mean(_altitudes))
            speeds.append(np.mean(_speeds))
            minutes.append(1 if i == 0 else pd.Timedelta(timestamps[i] - timestamps[i-1]).total_seconds() / 60)

        latitudes = np.array(latitudes)
        longitudes = np.array(longitudes)
        altitudes = np.array(altitudes)
        speeds = np.array(speeds)
        minutes = np.array(minutes)

        walk_minutes = minutes[(speeds >= 0.5) & (speeds < 2.0)].sum()
        jog_minutes = minutes[(2.0 <= speeds) & (speeds < 5.0)].sum()
        vehicle_minutes = minutes[(5.0 <= speeds)].sum()

        # 속도
        mean_speed = speeds.mean() if len(speeds) > 0 else 0
        max_speed = speeds.max() if len(speeds) > 0 else 0
        min_speed = speeds.min() if len(speeds) > 0 else 0

        # 이동거리
        distance = haversine_np(longitudes[:-1], latitudes[:-1], longitudes[1:], latitudes[1:]).sum()

        return walk_minutes, jog_minutes, vehicle_minutes, mean_speed, max_speed, min_speed, distance, speeds

    # 하루
    active_hour_walk_minutes, active_hour_jog_minutes, active_hour_vehicle_minutes, active_hour_mean_speed, active_hour_max_speed, active_hour_min_speed, active_hour_distance, _ = _process_feature(gps[df["hour"].isin(ACTIVE_HOURS)], timestamps[df["hour"].isin(ACTIVE_HOURS)])

    # 잠자는 시간대
    sleep_hour_walk_minutes, sleep_hour_jog_minutes, sleep_hour_vehicle_minutes, sleep_hour_mean_speed, sleep_hour_max_speed, sleep_hour_min_speed, sleep_hour_distance, _ = _process_feature(gps[df["hour"].isin(SLEEP_HOURS)], timestamps[df["hour"].isin(SLEEP_HOURS)])

    # 일어날 때
    _, _, _, _, _, _, _, might_wakeup_speeds = _process_feature(gps[df["hour"].isin(MIGHT_WAKEUP_HOURS)], timestamps[df["hour"].isin(MIGHT_WAKEUP_HOURS)])
    might_wakeup_timestamps = timestamps[df["hour"].isin(MIGHT_WAKEUP_HOURS)]
    wakeup_timestamps = might_wakeup_timestamps[(might_wakeup_speeds > 1.0)]
    first_move_datetime = (
        pd.to_datetime(wakeup_timestamps[0]) if len(wakeup_timestamps) > 0
        else pd.to_datetime(might_wakeup_timestamps[-1]) if len(might_wakeup_timestamps) > 0
        else pd.to_datetime(datetime(2024, 1, 1, MIGHT_WAKEUP_HOURS[-1], 0, 0))  # default to the last hour of the range
    )
    first_wakeup_minutes = (first_move_datetime.hour if first_move_datetime.hour > 12 else first_move_datetime.hour + 24) * 60 + first_move_datetime.minute

    return pd.Series({
        'active_hour_walk_minutes': active_hour_walk_minutes,
        'active_hour_jog_minutes': active_hour_jog_minutes,
        'active_hour_vehicle_minutes': active_hour_vehicle_minutes,
        'active_hour_mean_speed': active_hour_mean_speed,
        'active_hour_max_speed': active_hour_max_speed,
        'active_hour_min_speed': active_hour_min_speed,
        'active_hour_distance': active_hour_distance,
        'exercise_flag': 1 if active_hour_jog_minutes > 10 else 0,  # n분 이상 조깅한 경우
        'sleep_hour_walk_minutes': sleep_hour_walk_minutes,
        'sleep_hour_jog_minutes': sleep_hour_jog_minutes,
        'sleep_hour_vehicle_minutes': sleep_hour_vehicle_minutes,
        'sleep_hour_mean_speed': sleep_hour_mean_speed,
        'sleep_hour_max_speed': sleep_hour_max_speed,
        'sleep_hour_min_speed': sleep_hour_min_speed,
        'sleep_hour_distance': sleep_hour_distance,
        "mgps_first_wakeup_minutes": first_wakeup_minutes,
    })


mGps_ori = load_data(DataType.mGps)
mGps_ori = shift_lifelog_date(mGps_ori, target_hours=SLEEP_HOURS)

mGps2 = (
    mGps_ori
    .groupby(["subject_id", "lifelog_date"], group_keys=False, as_index=False, sort=False, observed=True)
    .apply(process_mGps)
    .reset_index(drop=True)
)

describe_df(mGps2)

# shape:
(759, 18)

# dtypes:
subject_id                           category
lifelog_date                   datetime64[ns]
active_hour_walk_minutes              float64
active_hour_jog_minutes               float64
active_hour_vehicle_minutes           float64
active_hour_mean_speed                float64
active_hour_max_speed                 float64
active_hour_min_speed                 float64
active_hour_distance                  float64
exercise_flag                         float64
sleep_hour_walk_minutes               float64
sleep_hour_jog_minutes                float64
sleep_hour_vehicle_minutes            float64
sleep_hour_mean_speed                 float64
sleep_hour_max_speed                  float64
sleep_hour_min_speed                  float64
sleep_hour_distance                   float64
mgps_first_wakeup_minutes             float64
dtype: object

,subject_id,lifelog_date,active_hour_walk_minutes,active_hour_jog_minutes,active_hour_vehicle_minutes,active_hour_mean_speed,active_hour_max_speed,active_hour_min_speed,active_hour_distance,exercise_flag,sleep_hour_walk_minutes,sleep_hour_jog_minutes,sleep_hour_vehicle_minutes,sleep_hour_mean_speed,sleep_hour_max_speed,sleep_hour_min_speed,sleep_hour_distance,mgps_first_wakeup_minutes
0,id01,2024-06-26,68.0000,32.0000,19.0000,0.5775,19.0505,0.0000,16.7900,1.0000,36.0000,0.0000,0.0000,0.1812,1.6664,0.0000,0.1752,1980.0000
1,id01,2024-06-27,136.0000,61.0000,66.0000,1.0368,24.2032,0.0000,32.2769,1.0000,1.0000,0.0000,0.0000,0.0424,0.5080,0.0000,0.0647,1831.0000
2,id01,2024-06-28,106.0000,68.0000,42.0000,0.8060,24.1712,0.0001,35.5108,1.0000,19.0000,0.0000,0.0000,0.3053,0.8415,0.0987,0.4590,1834.0000

# nan_stats:
                             missing_count  missing_ratio(%)
subject_id                               0            0.0000
lifelog_date                             0            0.0000
active_hour_walk_minutes                 0            0.0000
active_hour_jog_minutes                  0            0.0000
active_hour_vehicle_minutes              0            0.0000
active_hour_mean_speed                   0            0.0000
active_hour_max_speed                    0            0.0000
active_hour_min_speed                    0            0.0000
active_hour_distance                     0            0.0000
exercise_flag                            0            0.0000
sleep_hour_walk_minutes                  0            0.0000
sleep_hour_jog_minutes                   0            0.0000
sleep_hour_vehicle_minutes               0            0.0000
sleep_hour_mean_speed                    0            0.0000
sleep_hour_max_speed                     0            0.0000
sleep_hour_min_speed                     0            0.0000
sleep_hour_distance                      0            0.0000
mgps_first_wakeup_minutes                0            0.0000

### 🔥 mLight 주변 밝기
- Ambient light measured by the smartphone.
 - 어두운 밤	0.1 ~ 1 lux	캄캄한 방, 달빛 없는 밤
 - 가로등 켜진 거리	10 ~ 20 lux	흐릿한 외부 조명
 - 실내 조명	100 ~ 500 lux	사무실, 일반 거실
 - 밝은 실외	10,000 ~ 25,000 lux	맑은 날 햇빛
 - 직사광선 아래	30,000 ~ 100,000 lux	여름 한낮, 매우 강한 햇빛

- 밝기에 따라서 언제 불을 끄고 잠든 시간 추정
- 직사광선 잠에 좋은 영향을 주는지? (논문)
- 결측치 처리 x

In [ ]:
mLight['lifelog_date'] = mLight['timestamp'].astype(str).str[:10]
# mLight = fill_missing_dates_by_subject(mLight)
mLight.head()

  subject_id           timestamp  m_light lifelog_date
0       id01 2024-06-26 12:03:00 534.0000   2024-06-26
1       id01 2024-06-26 12:13:00 846.0000   2024-06-26
2       id01 2024-06-26 12:23:00 826.0000   2024-06-26
3       id01 2024-06-26 12:33:00 851.0000   2024-06-26
4       id01 2024-06-26 12:43:00 428.0000   2024-06-26

In [ ]:
def process_mLight(df):
    df = df.copy()
    df['timestamp'] = pd.to_datetime(df['timestamp'])
    df['lifelog_date'] = df['timestamp'].dt.date
    df['hour'] = df['timestamp'].dt.hour
    df['is_night'] = df['hour'].apply(lambda h: h >= 22 or h < 6)

    # 하루 요약 통계
    daily_light = df.groupby(['subject_id', 'lifelog_date']).agg(
        light_mean=('m_light', 'mean'),
        light_std=('m_light', 'std'),
        light_max=('m_light', 'max'),
        light_min=('m_light', 'min'),
        light_night_mean=('m_light', lambda x: x[df.loc[x.index, 'is_night']].mean()),
        light_day_mean=('m_light', lambda x: x[~df.loc[x.index, 'is_night']].mean()),
        light_night_ratio=('is_night', 'mean')
    ).reset_index()

    results = []

    for subject_id, group in tqdm(df.groupby('subject_id'), desc="Processing light-based sleep detection"):
        group = group.sort_values('timestamp').reset_index(drop=True)

        recorded_dates = set()
        sleeping = False
        zero_count = 0
        first_zero_time = None

        for i in range(len(group)):
            light = group.loc[i, 'm_light']
            hour = group.loc[i, 'hour']

            if light == 0:
                zero_count += 1
                if zero_count == 1:
                    first_zero_time = group.loc[i, 'timestamp']
                if zero_count >= 6 and not sleeping:
                    sleep_hour = first_zero_time.hour
                    if (sleep_hour >= 21 or sleep_hour <= 2):
                        sleeping = True
            else:
                if sleeping:
                    candidate_wakeup = group.loc[i, 'timestamp']
                    wake_hour = candidate_wakeup.hour

                    if 5 <= wake_hour <= 9 and first_zero_time is not None:
                        wake_time = candidate_wakeup
                        sleep_time = first_zero_time
                        duration_min = (wake_time - sleep_time).total_seconds() / 60

                        if 0 < duration_min <= 840:
                            sleep_duration = duration_min
                        else:
                            sleep_duration = np.nan

                        lifelog_date = wake_time.date() + pd.Timedelta(days=-1)

                        if lifelog_date not in recorded_dates:
                            results.append({
                                'subject_id': subject_id,
                                'lifelog_date': lifelog_date,
                                'sleep_duration_min_mLight': sleep_duration,
                                'sleep_time_min_mLight': sleep_time.hour * 60 + sleep_time.minute,
                                'wake_time_min_mLight': wake_time.hour * 60 + wake_time.minute,
                                'hour_slept_mLight': sleep_time.hour + sleep_time.minute / 60,
                                'hour_woke_up_mLight': wake_time.hour + wake_time.minute / 60
                            })
                            recorded_dates.add(lifelog_date)

                        sleeping = False
                        zero_count = 0
                        first_zero_time = None

            if light > 0:
                zero_count = 0
                first_zero_time = None

    sleep_df = pd.DataFrame(results)

    # 정렬 + 보간
    sleep_df = sleep_df.sort_values(['subject_id', 'lifelog_date'])
    sleep_df['sleep_duration_interp_mLight'] = sleep_df.groupby('subject_id')['sleep_duration_min_mLight'].transform(lambda x: x.interpolate())

    # 시간 단위 파생 컬럼
    sleep_df['sleep_duration_hour_mLight'] = sleep_df['sleep_duration_min_mLight'] / 60
    sleep_df['sleep_duration_interp_hour_mLight'] = sleep_df['sleep_duration_interp_mLight'] / 60

    # 병합
    final = pd.merge(daily_light, sleep_df, on=['subject_id', 'lifelog_date'], how='left')

    return final

In [ ]:
def process_mLight2(df):
    from datetime import datetime, timedelta

    df = df.copy()
    df['timestamp'] = pd.to_datetime(df['timestamp'])
    df['lifelog_date'] = pd.to_datetime(df['lifelog_date'])

    # m_light > 0 → m_screen_use로 변환
    df['m_light_on'] = (df['m_light'] > 0).astype(int)

    # base key 확보
    base_keys = df[['subject_id', 'lifelog_date']].drop_duplicates()
    base_keys['lifelog_date'] = base_keys['lifelog_date'].dt.date

    # 밤 9시 ~ 다음날 오전 11시 필터링
    df['hour'] = df['timestamp'].dt.hour
    df = df[(df['hour'] >= 21) | (df['hour'] < 11)].copy()
    df.loc[df['hour'] < 11, 'lifelog_date'] -= pd.Timedelta(days=1)

    df.sort_values(['subject_id', 'timestamp'], inplace=True)

    results = []

    for (subject_id, lifelog_date), group in df.groupby(['subject_id', 'lifelog_date']):
        group = group.sort_values('timestamp').reset_index(drop=True)

        # 1. 중간 각성 제거
        prev = group['m_light_on'].shift(1)
        next_ = group['m_light_on'].shift(-1)
        mask = (group['m_light_on'] == 1) & (prev == 0) & (next_ == 0)
        group.loc[mask, 'm_light_on'] = 0

        # 2. 짧은 각성 블록 제거
        group['is_sleep'] = group['m_light_on'] == 0
        group['block'] = (group['is_sleep'] != group['is_sleep'].shift()).cumsum()
        block_info = group.groupby('block').agg(
            is_sleep=('is_sleep', 'first'),
            size=('is_sleep', 'size')
        )

        for i in range(1, len(block_info) - 1):
            if (
                block_info.iloc[i]['is_sleep'] == False and
                block_info.iloc[i]['size'] <= 2 and
                block_info.iloc[i - 1]['is_sleep'] and
                block_info.iloc[i + 1]['is_sleep']
            ):
                group.loc[group['block'] == block_info.index[i], 'm_light_on'] = 0

        # 3. 수면 블록 추정
        group['is_sleep'] = group['m_light_on'] == 0
        group['block'] = (group['is_sleep'] != group['is_sleep'].shift()).cumsum()
        sleep_blocks = group[group['is_sleep']].groupby('block').agg(
            sleep_start=('timestamp', 'first'),
            sleep_end=('timestamp', 'last'),
            duration_min=('timestamp', lambda x: (x.max() - x.min()).total_seconds() / 60)
        )

        sleep_time = wake_time = duration_min = None
        if not sleep_blocks.empty:
            longest_sleep = sleep_blocks.loc[sleep_blocks['duration_min'].idxmax()]
            sleep_time = longest_sleep['sleep_start'].time()
            wake_time = longest_sleep['sleep_end'].time()
            duration_min = longest_sleep['duration_min']

            # 유효성 조건
            if not (4 <= wake_time.hour < 11):
                wake_time = None
            if not (sleep_time.hour >= 21 or sleep_time.hour < 3):
                sleep_time = None
            if duration_min < 100:
                sleep_time = None
                wake_time = None
                duration_min = None

        results.append({
            'subject_id': subject_id,
            'lifelog_date': lifelog_date.date(),
            'sleep_time': sleep_time,
            'wake_time': wake_time,
            'sleep_duration_min': round(duration_min, 1) if duration_min is not None else None
        })

    sleep_df = pd.DataFrame(results)
    result_df = base_keys.merge(sleep_df, on=['subject_id', 'lifelog_date'], how='left')

    # 시간 → 실수형 숫자 변환
    def time_to_float(t):
        if pd.isna(t):
            return None
        return round(t.hour + t.minute / 60 + t.second / 3600, 4)

    result_df['sleep_time'] = result_df['sleep_time'].apply(time_to_float)
    result_df['wake_time'] = result_df['wake_time'].apply(time_to_float)

    return result_df

In [ ]:
def add_ratios(df):
    df = df.copy()
    df['lifelog_date'] = pd.to_datetime(df['lifelog_date'])
    df['weekday'] = df['lifelog_date'].dt.weekday
    df['week_type'] = df['weekday'].apply(lambda x: 'weekend' if x >= 5 else 'weekday')
    df['month'] = df['lifelog_date'].dt.month

    # 평균 계산
    avg_duration = df.groupby(['subject_id', 'month', 'week_type'])['sleep_duration_min'].mean().reset_index(name='avg_sleep_duration')
    sleep_time_avg = df.groupby(['subject_id', 'month', 'week_type'])['sleep_time'].apply(calculate_circular_mean_sleep_time).reset_index(name='avg_sleep_time')
    wake_time_avg = df.groupby(['subject_id', 'month', 'week_type'])['wake_time'].apply(calculate_circular_mean_sleep_time).reset_index(name='avg_wake_time')
    avg_df = sleep_time_avg.merge(wake_time_avg, on=['subject_id', 'month', 'week_type']).merge(avg_duration, on=['subject_id', 'month', 'week_type'])
    df = df.merge(avg_df, on=['subject_id', 'month', 'week_type'], how='left')

    # 비율 및 차이
    df['sleep_time_diff'] = df['avg_sleep_time'] - df['sleep_time']
    df['wake_time_diff'] = df['avg_wake_time'] - df['wake_time']
    df['sleep_duration_diff'] = df['avg_sleep_duration'] - df['sleep_duration_min']
    df['sleep_time_ratio'] = df['sleep_time'] / df['avg_sleep_time']
    df['wake_time_ratio'] = df['wake_time'] / df['avg_wake_time']
    df['sleep_duration_ratio'] = df['sleep_duration_min'] / df['avg_sleep_duration']

    # 정렬 후 lag/변화량
    df = df.sort_values(['subject_id', 'lifelog_date'])
    for lag in [1, 2]:
        df[f'sleep_time_lag{lag}'] = df.groupby('subject_id')['sleep_time'].shift(lag)
        df[f'wake_time_lag{lag}'] = df.groupby('subject_id')['wake_time'].shift(lag)
        df[f'sleep_duration_lag{lag}'] = df.groupby('subject_id')['sleep_duration_min'].shift(lag)
        df[f'sleep_time_diff_lag{lag}'] = df.groupby('subject_id')['sleep_time'].diff(lag)
        df[f'wake_time_diff_lag{lag}'] = df.groupby('subject_id')['wake_time'].diff(lag)
        df[f'sleep_duration_diff_lag{lag}'] = df.groupby('subject_id')['sleep_duration_min'].diff(lag)
    df['week_type_lag1'] = df.groupby('subject_id')['week_type'].shift(1)

    # 이동 평균 (2,3)
    for window in [2, 3]:
        df[f'rolling_sleep_time_{window}d'] = df.groupby('subject_id')['sleep_time'].rolling(window=window, min_periods=1).mean().reset_index(level=0, drop=True)
        df[f'rolling_wake_time_{window}d'] = df.groupby('subject_id')['wake_time'].rolling(window=window, min_periods=1).mean().reset_index(level=0, drop=True)
        df[f'rolling_sleep_duration_{window}d'] = df.groupby('subject_id')['sleep_duration_min'].rolling(window=window, min_periods=1).mean().reset_index(level=0, drop=True)

    # 요일별 평균 수면 비교
    weekday_avg = df.groupby(['subject_id', 'weekday'])['sleep_duration_min'].mean().reset_index(name='weekday_avg_sleep')
    df = df.merge(weekday_avg, on=['subject_id', 'weekday'], how='left')
    df['sleep_duration_vs_weekday_avg'] = df['sleep_duration_min'] - df['weekday_avg_sleep']

    # 급격한 수면시간 변화 여부 (60분 이상 변화)
    df['is_sleep_duration_change_large'] = (df['sleep_duration_diff_lag1'].abs() > 60).astype(int)

    return df

In [ ]:
mLight21 = process_mLight(mLight)

# check
print(f'\n # mLight21 shape: {mLight21.shape}')
mLight21.head(1)

Processing light-based sleep detection:   0%|          | 0/10 [00:00<?, ?it/s]

 # mLight21 shape: (700, 17)

,subject_id,lifelog_date,light_mean,light_std,light_max,light_min,light_night_mean,light_day_mean,light_night_ratio,sleep_duration_min_mLight,sleep_time_min_mLight,wake_time_min_mLight,hour_slept_mLight,hour_woke_up_mLight,sleep_duration_interp_mLight,sleep_duration_hour_mLight,sleep_duration_interp_hour_mLight
0,id01,2024-06-26,364.5068,395.6594,1886.0000,0.0000,184.9231,403.4167,0.1781,340.0000,1409.0000,309.0000,23.4833,5.1500,340.0000,5.6667,5.6667

In [ ]:
mLight22 = process_mLight2(mLight)
mLight22['sleep_time'] = np.where(mLight22['sleep_time']<10,mLight22['sleep_time']+24,mLight22['sleep_time'])
mLight22['sleep_duration_min'] = mLight22.apply(lambda x: calculate_sleep_duration_min(x['sleep_time'],x['wake_time']),axis=1)
mLight22 = add_ratios(mLight22)
mLight22 = mLight22.drop(columns=['week_type','wake_time_lag1'])
mLight22.columns = ['subject_id', 'lifelog_date']+['light_'+i for i in mLight22.columns if i not in ['subject_id', 'lifelog_date']]
mLight22['lifelog_date'] = mLight22['lifelog_date'].astype(str)

# check
# mLight22 shape: (700, 55)
print(f'\n # mLight22 shape: {mLight22.shape}')
mLight22.head(1)

 # mLight22 shape: (700, 37)

,subject_id,lifelog_date,light_sleep_time,light_wake_time,light_sleep_duration_min,light_weekday,light_month,light_avg_sleep_time,light_avg_wake_time,light_avg_sleep_duration,light_sleep_time_diff,light_wake_time_diff,light_sleep_duration_diff,light_sleep_time_ratio,light_wake_time_ratio,light_sleep_duration_ratio,light_sleep_time_lag1,light_sleep_duration_lag1,light_sleep_time_diff_lag1,light_wake_time_diff_lag1,light_sleep_duration_diff_lag1,light_sleep_time_lag2,light_wake_time_lag2,light_sleep_duration_lag2,light_sleep_time_diff_lag2,light_wake_time_diff_lag2,light_sleep_duration_diff_lag2,light_week_type_lag1,light_rolling_sleep_time_2d,light_rolling_wake_time_2d,light_rolling_sleep_duration_2d,light_rolling_sleep_time_3d,light_rolling_wake_time_3d,light_rolling_sleep_duration_3d,light_weekday_avg_sleep,light_sleep_duration_vs_weekday_avg,light_is_sleep_duration_change_large
0,id01,2024-06-26,23.4833,4.9833,330.0000,2,6,23.3722,5.0944,343.3333,-0.1111,0.1111,13.3333,1.0048,0.9782,0.9612,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.4833,4.9833,330.0000,23.4833,4.9833,330.0000,358.2000,-28.2000,0

In [ ]:
def estimate_lights_off_time(df, light_threshold=2):

    # 시간 → 실수형 (예: 23:30 → 23.5)
    def time_to_float(t):
        if pd.isna(t):
            return None
        return round(t.hour + t.minute / 60 + t.second / 3600, 4)

    df = df.copy()
    df['timestamp'] = pd.to_datetime(df['timestamp'])
    df['lifelog_date'] = pd.to_datetime(df['lifelog_date'])

    # 밤 시간대 필터 (21시~23시 or 0~3시)
    df['hour'] = df['timestamp'].dt.hour
    df = df[(df['hour'] >= 21) | (df['hour'] <= 3)].copy()

    # 자정 이후는 전날 night로 처리
    df.loc[df['hour'] <= 3, 'lifelog_date'] -= pd.Timedelta(days=1)

    # 낮은 조도 조건
    df = df[df['m_light'] <= light_threshold]

    # 각 (subject_id, lifelog_date)별 불 끈 시각 추출
    lights_off_df = (
        df.groupby(['subject_id', 'lifelog_date'])['timestamp']
        .min()
        .reset_index(name='lights_off_time')
    )

    # 실수형 시각으로 변환
    lights_off_df['lights_off_time'] = lights_off_df['lights_off_time'].dt.time.apply(time_to_float)

    return lights_off_df

In [ ]:
mLight23 = estimate_lights_off_time(mLight)
mLight23['lights_off_time'] = np.where(mLight23['lights_off_time']<10,mLight23['lights_off_time']+24,mLight23['lights_off_time'])
mLight23.head()

  subject_id lifelog_date  lights_off_time
0       id01   2024-06-26          21.0500
1       id01   2024-06-27          21.1500
2       id01   2024-06-28          23.1500
3       id01   2024-06-29          21.9833
4       id01   2024-06-30          21.1500

### 📌 mScreenStatus 화면 사용여부

- Indicates whether the smartphone screen is in use.
 - 기상시간, 취침시간, 수면시간
 - 휴대폰 이용횟수, 이용시간
 - 00 - 05 사이에 휴대폰 이용한 건수
 - 결측치 처리 x

In [ ]:
mScreenStatus = pd.read_parquet(path+'ch2025_mScreenStatus.parquet')

mScreenStatus['lifelog_date'] = mScreenStatus['timestamp'].astype(str).str[:10]
# mScreenStatus = fill_missing_dates_by_subject(mScreenStatus)
mScreenStatus.head(1)

  subject_id           timestamp  m_screen_use lifelog_date
0       id01 2024-06-26 12:03:00             0   2024-06-26

In [ ]:
def preprocess_mScreenStatus(df):
    from datetime import datetime, time as dtime, timedelta

    df = df.copy()
    df['timestamp'] = pd.to_datetime(df['timestamp'])
    df['lifelog_date'] = pd.to_datetime(df['lifelog_date'])

    # base key 확보
    base_keys = df[['subject_id', 'lifelog_date']].drop_duplicates()
    base_keys['lifelog_date'] = base_keys['lifelog_date'].dt.date

    # 밤 9시부터 다음날 오전 11시 필터링
    df['hour'] = df['timestamp'].dt.hour
    df = df[(df['hour'] >= 21) | (df['hour'] < 11)].copy()
    df.loc[df['hour'] < 11, 'lifelog_date'] -= pd.Timedelta(days=1)

    df.sort_values(['subject_id', 'timestamp'], inplace=True)

    results = []

    for (subject_id, lifelog_date), group in df.groupby(['subject_id', 'lifelog_date']):
        group = group.sort_values('timestamp').reset_index(drop=True)

        # 1. 중간 각성(앞뒤 0, 본인 1) 제거
        prev = group['m_screen_use'].shift(1)
        next_ = group['m_screen_use'].shift(-1)
        mask = (group['m_screen_use'] == 1) & (prev == 0) & (next_ == 0)
        group.loc[mask, 'm_screen_use'] = 0

        # 2. 블록 단위로 짧은 각성 블록 제거
        group['is_sleep'] = group['m_screen_use'] == 0
        group['block'] = (group['is_sleep'] != group['is_sleep'].shift()).cumsum()
        block_info = group.groupby('block').agg(
            is_sleep=('is_sleep', 'first'),
            size=('is_sleep', 'size')
        )

        for i in range(1, len(block_info) - 1):
            if (
                block_info.iloc[i]['is_sleep'] == False and
                block_info.iloc[i]['size'] <= 2 and
                block_info.iloc[i - 1]['is_sleep'] and
                block_info.iloc[i + 1]['is_sleep']
            ):
                group.loc[group['block'] == block_info.index[i], 'm_screen_use'] = 0

        # 다시 블록 재계산 후 수면 추정
        group['is_sleep'] = group['m_screen_use'] == 0
        group['block'] = (group['is_sleep'] != group['is_sleep'].shift()).cumsum()
        sleep_blocks = group[group['is_sleep']].groupby('block').agg(
            sleep_start=('timestamp', 'first'),
            sleep_end=('timestamp', 'last'),
            duration_min=('timestamp', lambda x: (x.max() - x.min()).total_seconds() / 60)
        )

        sleep_time = wake_time = duration_min = None
        if not sleep_blocks.empty:
            longest_sleep = sleep_blocks.loc[sleep_blocks['duration_min'].idxmax()]
            sleep_time = longest_sleep['sleep_start'].time()
            wake_time = longest_sleep['sleep_end'].time()
            duration_min = (
                datetime.combine(datetime.today(), wake_time) - datetime.combine(datetime.today(), sleep_time)
            ).total_seconds() / 60
            if duration_min < 0:
                duration_min += 1440

            if not (4 <= wake_time.hour < 11):
                wake_time = None
            if not (sleep_time.hour >= 21 or sleep_time.hour < 3):
                sleep_time = None
            if duration_min < 100:
                sleep_time = None
                wake_time = None
                duration_min = None

        results.append({
            'subject_id': subject_id,
            'lifelog_date': lifelog_date.date(),
            'sleep_time': sleep_time,
            'wake_time': wake_time,
            'sleep_duration_min': round(duration_min, 1) if duration_min is not None else None
        })


    sleep_df = pd.DataFrame(results)
    result_df = base_keys.merge(sleep_df, on=['subject_id', 'lifelog_date'], how='left')

    # 시간 → 실수형 숫자 (예: 23:30 → 23.5)
    def time_to_float(t):
        if pd.isna(t):
            return None
        return round(t.hour + t.minute / 60 + t.second / 3600, 4)

    result_df['sleep_time'] = result_df['sleep_time'].apply(time_to_float)
    result_df['wake_time'] = result_df['wake_time'].apply(time_to_float)

    return result_df

In [ ]:
def preprocess_mScreenStatus(df):
    from datetime import datetime, timedelta

    df = df.copy()
    df['timestamp'] = pd.to_datetime(df['timestamp'])
    df['lifelog_date'] = pd.to_datetime(df['lifelog_date'])

    base_keys = df[['subject_id', 'lifelog_date']].drop_duplicates()
    base_keys['lifelog_date'] = base_keys['lifelog_date'].dt.date

    # 밤 9시 ~ 다음날 오전 11시 필터링
    df['hour'] = df['timestamp'].dt.hour
    df = df[(df['hour'] >= 21) | (df['hour'] < 11)].copy()
    df.loc[df['hour'] < 11, 'lifelog_date'] -= pd.Timedelta(days=1)
    df.sort_values(['subject_id', 'timestamp'], inplace=True)

    results = []

    for (subject_id, lifelog_date), group in df.groupby(['subject_id', 'lifelog_date']):
        group = group.sort_values('timestamp').reset_index(drop=True)

        # 중간 각성 제거
        prev = group['m_screen_use'].shift(1)
        next_ = group['m_screen_use'].shift(-1)
        mask = (group['m_screen_use'] == 1) & (prev == 0) & (next_ == 0)
        group.loc[mask, 'm_screen_use'] = 0

        # 짧은 각성 블록 제거
        group['is_sleep'] = group['m_screen_use'] == 0
        group['block'] = (group['is_sleep'] != group['is_sleep'].shift()).cumsum()
        block_info = group.groupby('block').agg(
            is_sleep=('is_sleep', 'first'),
            size=('is_sleep', 'size')
        )

        for i in range(1, len(block_info) - 1):
            if (
                block_info.iloc[i]['is_sleep'] == False and
                block_info.iloc[i]['size'] <= 2 and
                block_info.iloc[i - 1]['is_sleep'] and
                block_info.iloc[i + 1]['is_sleep']
            ):
                group.loc[group['block'] == block_info.index[i], 'm_screen_use'] = 0

        # 블록 재계산
        group['is_sleep'] = group['m_screen_use'] == 0
        group['block'] = (group['is_sleep'] != group['is_sleep'].shift()).cumsum()

        sleep_blocks = group[group['is_sleep']].groupby('block').agg(
            sleep_start=('timestamp', 'first'),
            sleep_end=('timestamp', 'last'),
            duration_min=('timestamp', lambda x: (x.max() - x.min()).total_seconds() / 60)
        )

        sleep_time = wake_time = duration_min = None
        if not sleep_blocks.empty:
            longest_sleep = sleep_blocks.loc[sleep_blocks['duration_min'].idxmax()]
            sleep_time = longest_sleep['sleep_start'].time()
            wake_time = longest_sleep['sleep_end'].time()
            duration_min = longest_sleep['duration_min']  # ✅ 정확하게 자정 넘는 경우도 반영됨

            # 유효 시간 범위 조건
            if not (4 <= wake_time.hour < 11):
                wake_time = None
            if not (sleep_time.hour >= 21 or sleep_time.hour < 3):
                sleep_time = None
            if duration_min < 100:
                sleep_time = None
                wake_time = None
                duration_min = None

        results.append({
            'subject_id': subject_id,
            'lifelog_date': lifelog_date.date(),
            'sleep_time': sleep_time,
            'wake_time': wake_time,
            'sleep_duration_min': round(duration_min, 1) if duration_min is not None else None
        })

    sleep_df = pd.DataFrame(results)
    result_df = base_keys.merge(sleep_df, on=['subject_id', 'lifelog_date'], how='left')

    # 시간 → 실수형 숫자 변환
    def time_to_float(t):
        if pd.isna(t):
            return None
        return round(t.hour + t.minute / 60 + t.second / 3600, 4)

    result_df['sleep_time'] = result_df['sleep_time'].apply(time_to_float)
    result_df['wake_time'] = result_df['wake_time'].apply(time_to_float)

    return result_df

In [ ]:
def add_ratios(df):
    df = df.copy()
    df['lifelog_date'] = pd.to_datetime(df['lifelog_date'])
    df['weekday'] = df['lifelog_date'].dt.weekday  # 0=월 ~ 6=일
    df['week_type'] = df['weekday'].apply(lambda x: 'weekend' if x in [4,5] else 'weekday') # 금,토
    df['month'] = df['lifelog_date'].dt.month

    # 평균 계산
    avg_duration = df.groupby(['subject_id', 'month', 'week_type'])['sleep_duration_min'].mean().reset_index(name='avg_sleep_duration')
    sleep_time_avg = df.groupby(['subject_id', 'month', 'week_type'])['sleep_time'].apply(calculate_circular_mean_sleep_time).reset_index(name='avg_sleep_time')
    wake_time_avg = df.groupby(['subject_id', 'month', 'week_type'])['wake_time'].apply(calculate_circular_mean_sleep_time).reset_index(name='avg_wake_time')
    avg_df = sleep_time_avg.merge(wake_time_avg, on=['subject_id', 'month', 'week_type']).merge(avg_duration, on=['subject_id', 'month', 'week_type'])
    df = df.merge(avg_df, on=['subject_id', 'month', 'week_type'], how='left')

    # 비율 변수
    df['sleep_time_diff'] = df['avg_sleep_time'] - df['sleep_time']
    df['wake_time_diff'] = df['avg_wake_time'] - df['wake_time']
    df['sleep_duration_diff'] = df['avg_sleep_duration'] - df['sleep_duration_min']
    df['sleep_time_ratio'] = df['sleep_time'] / df['avg_sleep_time']
    df['wake_time_ratio'] = df['wake_time'] / df['avg_wake_time']
    df['sleep_duration_ratio'] = df['sleep_duration_min'] / df['avg_sleep_duration']

    # 정렬 및 lag/변화량
    df = df.sort_values(['subject_id', 'lifelog_date'])

    # 시차 변수
    for lag in [1, 2]:
        df[f'sleep_time_lag{lag}'] = df.groupby('subject_id')['sleep_time'].shift(lag)
        df[f'wake_time_lag{lag}'] = df.groupby('subject_id')['wake_time'].shift(lag)
        df[f'sleep_duration_lag{lag}'] = df.groupby('subject_id')['sleep_duration_min'].shift(lag)

        df[f'sleep_time_diff_lag{lag}'] = df.groupby('subject_id')['sleep_time_diff'].shift(lag)
        df[f'wake_time_diff_lag{lag}'] = df.groupby('subject_id')['wake_time_diff'].shift(lag)
        df[f'sleep_duration_diff_lag{lag}'] = df.groupby('subject_id')['sleep_duration_diff'].shift(lag)

        df[f'sleep_time_ratio_lag{lag}'] = df.groupby('subject_id')['sleep_time_ratio'].shift(lag)
        df[f'wake_time_ratio_lag{lag}'] = df.groupby('subject_id')['wake_time_ratio'].shift(lag)
        df[f'sleep_duration_ratio_lag{lag}'] = df.groupby('subject_id')['sleep_duration_ratio'].shift(lag)

    # 이동 평균
    for window in [2,3,5,7]:
        df[f'sleep_time_mean{window}d'] = df.groupby('subject_id')['sleep_time'].rolling(window=window, min_periods=1).mean().reset_index(level=0, drop=True)
        df[f'wake_time_mean{window}d'] = df.groupby('subject_id')['wake_time'].rolling(window=window, min_periods=1).mean().reset_index(level=0, drop=True)
        df[f'sleep_duration_min_mean{window}d'] = df.groupby('subject_id')['sleep_duration_min'].rolling(window=window, min_periods=1).mean().reset_index(level=0, drop=True)

        df[f'sleep_time_diff_mean{window}d'] = df.groupby('subject_id')['sleep_time_diff'].rolling(window=window, min_periods=1).mean().reset_index(level=0, drop=True)
        df[f'wake_time_diff_mean{window}d'] = df.groupby('subject_id')['wake_time_diff'].rolling(window=window, min_periods=1).mean().reset_index(level=0, drop=True)
        df[f'sleep_duration_diff_mean{window}d'] = df.groupby('subject_id')['sleep_duration_diff'].rolling(window=window, min_periods=1).mean().reset_index(level=0, drop=True)

        df[f'sleep_time_ratio_mean{window}d'] = df.groupby('subject_id')['sleep_time_ratio'].rolling(window=window, min_periods=1).mean().reset_index(level=0, drop=True)
        df[f'wake_time_ratio_mean{window}d'] = df.groupby('subject_id')['wake_time_ratio'].rolling(window=window, min_periods=1).mean().reset_index(level=0, drop=True)
        df[f'sleep_duration_ratio_mean{window}d'] = df.groupby('subject_id')['sleep_duration_ratio'].rolling(window=window, min_periods=1).mean().reset_index(level=0, drop=True)

        # ----

        df[f'sleep_time_std{window}d'] = df.groupby('subject_id')['sleep_time'].rolling(window=window, min_periods=1).std().reset_index(level=0, drop=True)
        df[f'wake_time_std{window}d'] = df.groupby('subject_id')['wake_time'].rolling(window=window, min_periods=1).std().reset_index(level=0, drop=True)
        df[f'sleep_duration_min_std{window}d'] = df.groupby('subject_id')['sleep_duration_min'].rolling(window=window, min_periods=1).std().reset_index(level=0, drop=True)

        df[f'sleep_time_diff_std{window}d'] = df.groupby('subject_id')['sleep_time_diff'].rolling(window=window, min_periods=1).std().reset_index(level=0, drop=True)
        df[f'wake_time_diff_std{window}d'] = df.groupby('subject_id')['wake_time_diff'].rolling(window=window, min_periods=1).std().reset_index(level=0, drop=True)
        df[f'sleep_duration_diff_std{window}d'] = df.groupby('subject_id')['sleep_duration_diff'].rolling(window=window, min_periods=1).std().reset_index(level=0, drop=True)

        df[f'sleep_time_ratio_std{window}d'] = df.groupby('subject_id')['sleep_time_ratio'].rolling(window=window, min_periods=1).std().reset_index(level=0, drop=True)
        df[f'wake_time_ratio_std{window}d'] = df.groupby('subject_id')['wake_time_ratio'].rolling(window=window, min_periods=1).std().reset_index(level=0, drop=True)
        df[f'sleep_duration_ratio_std{window}d'] = df.groupby('subject_id')['sleep_duration_ratio'].rolling(window=window, min_periods=1).std().reset_index(level=0, drop=True)

    # 요일별 평균 수면 비교
    weekday_avg = df.groupby(['subject_id', 'weekday'])['sleep_duration_min'].mean().reset_index(name='weekday_avg_sleep')
    df = df.merge(weekday_avg, on=['subject_id', 'weekday'], how='left')
    df['sleep_duration_weekday_avg_diff'] = df['sleep_duration_min'] - df['weekday_avg_sleep']
    df['sleep_duration_weekday_avg_div'] = df['sleep_duration_min'] / df['weekday_avg_sleep']

    return df

In [ ]:
mScreenStatus2 = preprocess_mScreenStatus(mScreenStatus)
print(mScreenStatus2.shape)

mScreenStatus2 = fill_missing_dates_by_subject(mScreenStatus2)
print(mScreenStatus2.shape)

weekday_map = {
    0: '월요일', 1: '화요일', 2: '수요일', 3: '목요일',
    4: '금요일', 5: '토요일', 6: '일요일'
}
mScreenStatus2['weekday'] = mScreenStatus2['lifelog_date'].dt.dayofweek.map(weekday_map)
mScreenStatus2['month'] = mScreenStatus2['lifelog_date'].dt.month

mScreenStatus2['lifelog_date'] = mScreenStatus2['lifelog_date'].astype(str)
train['lifelog_date'] = train['lifelog_date'].astype(str)

mScreenStatus2 = mScreenStatus2.merge(train[['subject_id','lifelog_date','Q1','Q2','Q3','S1','S2','S3']],on=['subject_id','lifelog_date'],how='left')
print(mScreenStatus2.shape)

a1_map = {
    'sleep_duration_min':'수면시간(분)',
    'sleep_time':'취침시간',
    'wake_time':'기상시간',
    'Q1':'Q1(기상직후 수면의질)',
    'Q2':'Q2(취침직전 신체적피로)',
    'Q3':'Q3(취침직전 스트레스)',
    'S1':'S1(기상직후 수면시간)',
    'S2':'S2(기상직후 수면효율)',
    'S3':'S3(기상직후 수면지연시간)',
}

mScreenStatus2 = mScreenStatus2.rename(columns=a1_map)
mScreenStatus2.head()

(700, 5)
(853, 5)
(853, 13)

,lifelog_date,subject_id,취침시간,기상시간,수면시간(분),weekday,month,Q1(기상직후 수면의질),Q2(취침직전 신체적피로),Q3(취침직전 스트레스),S1(기상직후 수면시간),S2(기상직후 수면효율),S3(기상직후 수면지연시간)
0,2024-06-26,id01,23.4500,5.2500,348.0000,수요일,6,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000
1,2024-06-27,id01,23.1333,5.3000,370.0000,목요일,6,0.0000,0.0000,0.0000,0.0000,1.0000,1.0000
2,2024-06-28,id01,23.0000,5.9167,415.0000,금요일,6,1.0000,0.0000,0.0000,1.0000,1.0000,1.0000
3,2024-06-29,id01,21.8000,5.9167,487.0000,토요일,6,1.0000,0.0000,1.0000,2.0000,0.0000,0.0000
4,2024-06-30,id01,22.7000,5.1833,389.0000,일요일,6,0.0000,1.0000,1.0000,1.0000,1.0000,1.0000

In [ ]:
%%time

# CPU times: user 40.4 s, sys: 7.17 s, total: 47.6 s
# Wall time: 59min 11s

"""
- mACStatus: Indicates whether the smartphone is currently being charged.
- mActivity: Value calculated by the Google Activity Recognition API.
- mAmbience: Ambient sound identification labels and their respective probabilities.
- mBle: Bluetooth devices around individual subject.
- mGps: Multiple GPS coordinates measured within a single minute using the smartphone.
- mLight: Ambient light measured by the smartphone.
- (✔️) mScreenStatus: Indicates whether the smartphone screen is in use.
- mUsageStats: Indicates which apps were used on the smartphone and for how long.
- mWifi: Wifi devices around individual subject.
- wHr: Heart rate readings recorded by the smartwatch.
- wLight: Ambient light measured by the smartwatch.
- wPedo: Step data recorded by the smartwatch.
"""

system_message = f"""
# 🔈지침: 당신은 데이터 분석 전문가입니다.
- 모델 설명 : For the purpose of training a learning model to predict sleep health, fatigue, and stress, the following six metrics were derived from sleep sensor data and self-reported survey records.
- [데이터]에는 [취침시간], [기상시간] 결측치가 존재합니다. 이를 채워야 합니다.
- [취침시간]과 [기상시간]은 **24시간제를 기준으로 한 '소수 시간(decimal hour)' 형식**입니다.
    예) 23.50 → 23시 30분, 0.75 → 0시 45분, 1.0 → 1시 0분

# 🔍 평균값 설명
- 평균 취침시간/기상시간은 `21.0~2.0` 또는 `3.0~11.0` 범위에서 나타나며, 이는 **다음날로 넘어가는 원형 시간 범위입니다**.
    예) 1.4776은 1시 28분을 의미하며, 이는 24시를 넘어선 것이 아니라 **자정 이후 정상적인 시간대**입니다.

# 🔈결측치 보완 규칙
- 평균 취침시간/기상시간은 이미 올바른 포맷이며, 21.0~2.0(취침), 3.0~11.0(기상) 범위 내의 값입니다. **충분히 허용 가능한 값입니다. 혼란을 느끼지 말고 그대로 활용하세요.**
- 평균값이 0보다 작은 경우는 없으며, 1.4와 같은 값은 1시 24분을 의미합니다.

# 🔈금지 사항
- 데이터 형식이나 범위를 의심하거나, 평균값이 허용 범위를 벗어난다고 가정하지 마세요.
- 반복적으로 시간 포맷을 재해석하거나 '이 값이 잘못된 것 같다'는 내적 판단을 하지 마세요.

# 🔈주의사항 (중요!!)
- [취침시간] 결측값 추정 시, 21.0 ~ 2.0 범위 내의 값을 사용해야 합니다.
- [기상시간] 결측값 추정 시, 3.0 ~ 11.0 범위 내의 값을 사용해야 합니다.
- [취침시간], [기상시간] 결측값을 추정할 때 다양한 정보를 종합적으로 고려해야 합니다.
  → 다양한 정보: 전일 학습데이터, 통계데이터, Q1~S1 정보, 주말 유무(금요일 포함), 7~8월 유무 등
- [취침시간], [기상시간]의 **기존 값이 존재하는 경우 절대로 수정하지 마세요.**
- 기존값이 있는 경우에는 **해당 셀을 그대로 유지**하며, **빈칸(null)**인 경우에만 보완합니다.
- 입력으로 주어진 테이블의 다른 값들도 절대 수정하지 마세요. **오직 결측치만 채워야 합니다.**
- 누락된 셀은 반드시 채워야 하며, **빈 셀 없이 모든 셀을 채워진 상태로 출력**해야 합니다.
- 출력은 항상 **모든 셀에 값이 채워진 상태**여야 합니다. **빈칸을 남기지 마세요.**

### 🔈답변 작성 양식
- 답변에 지침내용을 포함하지 않습니다.
- 결측치만 채우고 기존값이 존재하는을 그대로 사용합니다.
"""

# ================================================================
# 설정값
save_path = '/content/drive/MyDrive/data/ch2025_data_items/fillna'
dataname  = 'mScreenStatus'
version   = '20250607_v4'
data      = mScreenStatus2.copy()
# ================================================================

# run
parsed_results = []
for subject_id in tqdm(data['subject_id'].unique(), desc="Processing each subject"):
# for subject_id in tqdm(['id06'], desc="Processing each subject"):

    print(f'# subject_id:{subject_id}')

    sub1 = data[data['subject_id'] == subject_id]
    sub1 = sub1.drop(columns=['수면시간(분)'])
    학습데이터 = sub1.to_csv(index=False, sep="\t")

    # ----------------------------------------------------------------------------------------------
    # 통계데이터
    a1 = data[data['subject_id'] == subject_id].groupby(['weekday']).apply(lambda x:pd.Series({
    '평균취침시간': calculate_circular_mean_sleep_time(x['취침시간'])
    ,'평균기상시간': calculate_circular_mean_sleep_time(x['기상시간'])
    })).reset_index()

    a2 = data[data['subject_id'] == subject_id].groupby(['month','weekday']).apply(lambda x:pd.Series({
    '평균취침시간': calculate_circular_mean_sleep_time(x['취침시간'])
    ,'평균기상시간': calculate_circular_mean_sleep_time(x['기상시간'])
    })).reset_index()

    # a1을 weekday 기준으로 merge
    a2_filled = a2.merge(
        a1,
        on='weekday',
        suffixes=('', '_a1'),
        how='left'
    )

    # 결측값이 있는 경우 a1 값으로 대체
    a2_filled['평균취침시간'] = a2_filled['평균취침시간'].fillna(a2_filled['평균취침시간_a1'])
    a2_filled['평균기상시간'] = a2_filled['평균기상시간'].fillna(a2_filled['평균기상시간_a1'])

    # 보조 컬럼 제거
    sub2 = a2_filled.drop(columns=['평균취침시간_a1', '평균기상시간_a1'])
    통계데이터 = sub2.to_csv(index=False, sep="\t")
    # ----------------------------------------------------------------------------------------------

    user_message = f"""
    # 🔈작업 순서
    1. 결측치 [취침시간]을 추정하시오.
    2. 결측치 [기상시간]을 추정하시오 (추가지침: 전 단계에서 생성 된 [취침시간]을 참고해서 [기상시간] 결측값을 추정하시오.)

    # 🔈 xdata 설명
    - mScreenStatus(Indicates whether the smartphone screen is in use)기반으로 파생된 추정 [취침시간], [기상시간]
    - [취침시간]과 [기상시간]은 소수점으로 표현된 24시간제 시간입니다. (예: 22.6500 → 22시 39분)

    # 🔈 ydata 설명 (예측타겟)
    - Q1: 기상 직후 수면의 질 (0: 평균 이하, 1: 평균 이상)
    - Q2: 취침 직전 신체 피로 수준 (0: 높은 피로, 1: 낮은 피로)
    - Q3: 취침 직전 스트레스 수준 (0: 높은 스트레스, 1: 낮은 스트레스)
    - S1: 수면시간 가이드라인 준수여부 (0: 미준수, 1: 부분 준수, 2: 완전 준수)
    - S2: 수면 효율 가이드라인 준수여부 (0: 미준수, 1: 준수)
    - S3: 수면 잠들기 지연시간 가이드라인 준수여부 (0: 미준수, 1: 준수)

    # 🔈도메인 지식
    - S1(수면시간)이 2(완전준수)인 경우 -> 기상기상이 평소보다 늦어서 수면시간이 충분한 경우
    - 금요일, 토요일에는 다음날이 휴일이기 때문에 기상시간을 평소보다 늦게 설정
    - 7월, 8월에는 무더위(여름철 고온 시기)에는 기상시간이 일반적으로 더 빨라지는 경향 존재
    - 전일 상태가 오늘 상태에 영향을 줄 수 있음 (전일 몸이 좋지 않으면 다음날도 몸이 좋지 않는 것과 동일한 원리)

    # 🔈통계데이터
    {통계데이터}

    # 🔈데이터
    {학습데이터}

    # 🔈답변 출력 형식
    lifelog_date\tsubject_id\t취침시간\t기상시간\n
    2024-06-26\tid01\t23.4500\t5.2500\n
    2024-06-27\tid01\t23.1333\t5.3000\n
    2024-06-28\tid01\t23.0000\t5.9167\n

    # 답변:
    """

    # 최대 3회 시도
    for attempt in range(3):
        try:
            # 질의
            messages = [
                {"role": "system", "content": system_message},
                {"role": "user", "content": user_message}
            ]

            sampling_params = SamplingParams(max_tokens=37000, temperature=0, seed=42)
            outputs = llm.chat(messages, sampling_params=sampling_params)

            # 텍스트 추출 및 저장
            result_text = outputs[0].outputs[0].text
            with open(f"{save_path}/{dataname}_{subject_id}_result_try{attempt+1}.txt", "w", encoding="utf-8") as f:
                f.write(result_text)

            # <think> 제거
            cleaned_text = re.sub(r"<think>.*?</think>", "", result_text, flags=re.DOTALL).strip()

            # 파싱
            df_parsed = pd.read_csv(StringIO(cleaned_text), sep="\t")

            # 결측이 많을 경우 재시도
            # 1. 결측값이 10개 넘거나
            # 2. 생성한 개수가 제공한 샘플보다 10개 이상 적을때
            if (df_parsed['기상시간'].isna().sum() > 10) | ((len(sub1)-len(df_parsed)) > 10):
                print(f"[RETRY] 결측치 많음 → subject_id: {subject_id} (attempt {attempt+1})")
                continue

            parsed_results.append(df_parsed)
            break  # 성공하면 반복 종료

        except Exception as e:
            print(f"[ERROR] Parsing failed for subject {subject_id} (attempt {attempt+1}): {e}")
            if attempt == 1:
                print(f"[FAIL] 최종 실패 → subject_id: {subject_id}")
            time.sleep(2)  # 재시도 전에 대기

# 모든 subject 결과 병합
data_filled_na = pd.concat(parsed_results, ignore_index=True)
data_filled_na = data_filled_na.rename(columns={'취침시간':'취침시간_llm','기상시간':'기상시간_llm'})
data_filled_na.to_excel(f'{save_path}/{dataname}_llm_{version}.xlsx',index=False)

# 비교검증데이터 저장
data_filled_na['lifelog_date'] = data_filled_na['lifelog_date'].astype(str)
data['lifelog_date'] = data['lifelog_date'].astype(str)
data_filled_na['subject_id'] = data_filled_na['subject_id'].astype(str)
data['subject_id'] = data['subject_id'].astype(str)
data = data.merge(data_filled_na,on=['lifelog_date','subject_id'],how='left')
data['수면시간_llm'] = data.apply(lambda x: calculate_sleep_duration_min(x['취침시간_llm'],x['기상시간_llm']),axis=1)
data.to_excel(f'{save_path}/{dataname}_llm_check_{version}.xlsx',index=False)

# check
data.head()

Processing each subject:   0%|          | 0/10 [00:00<?, ?it/s]

# subject_id:id01

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

# subject_id:id02

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

# subject_id:id03

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

# subject_id:id04

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

# subject_id:id05

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

# subject_id:id06

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

[ERROR] Parsing failed for subject id06 (attempt 1): '기상시간'

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

# subject_id:id07

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

[RETRY] 결측치 많음 → subject_id: id07 (attempt 1)

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

# subject_id:id08

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

# subject_id:id09

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

# subject_id:id10

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

CPU times: user 36 s, sys: 7.13 s, total: 43.1 s
Wall time: 53min 2s

,lifelog_date,subject_id,취침시간,기상시간,수면시간(분),weekday,month,Q1(기상직후 수면의질),Q2(취침직전 신체적피로),Q3(취침직전 스트레스),S1(기상직후 수면시간),S2(기상직후 수면효율),S3(기상직후 수면지연시간),취침시간_llm,기상시간_llm,수면시간_llm
0,2024-06-26,id01,23.4500,5.2500,348.0000,수요일,6,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,23.4500,5.2500,348.0000
1,2024-06-27,id01,23.1333,5.3000,370.0000,목요일,6,0.0000,0.0000,0.0000,0.0000,1.0000,1.0000,23.1333,5.3000,370.0000
2,2024-06-28,id01,23.0000,5.9167,415.0000,금요일,6,1.0000,0.0000,0.0000,1.0000,1.0000,1.0000,23.0000,5.9167,415.0000
3,2024-06-29,id01,21.8000,5.9167,487.0000,토요일,6,1.0000,0.0000,1.0000,2.0000,0.0000,0.0000,21.8000,5.9167,487.0000
4,2024-06-30,id01,22.7000,5.1833,389.0000,일요일,6,0.0000,1.0000,1.0000,1.0000,1.0000,1.0000,22.7000,5.1833,389.0000

In [ ]:
def add_ratios(df):
    df = df.copy()
    df['lifelog_date'] = pd.to_datetime(df['lifelog_date'])
    df['weekday'] = df['lifelog_date'].dt.weekday  # 0=월 ~ 6=일
    df['week_type'] = df['weekday'].apply(lambda x: 'weekend' if x in [4,5] else 'weekday') # 금,토
    df['month'] = df['lifelog_date'].dt.month

    # 평균 계산
    avg_duration = df.groupby(['subject_id', 'month', 'week_type'])['sleep_duration_min'].mean().reset_index(name='avg_sleep_duration')
    sleep_time_avg = df.groupby(['subject_id', 'month', 'week_type'])['sleep_time'].apply(calculate_circular_mean_sleep_time).reset_index(name='avg_sleep_time')
    wake_time_avg = df.groupby(['subject_id', 'month', 'week_type'])['wake_time'].apply(calculate_circular_mean_sleep_time).reset_index(name='avg_wake_time')
    avg_df = sleep_time_avg.merge(wake_time_avg, on=['subject_id', 'month', 'week_type']).merge(avg_duration, on=['subject_id', 'month', 'week_type'])
    df = df.merge(avg_df, on=['subject_id', 'month', 'week_type'], how='left')

    # 비율 변수
    df['sleep_time_diff'] = df['avg_sleep_time'] - df['sleep_time']
    df['wake_time_diff'] = df['avg_wake_time'] - df['wake_time']
    df['sleep_duration_diff'] = df['avg_sleep_duration'] - df['sleep_duration_min']
    df['sleep_time_ratio'] = df['sleep_time'] / df['avg_sleep_time']
    df['wake_time_ratio'] = df['wake_time'] / df['avg_wake_time']
    df['sleep_duration_ratio'] = df['sleep_duration_min'] / df['avg_sleep_duration']

    # 정렬 및 lag/변화량
    df = df.sort_values(['subject_id', 'lifelog_date'])

    # 시차 변수
    for lag in [1, 2]:
        df[f'sleep_time_lag{lag}'] = df.groupby('subject_id')['sleep_time'].shift(lag)
        df[f'wake_time_lag{lag}'] = df.groupby('subject_id')['wake_time'].shift(lag)
        df[f'sleep_duration_lag{lag}'] = df.groupby('subject_id')['sleep_duration_min'].shift(lag)

        df[f'sleep_time_diff_lag{lag}'] = df.groupby('subject_id')['sleep_time_diff'].shift(lag)
        df[f'wake_time_diff_lag{lag}'] = df.groupby('subject_id')['wake_time_diff'].shift(lag)
        df[f'sleep_duration_diff_lag{lag}'] = df.groupby('subject_id')['sleep_duration_diff'].shift(lag)

        df[f'sleep_time_ratio_lag{lag}'] = df.groupby('subject_id')['sleep_time_ratio'].shift(lag)
        df[f'wake_time_ratio_lag{lag}'] = df.groupby('subject_id')['wake_time_ratio'].shift(lag)
        df[f'sleep_duration_ratio_lag{lag}'] = df.groupby('subject_id')['sleep_duration_ratio'].shift(lag)

    # 이동 평균
    for window in [2,3,5,7]:
        df[f'sleep_time_mean{window}d'] = df.groupby('subject_id')['sleep_time'].rolling(window=window, min_periods=1).mean().reset_index(level=0, drop=True)
        df[f'wake_time_mean{window}d'] = df.groupby('subject_id')['wake_time'].rolling(window=window, min_periods=1).mean().reset_index(level=0, drop=True)
        df[f'sleep_duration_min_mean{window}d'] = df.groupby('subject_id')['sleep_duration_min'].rolling(window=window, min_periods=1).mean().reset_index(level=0, drop=True)

        df[f'sleep_time_diff_mean{window}d'] = df.groupby('subject_id')['sleep_time_diff'].rolling(window=window, min_periods=1).mean().reset_index(level=0, drop=True)
        df[f'wake_time_diff_mean{window}d'] = df.groupby('subject_id')['wake_time_diff'].rolling(window=window, min_periods=1).mean().reset_index(level=0, drop=True)
        df[f'sleep_duration_diff_mean{window}d'] = df.groupby('subject_id')['sleep_duration_diff'].rolling(window=window, min_periods=1).mean().reset_index(level=0, drop=True)

        df[f'sleep_time_ratio_mean{window}d'] = df.groupby('subject_id')['sleep_time_ratio'].rolling(window=window, min_periods=1).mean().reset_index(level=0, drop=True)
        df[f'wake_time_ratio_mean{window}d'] = df.groupby('subject_id')['wake_time_ratio'].rolling(window=window, min_periods=1).mean().reset_index(level=0, drop=True)
        df[f'sleep_duration_ratio_mean{window}d'] = df.groupby('subject_id')['sleep_duration_ratio'].rolling(window=window, min_periods=1).mean().reset_index(level=0, drop=True)

        # ----

        df[f'sleep_time_std{window}d'] = df.groupby('subject_id')['sleep_time'].rolling(window=window, min_periods=1).std().reset_index(level=0, drop=True)
        df[f'wake_time_std{window}d'] = df.groupby('subject_id')['wake_time'].rolling(window=window, min_periods=1).std().reset_index(level=0, drop=True)
        df[f'sleep_duration_min_std{window}d'] = df.groupby('subject_id')['sleep_duration_min'].rolling(window=window, min_periods=1).std().reset_index(level=0, drop=True)

        df[f'sleep_time_diff_std{window}d'] = df.groupby('subject_id')['sleep_time_diff'].rolling(window=window, min_periods=1).std().reset_index(level=0, drop=True)
        df[f'wake_time_diff_std{window}d'] = df.groupby('subject_id')['wake_time_diff'].rolling(window=window, min_periods=1).std().reset_index(level=0, drop=True)
        df[f'sleep_duration_diff_std{window}d'] = df.groupby('subject_id')['sleep_duration_diff'].rolling(window=window, min_periods=1).std().reset_index(level=0, drop=True)

        df[f'sleep_time_ratio_std{window}d'] = df.groupby('subject_id')['sleep_time_ratio'].rolling(window=window, min_periods=1).std().reset_index(level=0, drop=True)
        df[f'wake_time_ratio_std{window}d'] = df.groupby('subject_id')['wake_time_ratio'].rolling(window=window, min_periods=1).std().reset_index(level=0, drop=True)
        df[f'sleep_duration_ratio_std{window}d'] = df.groupby('subject_id')['sleep_duration_ratio'].rolling(window=window, min_periods=1).std().reset_index(level=0, drop=True)

    # 요일별 평균 수면 비교
    weekday_avg = df.groupby(['subject_id', 'weekday'])['sleep_duration_min'].mean().reset_index(name='weekday_avg_sleep')
    df = df.merge(weekday_avg, on=['subject_id', 'weekday'], how='left')
    df['sleep_duration_weekday_avg_diff'] = df['sleep_duration_min'] - df['weekday_avg_sleep']
    df['sleep_duration_weekday_avg_div'] = df['sleep_duration_min'] / df['weekday_avg_sleep']

    return df

In [ ]:
# 전처리

mScreenStatus2_llm = pd.read_excel('/content/drive/MyDrive/data/ch2025_data_items/share/hjy/mScreenStatus_llm_20250607_v4.xlsx')
mScreenStatus2_llm.head()

mScreenStatus2_llm['pk'] = mScreenStatus2_llm['subject_id']+mScreenStatus2_llm['lifelog_date']
mScreenStatus2_llm = mScreenStatus2_llm.set_index('pk')

mScreenStatus2 = preprocess_mScreenStatus(mScreenStatus)

# 취침시간, 기상시간 교체

mScreenStatus2['lifelog_date'] = mScreenStatus2['lifelog_date'].astype(str)
mScreenStatus2['pk'] = mScreenStatus2['subject_id']+mScreenStatus2['lifelog_date']

a1_map = mScreenStatus2_llm['취침시간_llm'].to_dict()
mScreenStatus2['sleep_time'] = np.where(mScreenStatus2['sleep_time'].isna(),mScreenStatus2['pk'].map(a1_map),mScreenStatus2['sleep_time'])

a1_map = mScreenStatus2_llm['기상시간_llm'].to_dict()
mScreenStatus2['wake_time'] = np.where(mScreenStatus2['wake_time'].isna(),mScreenStatus2['pk'].map(a1_map),mScreenStatus2['wake_time'])

mScreenStatus2 = mScreenStatus2.drop(columns='pk')

# 수면시간 재계산
mScreenStatus2['sleep_time'] = np.where(mScreenStatus2['sleep_time']<10,mScreenStatus2['sleep_time']+24,mScreenStatus2['sleep_time'])         ### 수정
mScreenStatus2['sleep_duration_min'] = mScreenStatus2.apply(lambda x: calculate_sleep_duration_min(x['sleep_time'],x['wake_time']),axis=1)

# 비율 변수 추가

mScreenStatus2 = add_ratios(mScreenStatus2)

mScreenStatus2 = mScreenStatus2.drop(columns=['weekday','week_type','month'])

# 저장
mScreenStatus2.to_excel('/content/drive/MyDrive/data/ch2025_data_items/share/hjy/mScreenStatus_llm결측값생성후파생변수생성_20250609_v1.xlsx')

# check
print(f'\n # mScreenStatus2 shape: {mScreenStatus2.shape}')
mScreenStatus2.head(1)

 # mScreenStatus2 shape: (700, 107)

,subject_id,lifelog_date,sleep_time,wake_time,sleep_duration_min,avg_sleep_time,avg_wake_time,avg_sleep_duration,sleep_time_diff,wake_time_diff,sleep_duration_diff,sleep_time_ratio,wake_time_ratio,sleep_duration_ratio,sleep_time_lag1,wake_time_lag1,sleep_duration_lag1,sleep_time_diff_lag1,wake_time_diff_lag1,sleep_duration_diff_lag1,sleep_time_ratio_lag1,wake_time_ratio_lag1,sleep_duration_ratio_lag1,sleep_time_lag2,wake_time_lag2,sleep_duration_lag2,sleep_time_diff_lag2,wake_time_diff_lag2,sleep_duration_diff_lag2,sleep_time_ratio_lag2,wake_time_ratio_lag2,sleep_duration_ratio_lag2,sleep_time_mean2d,wake_time_mean2d,sleep_duration_min_mean2d,sleep_time_diff_mean2d,wake_time_diff_mean2d,sleep_duration_diff_mean2d,sleep_time_ratio_mean2d,wake_time_ratio_mean2d,sleep_duration_ratio_mean2d,sleep_time_std2d,wake_time_std2d,sleep_duration_min_std2d,sleep_time_diff_std2d,wake_time_diff_std2d,sleep_duration_diff_std2d,sleep_time_ratio_std2d,wake_time_ratio_std2d,sleep_duration_ratio_std2d,sleep_time_mean3d,wake_time_mean3d,sleep_duration_min_mean3d,sleep_time_diff_mean3d,wake_time_diff_mean3d,sleep_duration_diff_mean3d,sleep_time_ratio_mean3d,wake_time_ratio_mean3d,sleep_duration_ratio_mean3d,sleep_time_std3d,wake_time_std3d,sleep_duration_min_std3d,sleep_time_diff_std3d,wake_time_diff_std3d,sleep_duration_diff_std3d,sleep_time_ratio_std3d,wake_time_ratio_std3d,sleep_duration_ratio_std3d,sleep_time_mean5d,wake_time_mean5d,sleep_duration_min_mean5d,sleep_time_diff_mean5d,wake_time_diff_mean5d,sleep_duration_diff_mean5d,sleep_time_ratio_mean5d,wake_time_ratio_mean5d,sleep_duration_ratio_mean5d,sleep_time_std5d,wake_time_std5d,sleep_duration_min_std5d,sleep_time_diff_std5d,wake_time_diff_std5d,sleep_duration_diff_std5d,sleep_time_ratio_std5d,wake_time_ratio_std5d,sleep_duration_ratio_std5d,sleep_time_mean7d,wake_time_mean7d,sleep_duration_min_mean7d,sleep_time_diff_mean7d,wake_time_diff_mean7d,sleep_duration_diff_mean7d,sleep_time_ratio_mean7d,wake_time_ratio_mean7d,sleep_duration_ratio_mean7d,sleep_time_std7d,wake_time_std7d,sleep_duration_min_std7d,sleep_time_diff_std7d,wake_time_diff_std7d,sleep_duration_diff_std7d,sleep_time_ratio_std7d,wake_time_ratio_std7d,sleep_duration_ratio_std7d,weekday_avg_sleep,sleep_duration_weekday_avg_diff,sleep_duration_weekday_avg_div
0,id01,2024-06-26,23.4500,5.2500,348.0000,23.0945,5.2444,369.0000,-0.3555,-0.0056,21.0000,1.0154,1.0011,0.9431,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.4500,5.2500,348.0000,-0.3555,-0.0056,21.0000,1.0154,1.0011,0.9431,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.4500,5.2500,348.0000,-0.3555,-0.0056,21.0000,1.0154,1.0011,0.9431,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.4500,5.2500,348.0000,-0.3555,-0.0056,21.0000,1.0154,1.0011,0.9431,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.4500,5.2500,348.0000,-0.3555,-0.0056,21.0000,1.0154,1.0011,0.9431,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,406.1000,-58.1000,0.8569

In [ ]:
# 평균수면시간
mScreenStatus2평균수면시간 = mScreenStatus2.groupby(['subject_id','week_type']).apply(lambda x: pd.Series({
     '평균 취침시간':circular_mean_sleep_time(x['sleep_time'])
    ,'평균 기상시간':circular_mean_sleep_time(x['wake_time'])
    ,'평균 수면시간':x['sleep_duration_min'].mean()
})).reset_index()

# 저장
fname = f'{path}mScreenStatus2평균수면시간.xlsx'
print(fname)
mScreenStatus2평균수면시간.to_excel(fname, index=False)

# check
mScreenStatus2평균수면시간.head()

### 📌 mUsageStats 앱사용통계
- mUsageStats: Indicates which apps were used on the smartphone and for how long.

 - 몇시까지 핸드폰 보다가 잠잤는지
 - 통화, 전화 얼마나 했는지
 - YouTube 얼마나 봤는지
 - 메시지, 카카오톡 얼마나 했는지
 - NAVER 얼마나 했는지
 - 평소보다 얼마나 많은 앱을 이용했는지
 - 제외? -> 시스템 UI,One UI 홈

In [ ]:
def extract_mUsageStats_info(row):
    m_data = row['m_usage_stats']
    app_name = [item['app_name'] for item in m_data]
    total_time = [item['total_time'] for item in m_data]
    return pd.Series({'app_name': app_name, 'total_time': total_time})

mUsageStats[['app_name', 'total_time']] = mUsageStats.apply(extract_mUsageStats_info, axis=1)
mUsageStats['lifelog_date'] = mUsageStats['timestamp'].astype(str).str[:10]
# mUsageStats = fill_missing_dates_by_subject(mUsageStats)
mUsageStats.head(1)

,subject_id,timestamp,m_usage_stats,app_name,total_time,lifelog_date
0,id01,2024-06-26 13:00:00,"[{'app_name': ' 캐시워크', 'total_time': 69}, {'app_name': 'NAVER', 'total_time': 549}, {'app_name': ' ✝️성경일독Q', 'total_time': 7337}]","[ 캐시워크, NAVER, ✝️성경일독Q]","[69, 549, 7337]",2024-06-26

In [ ]:
def process_mUsageStats(df):
    df = df.copy()
    df['lifelog_date'] = pd.to_datetime(df['lifelog_date'])
    df['timestamp'] = pd.to_datetime(df['timestamp'])
    df['요일'] = df['lifelog_date'].dt.day_name()
    df['hour'] = df['timestamp'].dt.hour

    # 시간대 분류
    def map_time_period(row):
        if 20 <= row['hour'] <= 23:
            return 'beforebed'
        else:
            return 'activehour'

    df['time_period'] = df.apply(map_time_period, axis=1)

    # 리스트 평탄화
    exploded_df = df.explode(['app_name', 'total_time'])
    exploded_df['total_time'] = exploded_df['total_time'].astype(float)
    exploded_df['total_time'] = exploded_df['total_time'] * 0.001 / 60  # 밀리초 → 초 → 분 변환

    # app_name 특수문자 제거
    exploded_df['app_name'] = exploded_df['app_name'].astype(str).apply(
        lambda x: re.sub(r'[^가-힣a-zA-Z0-9]', '', x)
    )

    # 시스템 앱 제거
    filtered_df = exploded_df[~exploded_df['app_name'].isin(['시스템UI'])]

    # 주요 파생변수 생성
    def calculate_daily_metrics(group):
        app_times = {

            '통화&전화_앱이용시간': group[group['app_name'].isin(['통화','전화'])]['total_time'].sum(),
            '메신저&카카오톡_앱이용시간': group[group['app_name'].isin(['메시지','카카오톡'])]['total_time'].sum(),
            'YouTube_앱이용시간': group[group['app_name'] == 'YouTube']['total_time'].sum(),
            'NAVER_앱이용시간': group[group['app_name'] == 'NAVER']['total_time'].sum(),
            '캐시워크_앱이용시간': group[group['app_name'] == '캐시워크']['total_time'].sum(),
            '성경일독Q_앱이용시간': group[group['app_name'] == '성경일독Q']['total_time'].sum(),
        }

        return pd.Series({
            **app_times,
            '이용앱개수': group['app_name'].nunique(),
            '핸드폰사용시간': group['total_time'].sum()
        })

    # 일자/시간대별 요약
    daily_stats = filtered_df.groupby(['subject_id', 'lifelog_date', 'time_period']).apply(calculate_daily_metrics).reset_index()

    # subject_id별 평균 총화면시간
    avg_screen_time = daily_stats.groupby('subject_id')['핸드폰사용시간'].mean().to_dict()

    # 평균 대비 비율
    def compute_screen_usage(row):
        avg_time = avg_screen_time.get(row['subject_id'], np.nan)
        if pd.isna(avg_time) or avg_time == 0:
            return np.nan
        return round((row['핸드폰사용시간'] / avg_time - 1) * 100, 1)

    daily_stats['평균대비핸드폰사용시간'] = daily_stats.apply(compute_screen_usage, axis=1)

    # 피벗
    daily_stats = daily_stats.pivot(index=['subject_id', 'lifelog_date'], columns='time_period')
    daily_stats.columns = [f"{tp}_{metric}" for metric, tp in daily_stats.columns]
    daily_stats = daily_stats.reset_index()

    feats = [
      'subject_id',
      'lifelog_date',
      'beforebed_통화&전화_앱이용시간',
      'beforebed_메신저&카카오톡_앱이용시간',
      'beforebed_YouTube_앱이용시간',
      'beforebed_NAVER_앱이용시간',
      'beforebed_캐시워크_앱이용시간',
      'beforebed_성경일독Q_앱이용시간',
      'beforebed_이용앱개수',
      'beforebed_핸드폰사용시간',
      'beforebed_평균대비핸드폰사용시간'
    ]

    return daily_stats[feats]

In [ ]:
mUsageStats2 = process_mUsageStats(mUsageStats)

# check
print(f'\n # mUsageStats2 shape: {mUsageStats2.shape}')
mUsageStats2.head(1)

 # mUsageStats2 shape: (689, 11)

,subject_id,lifelog_date,beforebed_통화&전화_앱이용시간,beforebed_메신저&카카오톡_앱이용시간,beforebed_YouTube_앱이용시간,beforebed_NAVER_앱이용시간,beforebed_캐시워크_앱이용시간,beforebed_성경일독Q_앱이용시간,beforebed_이용앱개수,beforebed_핸드폰사용시간,beforebed_평균대비핸드폰사용시간
0,id01,2024-06-26,0.9809,14.5713,0.0000,0.1351,5.4722,27.6892,20.0000,156.8681,-58.3000

In [ ]:
mUsageStats2 = process_mUsageStats(mUsageStats)
print(mUsageStats2.shape)

mUsageStats2 = fill_missing_dates_by_subject(mUsageStats2)
print(mUsageStats2.shape)

weekday_map = {
    0: '월요일', 1: '화요일', 2: '수요일', 3: '목요일',
    4: '금요일', 5: '토요일', 6: '일요일'
}
mUsageStats2['weekday'] = mUsageStats2['lifelog_date'].dt.dayofweek.map(weekday_map)
mUsageStats2['month'] = mUsageStats2['lifelog_date'].dt.month

mUsageStats2['lifelog_date'] = mUsageStats2['lifelog_date'].astype(str)
train['lifelog_date'] = train['lifelog_date'].astype(str)

mUsageStats2 = mUsageStats2.merge(train[['subject_id','lifelog_date','Q1','Q2','Q3','S1','S2','S3']],on=['subject_id','lifelog_date'],how='left')
print(mUsageStats2.shape)

a1_map = {
    'Q1':'Q1(기상직후 수면의질)',
    'Q2':'Q2(취침직전 신체적피로)',
    'Q3':'Q3(취침직전 스트레스)',
    'S1':'S1(기상직후 수면시간)',
    'S2':'S2(기상직후 수면효율)',
    'S3':'S3(기상직후 수면지연시간)',
}

mUsageStats2 = mUsageStats2.rename(columns=a1_map)
mUsageStats2.head()

(689, 11)
(843, 11)
(843, 19)

,lifelog_date,subject_id,beforebed_통화&전화_앱이용시간,beforebed_메신저&카카오톡_앱이용시간,beforebed_YouTube_앱이용시간,beforebed_NAVER_앱이용시간,beforebed_캐시워크_앱이용시간,beforebed_성경일독Q_앱이용시간,beforebed_이용앱개수,beforebed_핸드폰사용시간,beforebed_평균대비핸드폰사용시간,weekday,month,Q1(기상직후 수면의질),Q2(취침직전 신체적피로),Q3(취침직전 스트레스),S1(기상직후 수면시간),S2(기상직후 수면효율),S3(기상직후 수면지연시간)
0,2024-06-26,id01,0.9809,14.5713,0.0000,0.1351,5.4722,27.6892,20.0000,156.8681,-58.3000,수요일,6,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000
1,2024-06-27,id01,31.2269,10.1212,0.4516,5.2204,4.1854,22.4449,22.0000,119.2085,-68.3000,목요일,6,0.0000,0.0000,0.0000,0.0000,1.0000,1.0000
2,2024-06-28,id01,3.2414,1.8173,20.9373,13.0355,0.0163,29.5744,23.0000,113.7970,-69.7000,금요일,6,1.0000,0.0000,0.0000,1.0000,1.0000,1.0000
3,2024-06-29,id01,0.0000,4.6347,17.2053,1.2352,0.0033,16.7300,13.0000,62.7274,-83.3000,토요일,6,1.0000,0.0000,1.0000,2.0000,0.0000,0.0000
4,2024-06-30,id01,19.6152,11.2251,15.8671,0.6836,13.9035,38.1486,20.0000,145.8567,-61.2000,일요일,6,0.0000,1.0000,1.0000,1.0000,1.0000,1.0000

In [ ]:
%%time

# CPU times: user 40.4 s, sys: 7.17 s, total: 47.6 s
# Wall time: 59min 11s

"""
- mACStatus: Indicates whether the smartphone is currently being charged.
- mActivity: Value calculated by the Google Activity Recognition API.
- mAmbience: Ambient sound identification labels and their respective probabilities.
- mBle: Bluetooth devices around individual subject.
- mGps: Multiple GPS coordinates measured within a single minute using the smartphone.
- mLight: Ambient light measured by the smartphone.
- (✔️) mScreenStatus: Indicates whether the smartphone screen is in use.
- (✔️) mUsageStats: Indicates which apps were used on the smartphone and for how long.
- mWifi: Wifi devices around individual subject.
- wHr: Heart rate readings recorded by the smartwatch.
- wLight: Ambient light measured by the smartwatch.
- wPedo: Step data recorded by the smartwatch.
"""

system_message = f"""
# 🔈지침: 당신은 데이터 분석 전문가입니다.
- 모델 설명 : For the purpose of training a learning model to predict sleep health, fatigue, and stress, the following six metrics were derived from sleep sensor data and self-reported survey records.
- [데이터]에는 결측치가 존재합니다. 이를 채워야 합니다.


# 🔈주의사항 (중요!!)
- 결측값을 추정할 때 다양한 정보를 종합적으로 고려해야 합니다.
  → 다양한 정보: 전일 학습데이터, 통계데이터, Q1~S1 정보, 주말 유무(금요일 포함), 7~8월 유무 등
- 앱이용시간 단위는 분(minutes) 입니다.
- 앱이용시간 추정 시 가능한 값의 범위는 최소 0 ~ 180 (180분=3시간) 입니다.
- 기존값이 있는 경우에는 **해당 셀을 그대로 유지**하며, **빈칸(null)**인 경우에만 보완합니다.
- 입력으로 주어진 테이블의 다른 값들도 절대 수정하지 마세요. **오직 결측치만 채워야 합니다.**
- 누락된 셀은 반드시 채워야 하며, **빈 셀 없이 모든 셀을 채워진 상태로 출력**해야 합니다.
- 출력은 항상 **모든 셀에 값이 채워진 상태**여야 합니다. **빈칸을 남기지 마세요.**

### 🔈답변 작성 양식
- 답변에 지침내용을 포함하지 않습니다.
- 결측치만 채우고 기존값이 존재하는을 그대로 사용합니다.
"""

# ================================================================
# 설정값
save_path = '/content/drive/MyDrive/data/ch2025_data_items/share/hjy/mUsageStats'
dataname  = 'mUsageStats'
version   = '20250608_v1'
data      = mUsageStats2.copy()
# ================================================================

# run
parsed_results = []
for subject_id in tqdm(data['subject_id'].unique(), desc="Processing each subject"):
# for subject_id in tqdm(['id06'], desc="Processing each subject"):

    print(f'# subject_id:{subject_id}')

    sub1 = data[data['subject_id'] == subject_id]
    학습데이터 = sub1.to_csv(index=False, sep="\t")

    # ----------------------------------------------------------------------------------------------
    # 통계데이터
    a1 = data[data['subject_id'] == subject_id].groupby(['weekday']).apply(lambda x:pd.Series({
      'beforebed_통화&전화_앱이용시간': x['beforebed_통화&전화_앱이용시간'].mean()
     ,'beforebed_메신저&카카오톡_앱이용시간': x['beforebed_메신저&카카오톡_앱이용시간'].mean()
     ,'beforebed_YouTube_앱이용시간': x['beforebed_YouTube_앱이용시간'].mean()
     ,'beforebed_NAVER_앱이용시간': x['beforebed_NAVER_앱이용시간'].mean()
     ,'beforebed_캐시워크_앱이용시간': x['beforebed_캐시워크_앱이용시간'].mean()
     ,'beforebed_성경일독Q_앱이용시간': x['beforebed_성경일독Q_앱이용시간'].mean()
     ,'beforebed_이용앱개수': x['beforebed_이용앱개수'].mean()
     ,'beforebed_핸드폰사용시간': x['beforebed_핸드폰사용시간'].mean()
     ,'beforebed_평균대비핸드폰사용시간': x['beforebed_평균대비핸드폰사용시간'].mean()
    })).reset_index()

    a2 = data[data['subject_id'] == subject_id].groupby(['month','weekday']).apply(lambda x:pd.Series({
      'beforebed_통화&전화_앱이용시간': x['beforebed_통화&전화_앱이용시간'].mean()
     ,'beforebed_메신저&카카오톡_앱이용시간': x['beforebed_메신저&카카오톡_앱이용시간'].mean()
     ,'beforebed_YouTube_앱이용시간': x['beforebed_YouTube_앱이용시간'].mean()
     ,'beforebed_NAVER_앱이용시간': x['beforebed_NAVER_앱이용시간'].mean()
     ,'beforebed_캐시워크_앱이용시간': x['beforebed_캐시워크_앱이용시간'].mean()
     ,'beforebed_성경일독Q_앱이용시간': x['beforebed_성경일독Q_앱이용시간'].mean()
     ,'beforebed_이용앱개수': x['beforebed_이용앱개수'].mean()
     ,'beforebed_핸드폰사용시간': x['beforebed_핸드폰사용시간'].mean()
     ,'beforebed_평균대비핸드폰사용시간': x['beforebed_평균대비핸드폰사용시간'].mean()
    })).reset_index()

    # a1을 weekday 기준으로 merge
    a2_filled = a2.merge(
        a1,
        on='weekday',
        suffixes=('', '_a1'),
        how='left'
    )

    # 결측값이 있는 경우 a1 값으로 대체
    a2_filled['beforebed_통화&전화_앱이용시간'] = a2_filled['beforebed_통화&전화_앱이용시간'].fillna(a2_filled['beforebed_통화&전화_앱이용시간_a1'])
    a2_filled['beforebed_메신저&카카오톡_앱이용시간'] = a2_filled['beforebed_메신저&카카오톡_앱이용시간'].fillna(a2_filled['beforebed_메신저&카카오톡_앱이용시간_a1'])
    a2_filled['beforebed_YouTube_앱이용시간'] = a2_filled['beforebed_YouTube_앱이용시간'].fillna(a2_filled['beforebed_YouTube_앱이용시간_a1'])
    a2_filled['beforebed_NAVER_앱이용시간'] = a2_filled['beforebed_NAVER_앱이용시간'].fillna(a2_filled['beforebed_NAVER_앱이용시간_a1'])
    a2_filled['beforebed_캐시워크_앱이용시간'] = a2_filled['beforebed_캐시워크_앱이용시간'].fillna(a2_filled['beforebed_캐시워크_앱이용시간_a1'])
    a2_filled['beforebed_성경일독Q_앱이용시간'] = a2_filled['beforebed_성경일독Q_앱이용시간'].fillna(a2_filled['beforebed_성경일독Q_앱이용시간_a1'])
    a2_filled['beforebed_이용앱개수'] = a2_filled['beforebed_이용앱개수'].fillna(a2_filled['beforebed_이용앱개수_a1'])
    a2_filled['beforebed_핸드폰사용시간'] = a2_filled['beforebed_핸드폰사용시간'].fillna(a2_filled['beforebed_핸드폰사용시간_a1'])
    a2_filled['beforebed_평균대비핸드폰사용시간'] = a2_filled['beforebed_평균대비핸드폰사용시간'].fillna(a2_filled['beforebed_평균대비핸드폰사용시간_a1'])

    # 보조 컬럼 제거
    a2_filled = a2_filled.loc[:, ~a2_filled.columns.str.contains('_a1')]

    # a2_filled
    sub2 = a2_filled.copy()
    통계데이터 = sub2.to_csv(index=False, sep="\t")
    # ----------------------------------------------------------------------------------------------

    user_message = f"""
    # 🔈작업 순서
    1. 인접 값이 존재하는 경우 이를 먼저 결측치 추정에 활용하세요.
    2. 인접 값이 없는 경우 통계값을 활용하세요.

    # 🔈 xdata 설명
    - mUsageStats: Indicates which apps were used on the smartphone and for how long)기반으로 파생된 앱사용 시간 변수
    - 컬럼명 prefix인 beforebed는 취침전을 의미하면 취침전 시간 9 PM ~ 11 PM 시간대 발생한 앱사용 기록을 의미한다.

    # 🔈 ydata 설명 (예측타겟)
    - Q1: 기상 직후 수면의 질 (0: 평균 이하, 1: 평균 이상)
    - Q2: 취침 직전 신체 피로 수준 (0: 높은 피로, 1: 낮은 피로)
    - Q3: 취침 직전 스트레스 수준 (0: 높은 스트레스, 1: 낮은 스트레스)
    - S1: 수면시간 가이드라인 준수여부 (0: 미준수, 1: 부분 준수, 2: 완전 준수)
    - S2: 수면 효율 가이드라인 준수여부 (0: 미준수, 1: 준수)
    - S3: 수면 잠들기 지연시간 가이드라인 준수여부 (0: 미준수, 1: 준수)

    # 🔈도메인 지식
    - 취짐전 핸드폰 사용은 수면의 질에 악영향을 줄 수 있다는 연구 결과가 있다.
    - 금요일, 토요일에는 다음날이 휴일이기 때문에 늦게까지 핸드폰을 사용할 가능성이 높음
    - 전일 상태가 오늘 상태에 영향을 줄 수 있음

    # 🔈통계데이터
    {통계데이터}

    # 🔈데이터
    {학습데이터}

    # 🔈답변 출력 형식
    lifelog_date\tsubject_id\tbeforebed_통화&전화_앱이용시간\tbeforebed_메신저&카카오톡_앱이용시간\tbeforebed_YouTube_앱이용시간\tbeforebed_NAVER_앱이용시간\tbeforebed_캐시워크_앱이용시간\tbeforebed_성경일독Q_앱이용시간\tbeforebed_이용앱개수\tbeforebed_핸드폰사용시간\tbeforebed_평균대비핸드폰사용시간\n
    2024-06-26\tid01\t0.98095\t14.571316666666668\t0.0\t0.1351\t5.472166666666666\t27.689150000000005\t20.0\t156.8681\t-58.3\n
    2024-06-27\tid01\t31.2269\t10.12125\t0.45155\t5.220433333333333\t4.185383333333333\t22.444850000000002\t22.0\t119.2085\t-68.3\n

    # 답변:
    """

    try:
        # 질의
        messages = [
            {"role": "system", "content": system_message},
            {"role": "user", "content": user_message}
        ]

        sampling_params = SamplingParams(max_tokens=37000, temperature=0, seed=42) # 38960
        outputs = llm.chat(messages, sampling_params=sampling_params)

        # 텍스트 추출 및 <think> 제거
        result_text = outputs[0].outputs[0].text

        # 저장: 원본 텍스트 백업
        with open(f"{save_path}/{dataname}_{subject_id}_result_raw.txt", "w", encoding="utf-8") as f:
            f.write(result_text)

        cleaned_text = re.sub(r"<think>.*?</think>", "", result_text, flags=re.DOTALL).strip()

        # 파싱 (탭 구분 텍스트 → DataFrame)
        from io import StringIO
        df_parsed = pd.read_csv(StringIO(cleaned_text), sep="\t")

        # 결측 존재 시 재시도 (+1회 추가 시도)
        if df_parsed['beforebed_평균대비핸드폰사용시간'].isna().sum()>10:
            print(f"[RETRY] 결측치 발견 → subject_id: {subject_id} 다시 실행합니다.")
            outputs = llm.chat(messages, sampling_params=sampling_params)
            result_text = outputs[0].outputs[0].text
            cleaned_text = re.sub(r"<think>.*?</think>", "", result_text, flags=re.DOTALL).strip()
            df_parsed = pd.read_csv(StringIO(cleaned_text), sep="\t")

        parsed_results.append(df_parsed)

    except Exception as e:
        print(f"[ERROR] Parsing failed for subject {subject_id}: {e}")
        print(result_text[:500])

    # 잠시 대기: 서버 보호 + Rate 제한 회피
    import time
    time.sleep(2)

# 모든 subject 결과 병합
data_filled_na = pd.concat(parsed_results, ignore_index=True)
data_filled_na.columns = ['lifelog_date','subject_id']+[i+'_llm' for i in data_filled_na.columns if i not in ['lifelog_date','subject_id']]
data_filled_na.to_excel(f'{save_path}/{dataname}_llm_{version}.xlsx',index=False)

# 비교검증데이터 저장
data_filled_na['lifelog_date'] = data_filled_na['lifelog_date'].astype(str)
data['lifelog_date'] = data['lifelog_date'].astype(str)
data_filled_na['subject_id'] = data_filled_na['subject_id'].astype(str)
data['subject_id'] = data['subject_id'].astype(str)
data = data.merge(data_filled_na,on=['lifelog_date','subject_id'],how='left')
data.to_excel(f'{save_path}/{dataname}_llm_check_{version}.xlsx',index=False)

# check
data.head()

Processing each subject:   0%|          | 0/10 [00:00<?, ?it/s]

# subject_id:id01

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

### 🔥 mWifi 주변wifi (수정)
- Wifi devices around individual subject.
 - -30 ~ -50 dBm	매우 강한 신호 (최적)
 - -51 ~ -60 dBm	강한 신호 (문제 없음)
 - -61 ~ -70 dBm	괜찮은 신호 (약간 느릴 수 있음)
 - -71 ~ -80 dBm	약한 신호 (끊김 주의)
 - -81 dBm 이하	매우 약한 신호 (거의 끊김)

In [ ]:
def extract_wifi_info(row):
    wifi_data = row['m_wifi']
    bssids = [item['bssid'] for item in wifi_data]
    rssis = [item['rssi'] for item in wifi_data]
    return pd.Series({'bssid': bssids, 'rssi': rssis})

mWifi = pd.read_parquet(path+'ch2025_mWifi.parquet')
mWifi[['bssid', 'rssi']] = mWifi.apply(extract_wifi_info, axis=1)
mWifi['lifelog_date'] = mWifi['timestamp'].astype(str).str[:10]
# mWifi = fill_missing_dates_by_subject(mWifi)
mWifi.head(1)

,subject_id,timestamp,m_wifi,bssid,rssi,lifelog_date
0,id01,2024-06-26 12:03:00,"[{'bssid': 'a0:0f:37:9a:5d:8b', 'rssi': -78}, {'bssid': 'a0:0f:37:9a:5d:8c', 'rssi': -78}, {'bssid': 'a0:0f:37:9a:5d:8d', 'rssi': -78}, {'bssid': 'a0:0f:37:9a:5d:8e', 'rssi': -78}, {'bssid': 'a0:0f:37:9a:5d:8f', 'rssi': -78}, {'bssid': 'a0:0f:37:96:56:ef', 'rssi': -58}, {'bssid': '88:36:6c:86:75:84', 'rssi': -72}, {'bssid': 'a0:0f:37:96:56:ee', 'rssi': -58}, {'bssid': 'a0:0f:37:96:56:ed', 'rssi': -58}, {'bssid': '86:25:19:b5:b2:a5', 'rssi': -61}, {'bssid': 'a0:0f:37:96:56:ec', 'rssi': -58}, {'bssid': '1e:39:29:8e:fb:e9', 'rssi': -71}, {'bssid': '52:c2:e8:c7:9b:e4', 'rssi': -82}, {'bssid': 'a0:0f:37:96:56:eb', 'rssi': -58}, {'bssid': '12:e3:c7:09:20:34', 'rssi': -88}, {'bssid': '58:86:94:4a:08:b8', 'rssi': -82}, {'bssid': '90:9f:33:28:d0:2e', 'rssi': -78}, {'bssid': '00:26:66:bc:4e:18', 'rssi': -85}, {'bssid': 'f6:0a:f4:43:4b:ba', 'rssi': -45}, {'bssid': '10:e3:c7:09:20:35', 'rssi': -63}, {'bssid': '10:e3:c7:09:20:34', 'rssi': -89}, {'bssid': '1c:39:29:48:04:92', 'rssi': -82}, {'bssid': '12:e3:c7:07:9d:df', 'rssi': -83}, {'bssid': '86:25:19:c3:44:07', 'rssi': -84}, {'bssid': 'a0:0f:37:9a:37:2f', 'rssi': -76}, {'bssid': 'a0:0f:37:9a:37:2e', 'rssi': -76}, {'bssid': 'a0:0f:37:9a:37:2d', 'rssi': -76}, {'bssid': '0a:09:b4:74:05:ec', 'rssi': -72}, {'bssid': 'a0:0f:37:9a:37:2c', 'rssi': -76}, {'bssid': 'a0:0f:37:9a:37:2b', 'rssi': -76}, {'bssid': '0a:09:b4:74:05:eb', 'rssi': -59}, {'bssid': 'c0:25:2f:d8:c1:a6', 'rssi': -82}, {'bssid': '16:7f:67:bb:fa:f8', 'rssi': -79}, {'bssid': '3c:f3:92:ff:00:01', 'rssi': -82}, {'bssid': '06:09:b4:74:05:ec', 'rssi': -72}, {'bssid': '06:09:b4:74:05:eb', 'rssi': -59}, {'bssid': '12:e3:c7:0a:74:d1', 'rssi': -78}, {'bssid': '88:36:6c:a9:6f:8e', 'rssi': -63}, {'bssid': '02:e3:c7:09:20:34', 'rssi': -88}, {'bssid': '00:09:b4:74:05:eb', 'rssi': -60}, {'bssid': '00:09:b4:74:05:ec', 'rssi': -72}, {'bssid': '00:1d:93:93:cf:fe', 'rssi': -19}, {'bssid': '8e:e2:ac:a5:9d:15', 'rssi': -72}]","[a0:0f:37:9a:5d:8b, a0:0f:37:9a:5d:8c, a0:0f:37:9a:5d:8d, a0:0f:37:9a:5d:8e, a0:0f:37:9a:5d:8f, a0:0f:37:96:56:ef, 88:36:6c:86:75:84, a0:0f:37:96:56:ee, a0:0f:37:96:56:ed, 86:25:19:b5:b2:a5, a0:0f:37:96:56:ec, 1e:39:29:8e:fb:e9, 52:c2:e8:c7:9b:e4, a0:0f:37:96:56:eb, 12:e3:c7:09:20:34, 58:86:94:4a:08:b8, 90:9f:33:28:d0:2e, 00:26:66:bc:4e:18, f6:0a:f4:43:4b:ba, 10:e3:c7:09:20:35, 10:e3:c7:09:20:34, 1c:39:29:48:04:92, 12:e3:c7:07:9d:df, 86:25:19:c3:44:07, a0:0f:37:9a:37:2f, a0:0f:37:9a:37:2e, a0:0f:37:9a:37:2d, 0a:09:b4:74:05:ec, a0:0f:37:9a:37:2c, a0:0f:37:9a:37:2b, 0a:09:b4:74:05:eb, c0:25:2f:d8:c1:a6, 16:7f:67:bb:fa:f8, 3c:f3:92:ff:00:01, 06:09:b4:74:05:ec, 06:09:b4:74:05:eb, 12:e3:c7:0a:74:d1, 88:36:6c:a9:6f:8e, 02:e3:c7:09:20:34, 00:09:b4:74:05:eb, 00:09:b4:74:05:ec, 00:1d:93:93:cf:fe, 8e:e2:ac:a5:9d:15]","[-78, -78, -78, -78, -78, -58, -72, -58, -58, -61, -58, -71, -82, -58, -88, -82, -78, -85, -45, -63, -89, -82, -83, -84, -76, -76, -76, -72, -76, -76, -59, -82, -79, -82, -72, -59, -78, -63, -88, -60, -72, -19, -72]",2024-06-26

In [ ]:
def process_mWifi(df,threshold):

    df = df.copy()
    df['lifelog_date'] = pd.to_datetime(df['lifelog_date'])
    df['timestamp'] = pd.to_datetime(df['timestamp'])
    df['요일'] = df['lifelog_date'].dt.day_name()
    df['hour'] = df['timestamp'].dt.hour

    # 시간대 분류
    def map_time_period(row):
        if 20 <= row['hour'] <= 23:
            return 'beforebed'
        else:
            return 'activehour'

    df['time_period'] = df.apply(map_time_period, axis=1)

    features = []
    grouped = df.groupby(['subject_id', 'lifelog_date','time_period'])

    for (subject_id, date, period), group in grouped:
        scan_count = len(group)
        bssid_flat = sum(group['bssid'], [])  # flatten
        rssi_flat = sum(group['rssi'], [])    # flatten

        unique_bssid_count = len(set(bssid_flat))
        avg_rssi = sum(rssi_flat) / len(rssi_flat) if rssi_flat else None
        max_rssi = max(rssi_flat) if rssi_flat else None
        min_rssi = min(rssi_flat) if rssi_flat else None
        strong_rssi_ratio = sum(1 for r in rssi_flat if r > -60) / len(rssi_flat) if rssi_flat else 0
        empty_scan_count = sum(1 for b in group['bssid'] if len(b) == 0)

        # 가장 많이 탐지된 BSSID
        bssid_counter = Counter(bssid_flat)
        top_bssid, top_bssid_count = bssid_counter.most_common(1)[0] if bssid_counter else (None, 0)

        first_time = group['timestamp'].min()
        last_time = group['timestamp'].max()
        hour_span = (last_time - first_time).total_seconds() / 60  # 분 단위

        features.append({
            'subject_id': subject_id,
            'lifelog_date': date,
            'time_period': period,  #
            'scan_count': scan_count,
            'unique_bssid_count': unique_bssid_count,
            'avg_rssi': avg_rssi,
            'max_rssi': max_rssi,
            'min_rssi': min_rssi,
            'strong_signal_ratio': strong_rssi_ratio,
            'empty_scan_count': empty_scan_count,
            'top_bssid': top_bssid,
            'top_bssid_count': top_bssid_count,
            'hour_span_minutes': hour_span
        })

    daily_stats = pd.DataFrame(features)

    # 피벗
    daily_stats = daily_stats.pivot(index=['subject_id', 'lifelog_date'], columns='time_period')
    daily_stats.columns = [f"{tp}_{metric}" for metric, tp in daily_stats.columns]
    daily_stats = daily_stats.reset_index()

    return daily_stats

In [ ]:
mWifi2 = process_mWifi(mWifi,threshold=-60)

# check
print(f'\n # mWifi2 shape: {mWifi2.shape}')
mWifi2.head(1)

 # mWifi2 shape: (685, 22)

,subject_id,lifelog_date,activehour_scan_count,beforebed_scan_count,activehour_unique_bssid_count,beforebed_unique_bssid_count,activehour_avg_rssi,beforebed_avg_rssi,activehour_max_rssi,beforebed_max_rssi,activehour_min_rssi,beforebed_min_rssi,activehour_strong_signal_ratio,beforebed_strong_signal_ratio,activehour_empty_scan_count,beforebed_empty_scan_count,activehour_top_bssid,beforebed_top_bssid,activehour_top_bssid_count,beforebed_top_bssid_count,activehour_hour_span_minutes,beforebed_hour_span_minutes
0,id01,2024-06-26,48.0000,21.0000,354.0000,56.0000,-71.7103,-64.5025,-19.0000,-26.0000,-91.0000,-88.0000,0.1892,0.3881,0.0000,0.0000,86:25:19:9f:9b:be,04:09:a5:3a:c8:6a,19.0000,15.0000,470.0000,236.0000

### ✔️ wHr 심박동수 (수정)
- Heart rate readings recorded by the smartwatch.

In [ ]:
def process_wHr(df):
    heart_rate = df["heart_rate"].values  # [[0, 1, 2, ...], ...]

    def _process_feature(heart_rate):
        if len(heart_rate) == 0:
            return 0., 0., 0., 0., 0.

        heart_rate = np.array(sum(map(lambda x: x.tolist(), heart_rate), []))
        mean_hr = heart_rate.mean() if len(heart_rate) > 0 else 0
        min_hr = heart_rate.min() if len(heart_rate) > 0 else 0
        max_hr = heart_rate.max() if len(heart_rate) > 0 else 0
        std_hr = heart_rate.std() if len(heart_rate) > 0 else 0
        high_hr = heart_rate[heart_rate > 100].sum()

        return mean_hr, min_hr, max_hr, std_hr, high_hr

    # 하루
    active_hour_mean_hr, active_hour_min_hr, active_hour_max_hr, active_hour_std_hr, active_hour_high_hr = _process_feature(heart_rate[df["hour"].isin(ACTIVE_HOURS)])

    # 잠자는 시간대
    sleep_hour_mean_hr, sleep_hour_min_hr, sleep_hour_max_hr, sleep_hour_std_hr, sleep_hour_high_hr = _process_feature(heart_rate[df["hour"].isin(SLEEP_HOURS)])

    return pd.Series({
        'active_hour_mean_hr': active_hour_mean_hr,
        'active_hour_min_hr': active_hour_min_hr,
        'active_hour_max_hr': active_hour_max_hr,
        'active_hour_std_hr': active_hour_std_hr,
        'active_hour_high_hr': active_hour_high_hr,
        'sleep_hour_mean_hr': sleep_hour_mean_hr,
        'sleep_hour_min_hr': sleep_hour_min_hr,
        'sleep_hour_max_hr': sleep_hour_max_hr,
        'sleep_hour_std_hr': sleep_hour_std_hr,
        'sleep_hour_high_hr': sleep_hour_high_hr
    })

wHr_ori = load_data(DataType.wHr)
wHr_ori = shift_lifelog_date(wHr_ori, target_hours=SLEEP_HOURS)

wHr2 = (
    wHr_ori
    .groupby(["subject_id", "lifelog_date"], group_keys=False, as_index=False, sort=False, observed=True)
    .apply(process_wHr)
    .reset_index(drop=True)
)

describe_df(wHr2)

# shape:
(679, 12)

# dtypes:
subject_id                   category
lifelog_date           datetime64[ns]
active_hour_mean_hr           float64
active_hour_min_hr            float64
active_hour_max_hr            float64
active_hour_std_hr            float64
active_hour_high_hr           float64
sleep_hour_mean_hr            float64
sleep_hour_min_hr             float64
sleep_hour_max_hr             float64
sleep_hour_std_hr             float64
sleep_hour_high_hr            float64
dtype: object

,subject_id,lifelog_date,active_hour_mean_hr,active_hour_min_hr,active_hour_max_hr,active_hour_std_hr,active_hour_high_hr,sleep_hour_mean_hr,sleep_hour_min_hr,sleep_hour_max_hr,sleep_hour_std_hr,sleep_hour_high_hr
0,id01,2024-06-26,81.2434,59.0000,142.0000,11.8712,243191.0000,0.0000,0.0000,0.0000,0.0000,0.0000
1,id01,2024-06-27,79.3523,53.0000,130.0000,12.6371,119052.0000,0.0000,0.0000,0.0000,0.0000,0.0000
2,id01,2024-06-28,77.3601,51.0000,135.0000,12.5109,142587.0000,0.0000,0.0000,0.0000,0.0000,0.0000

# nan_stats:
                     missing_count  missing_ratio(%)
subject_id                       0            0.0000
lifelog_date                     0            0.0000
active_hour_mean_hr              0            0.0000
active_hour_min_hr               0            0.0000
active_hour_max_hr               0            0.0000
active_hour_std_hr               0            0.0000
active_hour_high_hr              0            0.0000
sleep_hour_mean_hr               0            0.0000
sleep_hour_min_hr                0            0.0000
sleep_hour_max_hr                0            0.0000
sleep_hour_std_hr                0            0.0000
sleep_hour_high_hr               0            0.0000

### ✔️ wLight 라이트 (수정)
- Ambient light measured by the smartwatch.  
  - 어두운 밤 0.1 ~ 1 lux 캄캄한 방, 달빛 없는 밤
  - 가로등 켜진 거리 10 ~ 20 lux 흐릿한 외부 조명
  - 실내 조명 100 ~ 500 lux 사무실, 일반 거실
  - 밝은 실외 10,000 ~ 25,000 lux 맑은 날 햇빛
  - 직사광선 아래 30,000 ~ 100,000 lux 여름 한낮, 매우 강한 햇빛

In [ ]:
def process_mLight(df):
    light = df["m_light"].values  # [534.0, 224, ...]

    def _process_feature(light):
        if len(light) == 0:
            return 0., 0., 0., 0., np.array([])

        ligths = np.array(light)
        mean_light = ligths.mean() if len(ligths) > 0 else 0
        min_light = ligths.min() if len(ligths) > 0 else 0
        max_light = ligths.max() if len(ligths) > 0 else 0
        std_light = ligths.std() if len(ligths) > 0 else 0

        return mean_light, min_light, max_light, std_light, ligths

    # 하루
    active_hour_mean_light, active_hour_min_light, active_hour_max_light, active_hour_std_light, _ = _process_feature(light[df["hour"].isin(ACTIVE_HOURS)])

    # 잠자는 시간대
    sleep_hour_mean_light, sleep_hour_min_light, sleep_hour_max_light, sleep_hour_std_light, _= _process_feature(light[df["hour"].isin(SLEEP_HOURS)])

    # 잠 자러갈 때
    might_go_to_sleep_light = light[df["hour"].isin(MIGHT_GO_TO_SLEEP_HOURS)]
    might_go_to_sleep_timestamps = df["timestamp"].values[df["hour"].isin(MIGHT_GO_TO_SLEEP_HOURS)]
    _, _, _, _, might_go_to_sleep_lights = _process_feature(might_go_to_sleep_light)
    first_sleep_timestamps = might_go_to_sleep_timestamps[(might_go_to_sleep_lights < 10.0)]
    first_sleep_datetime = (
        pd.to_datetime(first_sleep_timestamps[0]) if len(first_sleep_timestamps) > 0
        else pd.to_datetime(might_go_to_sleep_timestamps[-1]) if len(might_go_to_sleep_timestamps) > 0
        else pd.to_datetime(datetime(2024, 1, 1, MIGHT_GO_TO_SLEEP_HOURS[-1], 0, 0))  # default to the last hour of the range
    )
    first_sleep_minutes = (first_sleep_datetime.hour * 60 if first_sleep_datetime.hour > 12 else (first_sleep_datetime.hour + 24) * 60) + first_sleep_datetime.minute

    # 일어날 때
    might_wakeup_light = light[df["hour"].isin(MIGHT_WAKEUP_HOURS)]
    might_wakeup_timestamps = df["timestamp"].values[df["hour"].isin(MIGHT_WAKEUP_HOURS)]
    _, _, _, _, might_wakeup_lights = _process_feature(might_wakeup_light)
    wakeup_timestamps = might_wakeup_timestamps[(might_wakeup_lights > 10.0)]
    first_move_datetime = (
        pd.to_datetime(wakeup_timestamps[0]) if len(wakeup_timestamps) > 0
        else pd.to_datetime(might_wakeup_timestamps[-1]) if len(might_wakeup_timestamps) > 0
        else pd.to_datetime(datetime(2024, 1, 1, MIGHT_WAKEUP_HOURS[-1], 0, 0))  # default to the last hour of the range
    )
    first_wakeup_minutes = (first_move_datetime.hour if first_move_datetime.hour > 12 else first_move_datetime.hour + 24) * 60 + first_move_datetime.minute

    return pd.Series({
        'active_hour_mean_light': active_hour_mean_light,
        'active_hour_min_light': active_hour_min_light,
        'active_hour_max_light': active_hour_max_light,
        'active_hour_std_light': active_hour_std_light,
        'sleep_hour_mean_light': sleep_hour_mean_light,
        'sleep_hour_min_light': sleep_hour_min_light,
        'sleep_hour_max_light': sleep_hour_max_light,
        'sleep_hour_std_light': sleep_hour_std_light,
        'mlight_first_sleep_minutes': first_sleep_minutes,
        'mlight_first_wakeup_minutes': first_wakeup_minutes,
    })

wLight_ori = load_data(DataType.wLight)
wLight_ori = shift_lifelog_date(wLight_ori, target_hours=SLEEP_HOURS)

wLight2 = (
    wLight_ori
    .rename(columns={"w_light": "m_light"})
    .groupby(["subject_id", "lifelog_date"], group_keys=False, as_index=False, sort=False, observed=True)
    .apply(process_mLight)
    .reset_index(drop=True)
)

wLight2.rename(
    columns={
        col: "w" + col.replace("mlight_", "wlight_")
        for col in wLight.columns if col not in ["subject_id", "lifelog_date"]
    }, inplace=True
)

describe_df(wLight2)

# shape:
(752, 12)

# dtypes:
subject_id                           category
lifelog_date                   datetime64[ns]
active_hour_mean_light                float64
active_hour_min_light                 float64
active_hour_max_light                 float64
active_hour_std_light                 float64
sleep_hour_mean_light                 float64
sleep_hour_min_light                  float64
sleep_hour_max_light                  float64
sleep_hour_std_light                  float64
mlight_first_sleep_minutes            float64
mlight_first_wakeup_minutes           float64
dtype: object

,subject_id,lifelog_date,active_hour_mean_light,active_hour_min_light,active_hour_max_light,active_hour_std_light,sleep_hour_mean_light,sleep_hour_min_light,sleep_hour_max_light,sleep_hour_std_light,mlight_first_sleep_minutes,mlight_first_wakeup_minutes
0,id01,2024-06-26,299.4151,0.0000,20874.0000,1220.1126,0.0000,0.0000,0.0000,0.0000,1274.0000,1980.0000
1,id01,2024-06-27,290.7522,0.0000,12464.0000,1031.2252,0.0000,0.0000,0.0000,0.0000,1200.0000,1830.0000
2,id01,2024-06-28,518.8263,0.0000,91584.0000,3794.5034,0.0000,0.0000,0.0000,0.0000,1209.0000,1835.0000

# nan_stats:
                             missing_count  missing_ratio(%)
subject_id                               0            0.0000
lifelog_date                             0            0.0000
active_hour_mean_light                   0            0.0000
active_hour_min_light                    0            0.0000
active_hour_max_light                    0            0.0000
active_hour_std_light                    0            0.0000
sleep_hour_mean_light                    0            0.0000
sleep_hour_min_light                     0            0.0000
sleep_hour_max_light                     0            0.0000
sleep_hour_std_light                     0            0.0000
mlight_first_sleep_minutes               0            0.0000
mlight_first_wakeup_minutes              0            0.0000

### ✔️ wPedo 걸음수
- Step data recorded by the smartwatch.

In [ ]:
def process_mPedo(df):

    def _process_feature(df):
        if len(df) == 0:
            return 0., 0., 0.

        steps = df["step"].values
        distances = df["distance"].values
        calories = df["burned_calories"].values

        steps = steps.sum() if len(steps) > 0 else 0
        distance = distances.sum() if len(distances) > 0 else 0
        burned_calories = calories.sum() if len(calories) > 0 else 0

        return steps, distance, burned_calories

    # 하루
    active_hour_steps, active_hour_distance, active_hour_burned_calories = _process_feature(df[df["hour"].isin(ACTIVE_HOURS)])

    # 잠자는 시간대
    sleep_hour_steps, sleep_hour_distance, sleep_hour_burned_calories = _process_feature(df[df["hour"].isin(SLEEP_HOURS)])

    return pd.Series({
        'active_hour_steps': active_hour_steps,
        'active_hour_distance': active_hour_distance,
        'active_hour_burned_calories': active_hour_burned_calories,
        'sleep_hour_steps': sleep_hour_steps,
        'sleep_hour_distance': sleep_hour_distance,
        'sleep_hour_burned_calories': sleep_hour_burned_calories
    })

wPedo_ori = load_data(DataType.wPedo)
wPedo_ori = shift_lifelog_date(wPedo_ori, target_hours=SLEEP_HOURS)

wPedo2 = (
    wPedo_ori
    .groupby(["subject_id", "lifelog_date"], group_keys=False, as_index=False, sort=False, observed=True)
    .apply(process_mPedo)
    .reset_index(drop=True)
)

describe_df(wPedo2)

# shape:
(735, 8)

# dtypes:
subject_id                           category
lifelog_date                   datetime64[ns]
active_hour_steps                     float64
active_hour_distance                  float64
active_hour_burned_calories           float64
sleep_hour_steps                      float64
sleep_hour_distance                   float64
sleep_hour_burned_calories            float64
dtype: object

,subject_id,lifelog_date,active_hour_steps,active_hour_distance,active_hour_burned_calories,sleep_hour_steps,sleep_hour_distance,sleep_hour_burned_calories
0,id01,2024-06-26,3578.0000,2782.1901,189.3191,0.0000,0.0000,0.0000
1,id01,2024-06-27,2619.0000,2020.5527,280.2708,10.0000,6.8300,0.0000
2,id01,2024-06-28,3726.0000,2888.0892,116.1595,0.0000,0.0000,0.0000

# nan_stats:
                             missing_count  missing_ratio(%)
subject_id                               0            0.0000
lifelog_date                             0            0.0000
active_hour_steps                        0            0.0000
active_hour_distance                     0            0.0000
active_hour_burned_calories              0            0.0000
sleep_hour_steps                         0            0.0000
sleep_hour_distance                      0            0.0000
sleep_hour_burned_calories               0            0.0000

### 🔥 Sleeptime 일어난 건수

- Sleeptime에 (mLight 주변 밝기), (wLight 앰비언트 라이트) 변화 건수

In [ ]:
def compute_night_awake_features(df, prefix):

    df = df.copy()
    df['lifelog_date'] = df['timestamp'].astype(str).str[:10]
    df['timestamp'] = pd.to_datetime(df['timestamp'])

    # 00시~06시 필터
    df['hour'] = df['timestamp'].dt.hour
    df_night = df[(df['hour'] >= 0) & (df['hour'] < 6)].copy()

    # 깨어있는 분 계산
    df_night['awake_minute'] = (df_night[prefix] > 0).astype(int)

    # 깨어난 횟수 계산 (0 → 양수 전환)
    def count_awake_blocks(x):
        return ((x > 0) & (x.shift(fill_value=0) == 0)).sum()

    # 그룹별 집계
    result = df_night.groupby(['subject_id', 'lifelog_date']).agg(
        awake_minutes=('awake_minute', 'sum'),
        awake_blocks=(prefix, count_awake_blocks)
    ).reset_index()

    # 컬럼명 변경
    result = result.rename(columns={
        'awake_minutes': f'{prefix}_awake_minutes',
        'awake_blocks': f'{prefix}_awake_blocks'
    })

    # train에 결과 합치기 위해서 -1 day 하기
    result['lifelog_date'] = pd.to_datetime(result['lifelog_date'])
    result['lifelog_date'] = result['lifelog_date'] + pd.Timedelta(days=-1)
    result['lifelog_date'] = result['lifelog_date'].astype(str)

    return result

In [ ]:
mAwakeBlocks = compute_night_awake_features(mLight,'m_light')
wAwakeBlocks = compute_night_awake_features(wLight,'w_light')
AwakeBlocks = mAwakeBlocks.merge(wAwakeBlocks, on=['subject_id','lifelog_date'], how='outer')
AwakeBlocks['light_awake_minutes'] = AwakeBlocks[['m_light_awake_minutes','w_light_awake_minutes']].max(axis=1)
AwakeBlocks['light_awake_blocks'] = AwakeBlocks[['m_light_awake_blocks','w_light_awake_blocks']].max(axis=1)

# check
print(mAwakeBlocks.shape)
print(wAwakeBlocks.shape)
print(AwakeBlocks.shape)

(677, 4)
(565, 4)
(687, 8)

### 📌 merge 데이터
- train, test 기간 서로 겹침

In [ ]:
train = pd.read_csv('/content/drive/MyDrive/data/ch2025_metrics_train.csv')
test = pd.read_csv('/content/drive/MyDrive/data/ch2025_submission_sample.csv')

# 일자변수 타입 변환
mACStatus2['lifelog_date'] = mACStatus2['lifelog_date'].astype(str)
mActivity21['lifelog_date'] = mActivity21['lifelog_date'].astype(str)
mActivity22['lifelog_date'] = mActivity22['lifelog_date'].astype(str)
mAmbience2['lifelog_date'] = mAmbience2['lifelog_date'].astype(str)
mBle2['lifelog_date'] = mBle2['lifelog_date'].astype(str)
mGps2['lifelog_date'] = mGps2['lifelog_date'].astype(str)
mLight21['lifelog_date'] = mLight21['lifelog_date'].astype(str)
mLight22['lifelog_date'] = mLight22['lifelog_date'].astype(str)
mLight23['lifelog_date'] = mLight23['lifelog_date'].astype(str)
mScreenStatus2['lifelog_date'] = mScreenStatus2['lifelog_date'].astype(str)
mUsageStats2['lifelog_date'] = mUsageStats2['lifelog_date'].astype(str)
mWifi2['lifelog_date'] = mWifi2['lifelog_date'].astype(str)
wHr2['lifelog_date'] = wHr2['lifelog_date'].astype(str)
wLight2['lifelog_date'] = wLight2['lifelog_date'].astype(str)
wPedo2['lifelog_date'] = wPedo2['lifelog_date'].astype(str)

# ---- new ----

AwakeBlocks['lifelog_date'] = AwakeBlocks['lifelog_date'].astype(str)

In [ ]:
df_list = [
    mACStatus2,       # 1
    mActivity21,       # 2
    mActivity22,       # 2
    mAmbience2,       # 3
    mBle2,            # 4
    mGps2,            # 5
    mLight21,          # 6
    mLight22,          # 6
    mLight23,          # 6
    mScreenStatus2,   # 7
    mUsageStats2,     # 8
    mWifi2,           # 9
    wHr2,             # 10
    wLight2,          # 11
    wPedo2,           # 12
    # ---- new ----
    AwakeBlocks
]

data = reduce(lambda left, right: pd.merge(left, right, on=['subject_id', 'lifelog_date'], how='outer'), df_list)
data['lifelog_date'] = data['lifelog_date'].astype(str)

# 중복체크
print(data.shape)
print(data[['subject_id','lifelog_date']].drop_duplicates().shape)

# merge
train2 = train.merge(data, on=['subject_id','lifelog_date'], how='left')
test2 = test.merge(data, on=['subject_id','lifelog_date'], how='left')

# 저장
print('# train  shape:',train.shape)
print('# train2 shape:',test2.shape)
print('# test   shape:',test.shape)
print('# test2  shape:',test2.shape)

(806, 232)
(806, 2)
# train  shape: (450, 9)
# train2 shape: (250, 239)
# test   shape: (250, 9)
# test2  shape: (250, 239)

In [ ]:
# 저장
train2.to_parquet(f"/content/drive/MyDrive/data/train_0608_v1.parquet")
test2.to_parquet(f"/content/drive/MyDrive/data/test_0608_v1.parquet")

## 📦 학습(전처리 파일 불러오기)

In [ ]:
train2 = pd.read_parquet(f"/content/drive/MyDrive/data/train_0608_v1.parquet")
test2 = pd.read_parquet(f"/content/drive/MyDrive/data/test_0608_v1.parquet")

train = train2.copy()
test = test2.copy()

In [ ]:
# 검증데이터셋 PK모음
valid_ids1 = ['id012024-07-24', 'id012024-07-27', 'id012024-08-18', 'id012024-08-19', 'id012024-08-20', 'id012024-08-21', 'id012024-08-22', 'id012024-08-24', 'id012024-08-25', 'id012024-08-26', 'id012024-08-27', 'id012024-08-28', 'id012024-08-29', 'id012024-08-30', 'id022024-08-23', 'id022024-08-24', 'id022024-09-16', 'id022024-09-17', 'id022024-09-19', 'id022024-09-20', 'id022024-09-21', 'id022024-09-22', 'id022024-09-23', 'id022024-09-24', 'id022024-09-25', 'id022024-09-26', 'id022024-09-27', 'id022024-09-28', 'id032024-08-30', 'id032024-09-01', 'id032024-09-02', 'id032024-09-03', 'id032024-09-05', 'id032024-09-06', 'id032024-09-07', 'id042024-09-03', 'id042024-09-04', 'id042024-09-05', 'id042024-09-06', 'id042024-09-07', 'id042024-09-08', 'id042024-09-09', 'id042024-10-08', 'id042024-10-09', 'id042024-10-10', 'id042024-10-11', 'id042024-10-12', 'id042024-10-13', 'id042024-10-14', 'id052024-10-19', 'id052024-10-23', 'id052024-10-24', 'id052024-10-25', 'id052024-10-26', 'id052024-10-27', 'id052024-10-28', 'id062024-07-25', 'id062024-07-26', 'id062024-07-27', 'id062024-07-28', 'id062024-07-29', 'id062024-07-30', 'id062024-07-31', 'id072024-07-07', 'id072024-07-08', 'id072024-07-09', 'id072024-07-10', 'id072024-07-11', 'id072024-07-12', 'id072024-07-13', 'id072024-07-30', 'id072024-08-01', 'id072024-08-02', 'id072024-08-03', 'id072024-08-04', 'id072024-08-05', 'id072024-08-06', 'id082024-08-28', 'id082024-08-29', 'id082024-08-30', 'id082024-08-31', 'id082024-09-01', 'id082024-09-02', 'id082024-09-04', 'id092024-08-02', 'id092024-08-22', 'id092024-08-23', 'id092024-08-24', 'id092024-08-25', 'id092024-08-27', 'id092024-08-28', 'id092024-08-29', 'id092024-08-30', 'id092024-08-31', 'id092024-09-01', 'id092024-09-02', 'id092024-09-03', 'id092024-09-04', 'id102024-08-28', 'id102024-08-30', 'id102024-08-31', 'id102024-09-01', 'id102024-09-02', 'id102024-09-03', 'id102024-09-06']
valid_ids2 = ['id012024-07-24', 'id012024-07-27', 'id012024-08-19', 'id012024-08-20', 'id012024-08-21', 'id012024-08-22', 'id012024-08-24', 'id012024-08-25', 'id012024-08-26', 'id012024-08-27', 'id012024-08-28', 'id012024-08-29', 'id012024-08-30', 'id012024-09-01', 'id022024-08-23', 'id022024-08-24', 'id022024-09-13', 'id022024-09-14', 'id022024-09-16', 'id022024-09-17', 'id022024-09-19', 'id022024-09-20', 'id022024-09-21', 'id022024-09-22', 'id022024-09-23', 'id022024-09-24', 'id022024-09-25', 'id022024-09-26', 'id032024-09-02', 'id032024-09-03', 'id032024-09-05', 'id032024-09-06', 'id032024-09-07', 'id032024-09-08', 'id042024-09-07', 'id042024-09-08', 'id042024-09-09', 'id042024-09-11', 'id042024-09-17', 'id042024-09-18', 'id042024-09-28', 'id042024-09-29', 'id042024-10-21', 'id042024-10-23', 'id042024-10-27', 'id052024-08-29', 'id052024-08-30', 'id052024-08-31', 'id052024-09-01', 'id052024-10-10', 'id052024-11-05', 'id052024-11-06', 'id052024-11-10', 'id052024-11-11', 'id052024-11-12', 'id052024-11-15', 'id062024-08-03', 'id062024-08-04', 'id062024-08-05', 'id062024-08-06', 'id062024-08-11', 'id062024-08-16', 'id062024-08-19', 'id072024-07-02', 'id072024-07-03', 'id072024-07-04', 'id072024-07-06', 'id072024-07-07', 'id072024-07-08', 'id072024-07-09', 'id072024-08-02', 'id072024-08-03', 'id072024-08-04', 'id072024-08-05', 'id072024-08-06', 'id072024-08-07', 'id072024-08-08', 'id082024-09-01', 'id082024-09-02', 'id082024-09-04', 'id082024-09-06', 'id082024-09-12', 'id082024-09-16', 'id082024-09-17', 'id092024-07-27', 'id092024-07-28', 'id092024-07-30', 'id092024-07-31', 'id092024-08-02', 'id092024-08-04', 'id092024-08-05', 'id092024-08-22', 'id092024-08-23', 'id092024-08-24', 'id092024-08-25', 'id092024-08-27', 'id092024-08-28', 'id092024-08-29', 'id102024-08-30', 'id102024-08-31', 'id102024-09-01', 'id102024-09-02', 'id102024-09-03', 'id102024-09-06', 'id102024-09-08']
valid_ids3 = ['id012024-07-20', 'id012024-07-23', 'id012024-08-19', 'id012024-08-20', 'id012024-08-21', 'id012024-08-22', 'id012024-08-24', 'id012024-08-25', 'id012024-08-26', 'id012024-08-27', 'id012024-08-28', 'id012024-08-29', 'id012024-08-30', 'id012024-09-01', 'id022024-08-21', 'id022024-08-22', 'id022024-09-11', 'id022024-09-12', 'id022024-09-13', 'id022024-09-14', 'id022024-09-16', 'id022024-09-17', 'id022024-09-19', 'id022024-09-20', 'id022024-09-21', 'id022024-09-22', 'id022024-09-23', 'id022024-09-24', 'id032024-09-05', 'id032024-09-06', 'id032024-09-07', 'id032024-09-08', 'id032024-09-10', 'id032024-09-12', 'id032024-09-13', 'id042024-08-27', 'id042024-08-28', 'id042024-08-29', 'id042024-08-30', 'id042024-08-31', 'id042024-09-01', 'id042024-09-02', 'id042024-10-01', 'id042024-10-02', 'id042024-10-03', 'id042024-10-04', 'id042024-10-05', 'id042024-10-06', 'id042024-10-07', 'id052024-10-28', 'id052024-10-29', 'id052024-10-30', 'id052024-10-31', 'id052024-11-03', 'id052024-11-05', 'id052024-11-06', 'id062024-07-31', 'id062024-08-01', 'id062024-08-02', 'id062024-08-03', 'id062024-08-04', 'id062024-08-05', 'id062024-08-06', 'id072024-06-29', 'id072024-06-30', 'id072024-07-01', 'id072024-07-02', 'id072024-07-03', 'id072024-07-04', 'id072024-07-06', 'id072024-08-07', 'id072024-08-08', 'id072024-08-09', 'id072024-08-10', 'id072024-08-11', 'id072024-08-12', 'id072024-08-13', 'id082024-08-19', 'id082024-08-20', 'id082024-08-22', 'id082024-08-23', 'id082024-08-24', 'id082024-08-25', 'id082024-08-26', 'id092024-08-04', 'id092024-08-22', 'id092024-08-23', 'id092024-08-24', 'id092024-08-25', 'id092024-08-27', 'id092024-08-28', 'id092024-08-29', 'id092024-08-30', 'id092024-08-31', 'id092024-09-01', 'id092024-09-02', 'id092024-09-03', 'id092024-09-04', 'id102024-09-02', 'id102024-09-03', 'id102024-09-06', 'id102024-09-08', 'id102024-09-09', 'id102024-09-12', 'id102024-09-15']
valid_ids4 = ['id012024-07-24', 'id012024-07-27', 'id012024-08-18', 'id012024-08-19', 'id012024-08-20', 'id012024-08-21', 'id012024-08-22', 'id012024-08-24', 'id012024-08-25', 'id012024-08-26', 'id012024-08-27', 'id012024-08-28', 'id012024-08-29', 'id012024-08-30', 'id022024-08-23', 'id022024-08-24', 'id022024-09-12', 'id022024-09-13', 'id022024-09-14', 'id022024-09-16', 'id022024-09-17', 'id022024-09-22', 'id022024-09-23', 'id022024-09-24', 'id022024-09-25', 'id022024-09-26', 'id022024-09-27', 'id022024-09-28', 'id032024-08-30', 'id032024-09-01', 'id032024-09-02', 'id032024-09-07', 'id032024-09-08', 'id032024-09-10', 'id042024-09-03', 'id042024-09-04', 'id042024-09-05', 'id042024-09-11', 'id042024-09-17', 'id042024-09-18', 'id042024-09-28', 'id042024-09-29', 'id042024-10-21', 'id042024-10-23', 'id042024-10-27', 'id052024-08-29', 'id052024-08-30', 'id052024-08-31', 'id052024-09-01', 'id052024-10-10', 'id052024-11-03', 'id052024-11-05', 'id052024-11-10', 'id052024-11-11', 'id052024-11-12', 'id052024-11-15', 'id062024-07-27', 'id062024-07-28', 'id062024-07-29', 'id062024-07-30', 'id062024-08-11', 'id062024-08-16', 'id062024-08-19', 'id072024-07-03', 'id072024-07-04', 'id072024-07-06', 'id072024-07-10', 'id072024-07-11', 'id072024-07-12', 'id072024-07-13', 'id072024-07-29', 'id072024-07-30', 'id072024-08-01', 'id072024-08-02', 'id072024-08-03', 'id072024-08-04', 'id072024-08-05', 'id082024-09-01', 'id082024-09-02', 'id082024-09-04', 'id082024-09-06', 'id082024-09-12', 'id082024-09-16', 'id082024-09-17', 'id092024-07-02', 'id092024-07-04', 'id092024-07-05', 'id092024-07-06', 'id092024-08-02', 'id092024-08-04', 'id092024-08-05', 'id092024-08-22', 'id092024-08-23', 'id092024-08-24', 'id092024-08-25', 'id092024-08-27', 'id092024-08-28', 'id092024-08-29', 'id102024-07-27', 'id102024-07-28', 'id102024-07-29', 'id102024-07-30', 'id102024-08-01', 'id102024-08-02', 'id102024-08-03']

### 🔥 이미지 파생변수

In [ ]:
img_model = 'resnet50' # resnet50, xception, resnext101_32x32d efficientnet_b0 convnext_base convnext_tiny

# 데이터 읽기
img_features = pd.read_csv(f'/content/drive/MyDrive/data/ch2025_data_items/img_features_ch5_sleeptime_{img_model}_5.csv')
img_features = img_features[sorted(img_features.columns,reverse=True)]
img_features.columns = ['image_path']+['img'+i for i in img_features.columns if i not in ['image_path']]

# 정규표현식으로 추출
img_features['subject_id'] = img_features['image_path'].str.extract(r'user(id\d+)_')[0]
img_features['lifelog_date'] = img_features['image_path'].str.extract(r'_(\d{4}-\d{2}-\d{2})_')[0]

# 정렬
img_features = img_features.sort_values(['subject_id', 'lifelog_date'])

# # lag
# for lag in [1, 2]:
#     img_features[f'img0_lag{lag}'] = img_features.groupby('subject_id')['img0'].shift(lag)
#     img_features[f'img1_lag{lag}'] = img_features.groupby('subject_id')['img1'].shift(lag)

# check
img_features = img_features.drop(columns=['image_path'])
print(len(img_features))
display(img_features.head())

700

     img4    img3    img2    img1   img0 subject_id lifelog_date
0  0.2700  0.0377  0.2072 -0.4265 1.1548       id01   2024-06-26
1  0.2784 -0.0511  0.1298 -0.5424 1.1326       id01   2024-06-27
2 -0.0239 -0.1738  0.0195  0.1455 0.3727       id01   2024-06-28
3  0.0031 -0.1181  0.1111  0.2888 0.3363       id01   2024-06-29
4  0.1253 -0.3247 -0.2009 -0.2437 0.3198       id01   2024-06-30

In [ ]:
# add img features
train['lifelog_date'] = train['lifelog_date'].astype(str)
test['lifelog_date'] = test['lifelog_date'].astype(str)
train = train.merge(img_features,on=['subject_id','lifelog_date'],how='left')
test = test.merge(img_features,on=['subject_id','lifelog_date'],how='left')

### 🔥 추정수면효율
- 추정수면효율 (S2) : (불끈 시간 - 핸드폰 이용한 마지막 시간) / 추정수면시간

In [ ]:
def calculate_sleep_duration_min(sleep_time, wake_time):
    """
    취침 시각(sleep_time)과 기상 시각(wake_time)을 입력받아 수면 시간(분) 반환
    단위는 float 시간 (예: 23.5, 6.25)
    """
    if pd.isna(sleep_time) or pd.isna(wake_time):
        return None
    if wake_time < sleep_time:
        wake_time += 24  # 자정 넘긴 경우 보정
    duration = (wake_time - sleep_time) * 60
    return round(duration)

In [ ]:
train['불끈시간부터기상시간'] = train.apply(lambda x: calculate_sleep_duration_min(x['lights_off_time'],x['wake_time']),axis=1)
test['불끈시간부터기상시간'] = test.apply(lambda x: calculate_sleep_duration_min(x['lights_off_time'],x['wake_time']),axis=1)

In [ ]:
train['추정수면효율'] = train['불끈시간부터기상시간']/train['sleep_duration_min']
test['추정수면효율'] = test['불끈시간부터기상시간']/test['sleep_duration_min']

# 이상값 제거
train['추정수면효율'] = np.where(train['추정수면효율']<-5,np.nan,train['추정수면효율'])
test['추정수면효율'] = np.where(test['추정수면효율']<-5,np.nan,test['추정수면효율'])
train['추정수면효율'] = np.where(train['추정수면효율']>5,np.nan,train['추정수면효율'])
test['추정수면효율'] = np.where(test['추정수면효율']>55,np.nan,test['추정수면효율'])

### 🔥 추가 파생변수

In [ ]:
# sleep duration

train['sleep_time_m_light_sleep_time'] = train['sleep_time'] - train['light_sleep_time']
test['sleep_time_m_light_sleep_time'] = test['sleep_time'] - test['light_sleep_time']

train['wake__time_m_light_wake__time'] = train['wake_time'] - train['light_wake_time']
test['wake__time_m_light_wake__time'] = test['wake_time'] - test['light_wake_time']

train['sleep_duration_min_m_light_sleep_duration_min'] = train['sleep_duration_min'] - train['light_sleep_duration_min']
test['sleep_duration_min_m_light_sleep_duration_min'] = test['sleep_duration_min'] - test['light_sleep_duration_min']

train['sleep_time_d_light_sleep_time'] = train['sleep_time'] / train['light_sleep_time']
test['sleep_time_d_light_sleep_time'] = test['sleep_time'] / test['light_sleep_time']

train['wake__time_d_light_wake__time'] = train['wake_time'] / train['light_wake_time']
test['wake__time_d_light_wake__time'] = test['wake_time'] / test['light_wake_time']

train['sleep_duration_min_d_light_sleep_duration_min'] = train['sleep_duration_min'] / train['light_sleep_duration_min']
test['sleep_duration_min_d_light_sleep_duration_min'] = test['sleep_duration_min'] / test['light_sleep_duration_min']

train['sleep_time_min'] = train[['sleep_time','light_sleep_time']].min(axis=1)
train['sleep_time_max'] = train[['sleep_time','light_sleep_time']].max(axis=1)

train['wake_time_min'] = train[['wake_time','light_wake_time']].min(axis=1)
train['wake_time_max'] = train[['wake_time','light_wake_time']].max(axis=1)

train['sleep_duration_min_min'] = train[['sleep_duration_min','light_sleep_duration_min']].min(axis=1)
train['sleep_duration_min_max'] = train[['sleep_duration_min','light_sleep_duration_min']].max(axis=1)

test['sleep_time_min'] = test[['sleep_time','light_sleep_time']].min(axis=1)
test['sleep_time_max'] = test[['sleep_time','light_sleep_time']].max(axis=1)

test['wake_time_min'] = test[['wake_time','light_wake_time']].min(axis=1)
test['wake_time_max'] = test[['wake_time','light_wake_time']].max(axis=1)

test['sleep_duration_min_min'] = test[['sleep_duration_min','light_sleep_duration_min']].min(axis=1)
test['sleep_duration_min_max'] = test[['sleep_duration_min','light_sleep_duration_min']].max(axis=1)

In [ ]:
# 요일 컬럼 추가 (예: 월요일, 화요일, ...)
train['lifelog_date'] = pd.to_datetime(train['lifelog_date'])
test['lifelog_date'] = pd.to_datetime(test['lifelog_date'])

# 요일
weekday_map = {
    0: '월요일', 1: '화요일', 2: '수요일', 3: '목요일',
    4: '금요일', 5: '토요일', 6: '일요일'
}
train['weekday'] = train['lifelog_date'].dt.dayofweek.map(weekday_map)
test['weekday'] = test['lifelog_date'].dt.dayofweek.map(weekday_map)

# 월
train['month'] = train['lifelog_date'].dt.month
test['month'] = test['lifelog_date'].dt.month

# weekend
train['weekend'] = np.where(train['weekday'].isin(['토요일','일요일']),1,0)
test['weekend'] = np.where(test['weekday'].isin(['토요일','일요일']),1,0)

# weekend
train['weekend2'] = np.where(train['weekday'].isin(['토요일','금요일']),1,0)
test['weekend2'] = np.where(test['weekday'].isin(['토요일','금요일']),1,0)

# weekend
train['weekend3'] = np.where(train['weekday'].isin(['토요일','금요일','일요일']),1,0)
test['weekend3'] = np.where(test['weekday'].isin(['토요일','금요일','일요일']),1,0)

# 공휴일
공휴일 = [
     '2024-08-15'
    ,'2024-09-16'
    ,'2024-09-17'
    ,'2024-09-18'
    ,'2024-10-03'
    ,'2024-10-09'
]
train['공휴일'] = np.where(train['lifelog_date'].isin(공휴일),1,0)
test['공휴일'] = np.where(test['lifelog_date'].isin(공휴일),1,0)

# 주말 + 공휴일 묶어주기
train['weekend_holilday'] = np.where( ((train['weekend']==0) & (train['공휴일']==1)), 1, train['weekend'])
test['weekend_holilday'] = np.where( ((test['weekend']==0) & (test['공휴일']==1)), 1, test['weekend'])

In [ ]:
def add_prev_day_flag(df):
    df = df.copy()
    df['lifelog_date'] = pd.to_datetime(df['lifelog_date'])

    # 각 subject_id별로 전날 날짜 만들기
    df['prev_day'] = df['lifelog_date'] - pd.Timedelta(days=1)

    # subject_id + 날짜 기준으로 원본 키 구성
    key_set = set(zip(df['subject_id'], df['lifelog_date']))

    # 전날 데이터가 존재하면 1, 없으면 0
    df['has_prev_day_data'] = df[['subject_id', 'prev_day']].apply(
        lambda row: 1 if (row['subject_id'], row['prev_day']) in key_set else 0, axis=1
    )

    return df.drop(columns=['prev_day'])

train = add_prev_day_flag(train)
test = add_prev_day_flag(test)

In [ ]:
# 추정휴가
def rule_based_sum(x):
    rules = (
        #  (x['sleep_duration_min'] > (x['avg_sleep_duration']))
        #  (x['sleep_duration_min'] > (x['avg_sleep_duration']+60))
          (x['sleep_duration_diff']>0)
        & (x['week_type'] == 'weekday')
        # & (x['month'].isin([7,8]))
    )
    return rules

train['vacation'] = train.groupby('subject_id').apply(rule_based_sum).reset_index(level=0, drop=True).astype(int)
test['vacation'] = test.groupby('subject_id').apply(rule_based_sum).reset_index(level=0, drop=True).astype(int)

# check
test.groupby(['subject_id'])['vacation'].sum().head()

subject_id
id01    12
id02    12
id03     6
id04    16
id05     6
Name: vacation, dtype: int64

### 📌 결측 처리

In [ ]:
# 숫자형 컬럼만 선택해서 결측값 -1로 채우기
train[train.select_dtypes(include='number').columns] = train.select_dtypes(include='number').fillna(-9)
test[test.select_dtypes(include='number').columns] = test.select_dtypes(include='number').fillna(-9)

In [ ]:
feats = ['wake_time_diff', 'sleep_time_diff', 'sleep_duration_diff']+['wake_time_ratio','sleep_time_ratio','sleep_duration_ratio']

def interpolate_na(data,feats):
  data['lifelog_date'] = pd.to_datetime(data['lifelog_date'])
  data = data.set_index('lifelog_date')

  # 그룹별로 각 열에 대해 시계열 보간 수행
  data[feats] = (
      data.groupby('subject_id')[feats]
          .apply(lambda group: group.replace(-9,np.nan).interpolate(method='time'))
          .reset_index(level=0, drop=True)  # 인덱스 정리
  )
  data = data.reset_index()
  return data

train = interpolate_na(train,feats)
test = interpolate_na(test,feats)

In [ ]:
# 인코딩1
train['weekday'] = train['weekday'].map(dict([(j,i) for i,j in weekday_map.items()]))
test['weekday'] = test['weekday'].map(dict([(j,i) for i,j in weekday_map.items()]))
# train = pd.get_dummies(train,columns=['weekday'],drop_first=True)
# test = pd.get_dummies(test,columns=['weekday'],drop_first=True)

### get_oof_predictions

In [ ]:
def get_oof_predictions(X, y, lgb_params, xgb_params, meta_weights, n_splits=5, is_multiclass=False, num_class=None):
    from sklearn.model_selection import StratifiedKFold
    from lightgbm import LGBMClassifier
    from xgboost import XGBClassifier
    import numpy as np

    lgb_A = meta_weights['lgb']
    xgb_B = meta_weights['xgb']

    oof_preds_lgb = np.zeros(len(X)) if not is_multiclass else np.zeros((len(X), num_class))
    oof_preds_xgb = np.zeros_like(oof_preds_lgb)

    skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)

    for train_idx, valid_idx in skf.split(X, y):
        X_train, X_valid = X.iloc[train_idx], X.iloc[valid_idx]
        y_train, y_valid = y.iloc[train_idx], y.iloc[valid_idx]

        if is_multiclass:
            lgb_model = LGBMClassifier(**lgb_params, objective='multiclass', num_class=num_class)
            xgb_model = XGBClassifier(**xgb_params, objective='multi:softprob', num_class=num_class)
        else:
            lgb_model = LGBMClassifier(**lgb_params)
            xgb_model = XGBClassifier(**xgb_params)

        lgb_model.fit(X_train, y_train)
        xgb_model.fit(X_train, y_train)

        if is_multiclass:
            oof_preds_lgb[valid_idx] = lgb_model.predict_proba(X_valid)
            oof_preds_xgb[valid_idx] = xgb_model.predict_proba(X_valid)
        else:
            oof_preds_lgb[valid_idx] = lgb_model.predict_proba(X_valid)[:, 1]
            oof_preds_xgb[valid_idx] = xgb_model.predict_proba(X_valid)[:, 1]

    # 앙상블 및 후처리
    if is_multiclass:
        ensemble_proba = lgb_A * oof_preds_lgb + xgb_B * oof_preds_xgb

        # 클래스 2 보정
        ensemble_proba[:, 2] *= 1.1
        ensemble_proba /= ensemble_proba.sum(axis=1, keepdims=True)

        oof_preds = np.argmax(ensemble_proba, axis=1)
    else:
        ensemble_proba = lgb_A * oof_preds_lgb + xgb_B * oof_preds_xgb
        oof_preds = (ensemble_proba > 0.5).astype(int)

    return oof_preds

### run_encoding

In [ ]:
def run_encoding(train_df, test_df, all_targets, encoder_feats):

  # 노이즈 수준 설정
  def add_noise(series, noise_level, seed=3):
      rng = np.random.default_rng(seed)
      return series * (1 + noise_level * rng.standard_normal(len(series)))

  noise_level = 0.015  # 필요에 따라 조정

  # 타겟인코딩
  for tgt in all_targets:

    # encoder_feats = ['subject_id','month','weekend']

    #### 타겟인코딩1

    subject_mean = train_df.groupby(encoder_feats)[tgt].mean().rename(f'{tgt}_te')
    train_df = train_df.merge(subject_mean, on=encoder_feats, how='left')
    test_df = test_df.merge(subject_mean, on=encoder_feats, how='left')
    # global_mean = train_df[tgt].mean()
    # test_df[f'{tgt}_te'] = test_df[f'{tgt}_te'].fillna(global_mean)

    # 노이즈 추가
    train_df[f'{tgt}_te'] = add_noise(train_df[f'{tgt}_te'], noise_level)
    test_df[f'{tgt}_te'] = add_noise(test_df[f'{tgt}_te'], noise_level)

    #### 타겟인코딩2

    # encoder_feats = ['subject_id','month','weekend2']

    # 새로운 범주형 열 생성
    train_df['TMP'] = train_df[encoder_feats].applymap(str).apply(lambda x: ''.join(x) ,axis=1)
    test_df['TMP'] = test_df[encoder_feats].applymap(str).apply(lambda x: ''.join(x) ,axis=1)

    # 인코더
    smoothing = 300 * 1.7
    encoder = TargetEncoder(cols=['TMP'], smoothing=smoothing) # 40, 300
    encoder.fit(train_df[['TMP']], train_df[tgt])

    # 인코딩 결과를 새로운 열에 저장
    train_df[f'{tgt}_te2'] = encoder.transform(train_df[['TMP']])
    test_df[f'{tgt}_te2'] = encoder.transform(test_df[['TMP']])

    # 노이즈 추가
    train_df[f'{tgt}_te2'] = add_noise(train_df[f'{tgt}_te2'], noise_level)
    test_df[f'{tgt}_te2'] = add_noise(test_df[f'{tgt}_te2'], noise_level)

    # 불필요한 변수 제거
    train_df = train_df.drop(columns=['TMP'])
    test_df = test_df.drop(columns=['TMP'])

  return train_df, test_df

### run_basemodel

In [ ]:
def apply_pseudo_labeling(X_test, y_pred_proba, threshold=0.9):

    # Binary classification
    if y_pred_proba.ndim == 1:
        # 확률이 양극단(0~0.1 or 0.9~1.0)인 것만 선택
        confident_idx = (y_pred_proba >= threshold) | (y_pred_proba <= 1 - threshold)
        y_pseudo = (y_pred_proba[confident_idx] >= 0.5).astype(int)

    # Multiclass classification
    else:
        max_proba = y_pred_proba.max(axis=1)
        confident_idx = max_proba >= threshold
        y_pseudo = np.argmax(y_pred_proba[confident_idx], axis=1)

    X_pseudo = X_test.iloc[confident_idx].copy()
    return X_pseudo, y_pseudo

In [ ]:
def run_basemodel(train, test, valid_ids, lgb_param_dict, xgb_param_dict, meta_weights, topn, n_splits, vi=False, random_state=42,
                  submit=False, get_oof=False, err_analysis=True):

    train_df = train.copy()
    test_df = test.copy()

    valid_ids['pk'] = valid_ids['subject_id']+valid_ids['sleep_date']
    train_df['pk'] = train_df['subject_id']+train_df['sleep_date']

    submission_final = test_df[['subject_id', 'sleep_date', 'lifelog_date']].copy()
    submission_final['lifelog_date'] = pd.to_datetime(submission_final['lifelog_date']).dt.date

    submission_valid = train_df.loc[train_df['pk'].isin(valid_ids['pk'].unique().tolist()),['subject_id', 'sleep_date', 'lifelog_date']].copy()
    submission_valid['lifelog_date'] = pd.to_datetime(submission_valid['lifelog_date']).dt.date

    # 타겟
    targets_binary = ['Q1', 'Q2', 'Q3', 'S2', 'S3']
    targets_binary_name = ['기상직후수면질','취침전신체적피로','취침전스트레스','수면효율','수면잠들기시간']
    target_multiclass = 'S1'
    all_targets = targets_binary + [target_multiclass]

    # ========================================= valid 모델 검증 =========================================

    total_avg_f1s = []
    val_f1 = []
    pred_valid = {}
    top_features_dict = {}

    # ----
    # binary
    # ----

    for col in targets_binary:

        train_df = train.copy()
        test_df = test.copy()

        if col in ['Q2','S2','S3']:
            encoder_feats = ['subject_id','month','weekend2']
            train_df, test_df = run_encoding(train_df, test_df, all_targets, encoder_feats)
        else:
            encoder_feats = ['subject_id','month','weekend']
            train_df, test_df = run_encoding(train_df, test_df, all_targets, encoder_feats)

        # 인코딩
        PK = ['sleep_date', 'lifelog_date', 'subject_id']
        encoder = LabelEncoder()
        categorical_features = [i for i in train_df.select_dtypes(include=['object', 'category']).columns if i not in PK+['pk']]
        for col in categorical_features:
            print(col)
            train_df[col] = encoder.fit_transform(train_df[col])
            test_df[col] = encoder.fit_transform(test_df[col])

        # X
        X = train_df.drop(columns=PK + all_targets)
        test_X = test_df.drop(columns=PK + all_targets)

        # 상관관계기반 변수선택
        # ==============================================================
        y = train_df[col]
        corr_series = X.corrwith(y).abs()
        if isinstance(topn,int)==True:
          top_features = corr_series.sort_values(ascending=False).head(topn).index.tolist()
        else:
          top_features = corr_series.sort_values(ascending=False).head(topn[col]).index.tolist()
        top_features_dict[col] = top_features
        # =========================================================

        valid_ids['pk'] = valid_ids['subject_id']+valid_ids['sleep_date']
        train_df['pk'] = train_df['subject_id']+train_df['sleep_date']

        X_valid = train_df.loc[train_df['pk'].isin(valid_ids['pk']),[i for i in X.columns.tolist() if i in top_features]].reset_index(drop=True).copy()
        X_train = train_df.loc[~train_df['pk'].isin(valid_ids['pk']),[i for i in X.columns.tolist() if i in top_features]].reset_index(drop=True).copy()
        y_valid = train_df.loc[train_df['pk'].isin(valid_ids['pk']),y.name].reset_index(drop=True).copy()
        y_train = train_df.loc[~train_df['pk'].isin(valid_ids['pk']),y.name].reset_index(drop=True).copy()

        # LightGBM
        lgb_params = lgb_param_dict[col].copy()
        lgb_params['random_state'] = random_state
        lgb_model = LGBMClassifier(**lgb_params)
        lgb_model.fit(X_train, y_train)

        # Feature importance
        if vi==True:
          fi_df = pd.DataFrame({'feature': lgb_model.feature_name_, 'importance': lgb_model.feature_importances_})
          top10 = fi_df.sort_values(by='importance', ascending=False).head(10)
          feat_str = ", ".join([f"{row['feature']}({int(row['importance'])})" for _, row in top10.iterrows()])
          print(f"[LGB][{col}] {feat_str}")

        # XGBoost
        xgb_params = xgb_param_dict[col].copy()
        xgb_params['random_state'] = random_state
        xgb_model = XGBClassifier(**xgb_params)
        xgb_model.fit(X_train, y_train)

        # Feature importance
        if vi==True:
          fi_df = pd.DataFrame({'feature': xgb_model.get_booster().feature_names, 'importance': xgb_model.feature_importances_})
          top10 = fi_df.sort_values(by='importance', ascending=False).head(10)
          feat_str = ", ".join([f"{row['feature']}({int(row['importance'])})" for _, row in top10.iterrows()])
          print(f"[XGB][{col}] {feat_str}")

        # Get predictions and ensemble
        lgb_pred_valid = lgb_model.predict_proba(X_valid)[:, 1]
        xgb_pred_valid = xgb_model.predict_proba(X_valid)[:, 1]

        lgb_A = meta_weights[col]['lgb']
        xgb_B = meta_weights[col]['xgb']

        pred_valid[col] = (lgb_A * lgb_pred_valid + xgb_B * xgb_pred_valid  > 0.5).astype(int)
        f1 = f1_score(y_valid, pred_valid[col], average='macro')
        val_f1.append(f1)


    # ----
    # multiclass
    # ----

    train_df = train.copy()
    test_df = test.copy()

    encoder_feats = ['subject_id','month','weekend2']
    train_df, test_df = run_encoding(train_df, test_df, all_targets, encoder_feats)

    # 인코딩
    PK = ['sleep_date', 'lifelog_date', 'subject_id']
    encoder = LabelEncoder()
    categorical_features = [i for i in train_df.select_dtypes(include=['object', 'category']).columns if i not in PK+['pk']]
    for col in categorical_features:
        print(col)
        train_df[col] = encoder.fit_transform(train_df[col])
        test_df[col] = encoder.fit_transform(test_df[col])

    # X
    X = train_df.drop(columns=PK + all_targets)
    test_X = test_df.drop(columns=PK + all_targets)

    # 상관관계기반 변수선택
    # ==============================================================
    y = train_df['S1']
    corr_series = X.corrwith(y).abs()
    if isinstance(topn,int)==True:
      top_features = corr_series.sort_values(ascending=False).head(topn).index.tolist()
    else:
      top_features = corr_series.sort_values(ascending=False).head(topn['S1']).index.tolist()
    top_features_dict['S1'] = top_features
    # =========================================================

    valid_ids['pk'] = valid_ids['subject_id']+valid_ids['sleep_date']
    train_df['pk'] = train_df['subject_id']+train_df['sleep_date']

    X_valid = train_df.loc[train_df['pk'].isin(valid_ids['pk']),[i for i in X.columns.tolist() if i in top_features]].reset_index(drop=True).copy()
    X_train = train_df.loc[~train_df['pk'].isin(valid_ids['pk']),[i for i in X.columns.tolist() if i in top_features]].reset_index(drop=True).copy()
    y_valid = train_df.loc[train_df['pk'].isin(valid_ids['pk']),y.name].reset_index(drop=True).copy()
    y_train = train_df.loc[~train_df['pk'].isin(valid_ids['pk']),y.name].reset_index(drop=True).copy()

    # LightGBM
    lgb_params = lgb_param_dict['S1'].copy()
    lgb_params['random_state'] = random_state
    lgb_model = LGBMClassifier(**lgb_params, objective='multiclass', num_class=3)
    lgb_model.fit(X_train, y_train)

    # Feature importance
    if vi==True:
      fi_df = pd.DataFrame({'feature': lgb_model.feature_name_, 'importance': lgb_model.feature_importances_})
      top10 = fi_df.sort_values(by='importance', ascending=False).head(10)
      feat_str = ", ".join([f"{row['feature']}({int(row['importance'])})" for _, row in top10.iterrows()])
      print(f"[LGB][S1] {feat_str}")

    # XGBoost
    xgb_params = xgb_param_dict['S1'].copy()
    xgb_params['random_state'] = random_state
    xgb_model = XGBClassifier(**xgb_params, objective='multi:softmax', num_class=3)
    xgb_model.fit(X_train, y_train)

    # Feature importance
    if vi==True:
      fi_df = pd.DataFrame({'feature': xgb_model.get_booster().feature_names, 'importance': xgb_model.feature_importances_})
      top10 = fi_df.sort_values(by='importance', ascending=False).head(10)
      feat_str = ", ".join([f"{row['feature']}({int(row['importance'])})" for _, row in top10.iterrows()])
      print(f"[XGB][S1] {feat_str}")

    # Get predictions and ensemble
    lgb_pred_valid = lgb_model.predict_proba(X_valid)
    xgb_pred_valid = xgb_model.predict_proba(X_valid)

    lgb_A = meta_weights['S1']['lgb']
    xgb_B = meta_weights['S1']['xgb']

    # pred_valid['S1'] = np.argmax(lgb_A * lgb_pred_valid + xgb_B * xgb_pred_valid, axis=1)
    ensemble_proba = lgb_A * lgb_pred_valid + xgb_B * xgb_pred_valid
    ensemble_proba[:, 2] *= 1.1  # 2번 클래스의 확률을 보정
    ensemble_proba /= ensemble_proba.sum(axis=1, keepdims=True)  # 다시 정규화
    pred_valid['S1'] = np.argmax(ensemble_proba, axis=1)

    f1 = f1_score(y_valid, pred_valid['S1'], average='macro')
    val_f1.append(f1)
    # ================================================================================================================

    # 점수
    # f1 = f1_score(y_valid, pred_valid['S1'], average='macro')
    # val_f1.append(f1)
    avg_f1 = np.mean(val_f1)
    total_avg_f1s.append(avg_f1)
    detail = " ".join([f"{name}({tname}):{score:.4f}" for name, tname, score in zip(targets_binary + [target_multiclass], targets_binary_name + ['수면시간'], val_f1)])
    print(f"# 평균 F1: {avg_f1:.4f} / [상세] {detail}")

    # valid pred 저장
    submission_valid['S1'] = pred_valid['S1']
    for col in targets_binary:
      submission_valid[col] = pred_valid[col]
    submission_valid = submission_valid[['subject_id', 'sleep_date', 'lifelog_date', 'Q1', 'Q2', 'Q3', 'S1', 'S2', 'S3']]
    fname = f"submission_valid_{np.mean(total_avg_f1s)}.csv"
    submission_valid.to_csv(fname, index=False)
    # print(f"# {fname} 저장 완료")

    # S1분포 확인
    a1 = train['S1'].value_counts(normalize=True)
    a2 = submission_valid['S1'].value_counts(normalize=True)
    s1_prop = pd.concat([a1,a2],axis=1)
    s1_prop.columns = ['train','valid']
    display(s1_prop)

    # 🔍 subject_id별 오차 통계 출력
    if err_analysis==True:
        df_eval = pd.DataFrame({
            'subject_id': submission_valid['subject_id'].values,
            'y_true': y_valid,
            'y_pred': pred_valid['S1']
        })
        df_eval['is_error'] = df_eval['y_true'] != df_eval['y_pred']

        subject_stats = df_eval.groupby('subject_id').agg(
            total_samples=('y_true', 'count'),
            error_count=('is_error', 'sum')
        )
        subject_stats['error_rate'] = subject_stats['error_count'] / subject_stats['total_samples']
        subject_stats = subject_stats.sort_values('error_rate', ascending=False)
        display(subject_stats)

    # ========================================= modoling with 100% train & no valid =========================================

    if submit == True:

      # ----
      # binary
      # ----

      binary_preds = {}
      binary_preds_proba = {}
      for col in targets_binary:

          train_df = train.copy()
          test_df = test.copy()

          if col in ['Q2','S2','S3']:
              encoder_feats = ['subject_id','month','weekend2']
              train_df, test_df = run_encoding(train_df, test_df, all_targets, encoder_feats)
          else:
              encoder_feats = ['subject_id','month','weekend']
              train_df, test_df = run_encoding(train_df, test_df, all_targets, encoder_feats)

          y = train_df[col]


          # 인코딩
          PK = ['sleep_date', 'lifelog_date', 'subject_id']
          encoder = LabelEncoder()
          categorical_features = [i for i in train_df.select_dtypes(include=['object', 'category']).columns if i not in PK+['pk']]
          for col in categorical_features:
              print(col)
              train_df[col] = encoder.fit_transform(train_df[col])
              test_df[col] = encoder.fit_transform(test_df[col])

          # X
          X = train_df.drop(columns=PK + all_targets)
          test_X = test_df.drop(columns=PK + all_targets)

          # Train LightGBM
          lgb_params = lgb_param_dict[col].copy()
          lgb_params['random_state'] = random_state
          lgb_model = LGBMClassifier(**lgb_params)
          lgb_model.fit(X[[i for i in X.columns.tolist() if i in top_features_dict[col]]], y)

          # Train XGBoost
          xgb_params = xgb_param_dict[col].copy()
          xgb_params['random_state'] = random_state
          xgb_model = XGBClassifier(**xgb_params)
          xgb_model.fit(X[[i for i in X.columns.tolist() if i in top_features_dict[col]]], y)

          # Get predictions and ensemble
          lgb_pred = lgb_model.predict_proba(test_X[[i for i in X.columns.tolist() if i in top_features_dict[col]]])[:, 1]
          xgb_pred = xgb_model.predict_proba(test_X[[i for i in X.columns.tolist() if i in top_features_dict[col]]])[:, 1]

          lgb_A = meta_weights[col]['lgb']
          xgb_B = meta_weights[col]['xgb']

          binary_preds[col] = (lgb_A * lgb_pred + xgb_B * xgb_pred  > 0.5).astype(int)

      # ----
      # multiclass
      # ----

      train_df = train.copy()
      test_df = test.copy()

      y = train_df[target_multiclass]

      encoder_feats = ['subject_id','month','weekend2']
      train_df, test_df = run_encoding(train_df, test_df, all_targets, encoder_feats)

      # 인코딩
      PK = ['sleep_date', 'lifelog_date', 'subject_id']
      encoder = LabelEncoder()
      categorical_features = [i for i in train_df.select_dtypes(include=['object', 'category']).columns if i not in PK+['pk']]
      for col in categorical_features:
          print(col)
          train_df[col] = encoder.fit_transform(train_df[col])
          test_df[col] = encoder.fit_transform(test_df[col])

      # X
      X = train_df.drop(columns=PK + all_targets)
      test_X = test_df.drop(columns=PK + all_targets)

      # Train LightGBM
      lgb_params = lgb_param_dict['S1'].copy()
      lgb_params['random_state'] = random_state
      lgb_model = LGBMClassifier(**lgb_params, objective='multiclass', num_class=3)
      lgb_model.fit(X[[i for i in X.columns.tolist() if i in top_features_dict['S1']]], y)

      # Train XGBoost
      xgb_params = xgb_param_dict['S1'].copy()
      xgb_params['random_state'] = random_state
      xgb_model = XGBClassifier(**xgb_params, objective='multi:softmax', num_class=3)
      xgb_model.fit(X[[i for i in X.columns.tolist() if i in top_features_dict['S1']]], y)

      # Get predictions and ensemble
      lgb_pred = lgb_model.predict_proba(test_X[[i for i in X.columns.tolist() if i in top_features_dict['S1']]])
      xgb_pred = xgb_model.predict_proba(test_X[[i for i in X.columns.tolist() if i in top_features_dict['S1']]])

      lgb_A = meta_weights['S1']['lgb']
      xgb_B = meta_weights['S1']['xgb']

      multiclass_pred = np.argmax(lgb_A * lgb_pred + xgb_B * xgb_pred, axis=1)

      # 예측 저장
      submission_final['S1'] = multiclass_pred
      for col in targets_binary:
        submission_final[col] = binary_preds[col]
      submission_final = submission_final[['subject_id', 'sleep_date', 'lifelog_date', 'Q1', 'Q2', 'Q3', 'S1', 'S2', 'S3']]
      fname = f"submission_{np.mean(total_avg_f1s)}.csv"
      submission_final.to_csv(fname, index=False)
      print(f"# {fname} 저장 완료")
      print(f"# submission shape:{submission_final.shape}")

      # 모델별 예측결과 비율 비교
      a11 = train_df[['Q1', 'Q2', 'Q3', 'S1', 'S2', 'S3']].sum()
      a13 = train_df[['Q1', 'Q2', 'Q3', 'S1', 'S2', 'S3']].apply(len)
      a12 = train_df[['Q1', 'Q2', 'Q3', 'S1', 'S2', 'S3']].mean()
      a21 = submission_final[['Q1', 'Q2', 'Q3', 'S1', 'S2', 'S3']].sum()
      a23 = submission_final[['Q1', 'Q2', 'Q3', 'S1', 'S2', 'S3']].apply(len)
      a22 = submission_final[['Q1', 'Q2', 'Q3', 'S1', 'S2', 'S3']].mean()
      result = pd.concat([a11, a13, a12, a21, a23, a22], axis=1)
      result.columns = ['학습sum','학습len','학습mean','테스트sum','테스트len','테스트mean']
      print('\n 예측결과 비교표')
      display(result)

      # ========================================= OOF 예측 생성 (train set에 대해) =========================================

      if get_oof==True:

        mask = train['month'] != 6
        print(f'# k-fold: {n_splits}')
        print(f'# train: {len(y[mask])}')

        oof_f1 = []
        print('# OOF 예측 생성')
        oof_result = train_df[['subject_id', 'sleep_date', 'lifelog_date']].copy()
        for col in targets_binary:

            lgb_params = lgb_param_dict[col].copy()
            lgb_params['random_state'] = random_state

            xgb_params = xgb_param_dict[col].copy()
            xgb_params['random_state'] = random_state

            y = train_df[col]

            oof_preds = get_oof_predictions(
                X[[i for i in X.columns.tolist() if i in top_features_dict[col]]], y,
                lgb_params, xgb_params,
                meta_weights[col],
                n_splits=n_splits,
                is_multiclass=False
            )

            oof_result[col] = oof_preds
            f1 = f1_score(y[mask], oof_preds[mask], average='macro')
            oof_f1.append(f1)

        # multiclass

        lgb_params = lgb_param_dict['S1'].copy()
        lgb_params['random_state'] = random_state

        xgb_params = xgb_param_dict['S1'].copy()
        xgb_params['random_state'] = random_state

        y = train_df['S1']

        oof_preds = get_oof_predictions(
            X[[i for i in X.columns.tolist() if i in top_features_dict['S1']]], y,
            lgb_params, xgb_params,
            meta_weights['S1'],
            n_splits=n_splits,
            is_multiclass=True,
            num_class=3
        )

        oof_result['S1'] = oof_preds
        f1 = f1_score(y[mask], oof_preds[mask], average='macro')
        oof_f1.append(f1)
        oof_avg_f1 = np.mean(oof_f1)

        # 로그
        detail = " ".join([f"{name}({tname}):{score:.4f}" for name, tname, score in zip(targets_binary + ['S1'], targets_binary_name + ['수면시간'], oof_f1)])
        print(f"#  oof F1: {oof_avg_f1:.4f} / [상세] {detail}")

        # oof_result 저장
        fname = f"oof_result_{np.mean(total_avg_f1s)}.csv"
        oof_result.to_csv(fname, index=False)
        print(f"# {fname} 저장 완료")

    return submission_final, submission_valid, val_f1

### main

In [ ]:
%%time

# CPU times: user 3h 59min 49s, sys: 26min 28s, total: 4h 26min 18s
# Wall time: 37min 46s

def trial(x):

  #==== high score ================================================
  lgb_params = {
    'n_estimators': 5000, # 5000
    "learning_rate": 0.01, # 0.01
    'lambda_l1': 5, # 5
    'lambda_l2': 1, # 1
    'bagging_fraction': 0.8, # 0.8
    'feature_fraction': 1,
    'n_jobs': -1,
    'verbosity': -1
  }
  lgb_param_dict = {}
  lgb_param_dict['Q1'] = lgb_params.copy()
  lgb_param_dict['Q2'] = lgb_params.copy()
  lgb_param_dict['S2'] = lgb_params.copy()

  lgb_params2 = {
    'boosting_type':'dart',
    'drop_rate': 0.1,
    'skip_drop': 0.6,
    'max_drop': 20,
    # --------------------------
    'min_data_in_leaf': 25,
    'n_estimators': 2000, # 5000
    "learning_rate": 0.01, # 0.01
    'lambda_l1': 5, # 5
    'lambda_l2': 1, # 1
    'bagging_fraction': 0.8, # 0.8
    'feature_fraction': 1,
    'n_jobs': -1,
    'verbosity': -1
  }
  lgb_param_dict['Q3'] = lgb_params2.copy()
  lgb_param_dict['Q3']['max_depth'] = 3

  lgb_param_dict['S3'] = lgb_params2.copy()
  lgb_param_dict['S3']['skip_drop'] = 0.6

  #================================================================
  lgb_params3 = {
    'n_estimators': 5000, # 5000
    "learning_rate": 0.01, # 0.01
    'lambda_l1': 2, # 5
    'lambda_l2': 1, # 1
    'bagging_fraction': 0.8, # 0.8
    'feature_fraction': 0.9,
    'n_jobs': -1,
    'verbosity': -1
  }
  lgb_param_dict['S1'] = lgb_params3.copy()
  lgb_param_dict['S1']['skip_drop'] = 0.6

  #================================================================
  xgb_params = {
    'n_estimators': 1000,  # 1000
    'learning_rate': 0.01, # 0.01
    'reg_lambda': 1,
    'max_depth': 6,
    'min_child_weight': 10, # 10
    'subsample': 0.8 , # 0.8
    'colsample_bytree': 0.8 # 0.8
  }
  xgb_param_dict = {}
  xgb_param_dict['Q1'] = xgb_params.copy()
  xgb_param_dict['Q2'] = xgb_params.copy()
  xgb_param_dict['Q2']['subsample'] = 0.9
  xgb_param_dict['Q2']['reg_lambda'] = 2
  xgb_param_dict['Q3'] = xgb_params.copy()
  xgb_param_dict['Q3']['subsample'] = 0.9
  xgb_param_dict['S1'] = xgb_params.copy()
  xgb_param_dict['S1']['subsample'] = 1
  xgb_param_dict['S1']['colsample_bytree'] = 0.7
  xgb_param_dict['S2'] = xgb_params.copy()
  xgb_param_dict['S3'] = xgb_params.copy()

  drop_features2 = [
    'light_week_type_lag1',
    'activehour_top_bssid',
    'beforebed_top_bssid',
    'week_type','week_type_lag1',
    'light_week_type_lag1','pk'
  ]
  selected_features = [i for i in train.columns if i not in drop_features2]

  meta_weights = {}
  meta_weights['Q1'] = {'lgb': 0.4, 'xgb': 0.6}
  meta_weights['Q2'] = {'lgb': 0.7, 'xgb': 0.3}
  meta_weights['Q3'] = {'lgb': 0.3, 'xgb': 0.7}
  meta_weights['S2'] = {'lgb': 0.3, 'xgb': 0.7}
  meta_weights['S3'] = {'lgb': 0.6, 'xgb': 0.4}
  meta_weights['S1'] = {'lgb': 0.4, 'xgb': 0.6}

  """
  [reference]
  평균 F1: 0.6463 / [상세] Q1(기상직후수면질):0.7229 Q2(취침전신체적피로):0.7278 Q3(취침전스트레스):0.6769 S2(수면효율):0.5957 S3(수면잠들기시간):0.6854 S1(S1):0.4691
  # 전체 평균 F1: 0.6463
  # [OOF] F1 score: 0.6611

  # 평균 F1: 0.6841 / [상세] Q1(기상직후수면질):0.7496 Q2(취침전신체적피로):0.7697 Q3(취침전스트레스):0.6745 S2(수면효율):0.7086 S3(수면잠들기시간):0.6870 S1(수면시간):0.5148
  #  oof F1: 0.6755 / [상세] Q1(기상직후수면질):0.7372 Q2(취침전신체적피로):0.6899 Q3(취침전스트레스):0.6630 S2(수면효율):0.6811 S3(수면잠들기시간):0.7274 S1(수면시간):0.5541
  # public : 0.6236401

  # 평균 F1: 0.6909 / [상세] Q1(기상직후수면질):0.7496 Q2(취침전신체적피로):0.7882 Q3(취침전스트레스):0.6785 S2(수면효율):0.7086 S3(수면잠들기시간):0.6870 S1(수면시간):0.5333
  #  oof F1: 0.6719 / [상세] Q1(기상직후수면질):0.7372 Q2(취침전신체적피로):0.6860 Q3(취침전스트레스):0.6638 S2(수면효율):0.6811 S3(수면잠들기시간):0.7274 S1(수면시간):0.5361
  """

  best_topn =  {'Q1': 277, 'Q2': 140, 'Q3': 277, 'S2': 140, 'S3': 50, 'S1':90} # 0.6755

  submission_final, submission_valid, f1 = run_basemodel(
      train[selected_features], test[selected_features], valid_ids,
      lgb_param_dict, xgb_param_dict,
      meta_weights,
      best_topn,
      vi=False, n_splits=5, random_state=41, submit=False, get_oof=False, threshold=0.95
  )

  return f1

CPU times: user 0 ns, sys: 4 µs, total: 4 µs
Wall time: 8.11 µs

In [ ]:
# 평균 F1: 0.6315 / [상세] Q1():0.6647 Q2(*):0.7867 Q3():0.5636 S2():0.5683 S3(*):0.7234 S1():0.4823 -> 0.63100
# 평균 F1: 0.6242 / [상세] Q1():0.7030 Q2(*):0.7395 Q3():0.6085 S2():0.5639 S3(*):0.6769 S1():0.4531 -> 0.63104
# --------------------------------------------------------------------------------------------------------------
# 평균 F1: 0.6923 / [상세] Q1():0.7496 Q2():0.7882 Q3():0.6870 S2():0.7086 S3():0.6870 S1():0.5333
#  oof F1: 0.6719 / [상세] Q1():0.7372 Q2():0.6860 Q3():0.6638 S2():0.6811 S3():0.7274 S1():0.5361

opts = [2,3,5,10,15,20,25,30,35,40,50,70,100]
opts = [0.01,0.02,0.005,0.007,0.1,0.2,0.5,0.7,0.05,0.07]
opts = [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1]
opts = [1,2,3,4,5,6,7,8,9,10,15,20]

rst = {}
for x in opts:
  print(f'\n # : {x}')
  f1 = trial(x)
  rst[x] = f1

 # : 1

KeyboardInterrupt:

In [ ]:
pd.DataFrame(rst).T

### 최종모델

In [ ]:
#==== high score ================================================
lgb_params = {
  'n_estimators': 5000, # 5000
  "learning_rate": 0.01, # 0.01
  'lambda_l1': 5, # 5
  'lambda_l2': 1, # 1
  'bagging_fraction': 0.8, # 0.8
  'feature_fraction': 1,
  'n_jobs': -1,
  'verbosity': -1
}
lgb_param_dict = {}
lgb_param_dict['Q1'] = lgb_params.copy()
lgb_param_dict['Q2'] = lgb_params.copy()
lgb_param_dict['S2'] = lgb_params.copy()

lgb_params2 = {
  'boosting_type':'dart',
  'drop_rate': 0.1,
  'skip_drop': 0.6,
  'max_drop': 20,
  # --------------------------
  'min_data_in_leaf': 25,
  'n_estimators': 2000, # 5000
  "learning_rate": 0.01, # 0.01
  'lambda_l1': 5, # 5
  'lambda_l2': 1, # 1
  'bagging_fraction': 0.8, # 0.8
  'feature_fraction': 1,
  'n_jobs': -1,
  'verbosity': -1
}
lgb_param_dict['Q3'] = lgb_params2.copy()
lgb_param_dict['Q3']['max_depth'] = 3

lgb_param_dict['S3'] = lgb_params2.copy()
lgb_param_dict['S3']['skip_drop'] = 0.6

#================================================================
lgb_params3 = {
  'n_estimators': 5000, # 5000
  "learning_rate": 0.01, # 0.01
  'lambda_l1': 2, # 5
  'lambda_l2': 1, # 1
  'bagging_fraction': 0.8, # 0.8
  'feature_fraction': 0.9,
  'n_jobs': -1,
  'verbosity': -1
}
lgb_param_dict['S1'] = lgb_params3.copy()
lgb_param_dict['S1']['skip_drop'] = 0.6

#================================================================
#================================================================
xgb_params = {
  'n_estimators': 1000,  # 1000
  'learning_rate': 0.01, # 0.01
  'reg_lambda': 1,
  'max_depth': 6,
  'min_child_weight': 10, # 10
  'subsample': 0.8 , # 0.8
  'colsample_bytree': 0.8 # 0.8
}
xgb_param_dict = {}
xgb_param_dict['Q1'] = xgb_params.copy()
xgb_param_dict['Q2'] = xgb_params.copy()
xgb_param_dict['Q2']['subsample'] = 0.9
xgb_param_dict['Q2']['reg_lambda'] = 2
xgb_param_dict['Q3'] = xgb_params.copy()
xgb_param_dict['Q3']['subsample'] = 0.9
xgb_param_dict['S1'] = xgb_params.copy()
xgb_param_dict['S1']['subsample'] = 1
xgb_param_dict['S1']['colsample_bytree'] = 0.7
xgb_param_dict['S2'] = xgb_params.copy()
xgb_param_dict['S3'] = xgb_params.copy()

drop_features2 = [
  'light_week_type_lag1',
  'activehour_top_bssid',
  'beforebed_top_bssid',
  'week_type','week_type_lag1',
  'light_week_type_lag1','pk'
]
selected_features = [i for i in train.columns if i not in drop_features2]

meta_weights = {}
meta_weights['Q1'] = {'lgb': 0.4, 'xgb': 0.6}
meta_weights['Q2'] = {'lgb': 0.7, 'xgb': 0.3}
meta_weights['Q3'] = {'lgb': 0.3, 'xgb': 0.7}
meta_weights['S2'] = {'lgb': 0.3, 'xgb': 0.7}
meta_weights['S3'] = {'lgb': 0.6, 'xgb': 0.4}
meta_weights['S1'] = {'lgb': 0.4, 'xgb': 0.6}

"""
[reference]
평균 F1: 0.6463 / [상세] Q1(기상직후수면질):0.7229 Q2(취침전신체적피로):0.7278 Q3(취침전스트레스):0.6769 S2(수면효율):0.5957 S3(수면잠들기시간):0.6854 S1(S1):0.4691
# 전체 평균 F1: 0.6463
# [OOF] F1 score: 0.6611

# 평균 F1: 0.6841 / [상세] Q1(기상직후수면질):0.7496 Q2(취침전신체적피로):0.7697 Q3(취침전스트레스):0.6745 S2(수면효율):0.7086 S3(수면잠들기시간):0.6870 S1(수면시간):0.5148
#  oof F1: 0.6755 / [상세] Q1(기상직후수면질):0.7372 Q2(취침전신체적피로):0.6899 Q3(취침전스트레스):0.6630 S2(수면효율):0.6811 S3(수면잠들기시간):0.7274 S1(수면시간):0.5541
# public : 0.6236401

# 평균 F1: 0.6909 / [상세] Q1(기상직후수면질):0.7496 Q2(취침전신체적피로):0.7882 Q3(취침전스트레스):0.6785 S2(수면효율):0.7086 S3(수면잠들기시간):0.6870 S1(수면시간):0.5333
#  oof F1: 0.6719 / [상세] Q1(기상직후수면질):0.7372 Q2(취침전신체적피로):0.6860 Q3(취침전스트레스):0.6638 S2(수면효율):0.6811 S3(수면잠들기시간):0.7274 S1(수면시간):0.5361

# 평균 F1: 0.7005 / [상세] Q1(기상직후수면질):0.7496 Q2(취침전신체적피로):0.7882 Q3(취침전스트레스):0.6955 S2(수면효율):0.7086 S3(수면잠들기시간):0.6955 S1(수면시간):0.5657
#  oof F1: 0.6722 / [상세] Q1(기상직후수면질):0.7372 Q2(취침전신체적피로):0.6860 Q3(취침전스트레스):0.6770 S2(수면효율):0.6811 S3(수면잠들기시간):0.7083 S1(수면시간):0.5436

# 평균 F1: 0.6849 / [상세] Q1(기상직후수면질):0.7496 Q2(취침전신체적피로):0.7882 Q3(취침전스트레스):0.6578 S2(수면효율):0.7086 S3(수면잠들기시간):0.6870 S1(수면시간):0.5179
#  oof F1: 0.6706 / [상세] Q1(기상직후수면질):0.7372 Q2(취침전신체적피로):0.6860 Q3(취침전스트레스):0.6770 S2(수면효율):0.6811 S3(수면잠들기시간):0.7083 S1(수면시간):0.5339

# 평균 F1: 0.6529 / [상세] Q1(기상직후수면질):0.7021 Q2(취침전신체적피로):0.7154 Q3(취침전스트레스):0.6163 S2(수면효율):0.6654 S3(수면잠들기시간):0.6603 S1(수면시간):0.5577
#  oof F1: 0.6662 / [상세] Q1(기상직후수면질):0.6886 Q2(취침전신체적피로):0.6838 Q3(취침전스트레스):0.6779 S2(수면효율):0.6732 S3(수면잠들기시간):0.7171 S1(수면시간):0.5569
"""

best_topn =  {'Q1': 277, 'Q2': 140, 'Q3': 277, 'S2': 140, 'S3': 50, 'S1':90} # 0.6755

submission_final, submission_valid, f1 = run_basemodel(
    train[selected_features], test[selected_features], valid_ids,
    lgb_param_dict, xgb_param_dict,
    meta_weights,
    best_topn,
    vi=True, n_splits=5, random_state=41, submit=True, get_oof=True
)

[LGB][Q1] beforebed_통화&전화_앱이용시간(2269), Q1_te2(420), wake_time_ratio(414), Q1_te(198), mlight_first_wakeup_minutes(133), active_hour_std_light(130), active_hour_mean_light(121), sleep_duration_min(121), light_wake_time_ratio(109), wake_time_diff(104)
[XGB][Q1] Q1_te(0), Q1_te2(0), light_rolling_sleep_duration_3d(0), wake_time_ratio(0), beforebed_scan_count(0), sleep_duration_min_min(0), wake_time_diff(0), beforebed_통화&전화_앱이용시간(0), sleep_duration_min(0), light_sleep_duration_vs_weekday_avg(0)
[LGB][Q2] m_activity@240min@std@04h00m(1770), rolling_wake_time_3d(276), Q2_te2(251), active_hour_walk_minutes(226), Q2_te(180), active_hour_std_hr(177), beforebed_unique_bssid_count(158), active_hour_vehicle_minutes(152), Q3_te2(141), mlight_first_sleep_minutes(134)
[XGB][Q2] Q2_te(0), Q2_te2(0), m_activity_0@240min@std@04h00m(0), beforebed_이용앱개수(0), m_activity_met@240min@std@04h00m(0), activity_minutes(0), S1_te2(0), m_activity_0@240min@sum@16h00m(0), active_hour_max_speed(0), m_activity@240min@std@16h00m(0)
[LGB][Q3] Q3_te2(1854), sleep_duration_lag2(632), light_weekday(536), m_activity_met@240min@sum@04h00m(359), 추정수면효율(333), light_max(307), light_sleep_time_diff_lag2(299), wake_time_ratio(298), beforebed_핸드폰사용시간(288), walking_minutes(270)
[XGB][Q3] work_hour_others_ratio(0), Q3_te2(0), Q3_te(0), sleep_hour_others_ratio(0), beforebed_hour_span_minutes(0), sleep_duration_interp_mLight(0), sleep_duration_min_m_light_sleep_duration_min(0), sleep_hour_rssi_max(0), mlight_first_sleep_minutes(0), sleep_hour_unknown_ratio(0)
[LGB][S2] S2_te2(324), work_hour_unknown_ratio(228), S2_te(210), m_activity_0@240min@std@08h00m(197), sleep_duration_lag2(196), img1(186), beforebed_max_rssi(160), sleep_time_lag2(156), light_wake_time_diff_lag2(146), sleep_hour_mean_speed(136)
[XGB][S2] S2_te2(0), activehour_min_rssi(0), S2_te(0), max_charging_duration(0), beforebed_이용앱개수(0), S1_te2(0), sleep_hour_mean_speed(0), m_activity_met@240min@std@12h00m(0), activehour_scan_count(0), S3_te(0)
[LGB][S3] S3_te2(1332), rolling_sleep_duration_3d(1156), light_night_mean(1093), img3(1008), S3_te(956), active_hour_high_hr(739), activehour_max_rssi(615), sleep_duration_min(505), light_wake_time_diff_lag2(495), Q1_te2(385)
[XGB][S3] S3_te2(0), S3_te(0), activehour_max_rssi(0), light_night_mean(0), S2_te(0), img3(0), S2_te2(0), sleep_duration_min(0), weekend3(0), wake_time_min(0)
[LGB][S1] S1_te2(854), beforebed_핸드폰사용시간(815), activehour_scan_count(720), S1_te(676), sleep_duration_vs_weekday_avg(666), activehour_strong_signal_ratio(652), rolling_sleep_time_2d(634), activehour_top_bssid_count(599), light_wake_time_lag2(526), img2(503)
[XGB][S1] S1_te(0), S1_te2(0), sleep_time(0), light_rolling_sleep_duration_2d(0), sleep_duration_min_max(0), m_light_awake_minutes(0), sleep_duration_min(0), sleep_duration_ratio(0), rolling_sleep_time_2d(0), weekday_avg_sleep(0)
# 평균 F1: 0.6529 / [상세] Q1(기상직후수면질):0.7021 Q2(취침전신체적피로):0.7154 Q3(취침전스트레스):0.6163 S2(수면효율):0.6654 S3(수면잠들기시간):0.6603 S1(수면시간):0.5577

    train  valid
S1
1  0.4978 0.5714
0  0.3178 0.2952
2  0.1844 0.1333

            total_samples  error_count  error_rate
subject_id
id09                   14           10      0.7143
id05                    7            4      0.5714
id10                    7            3      0.4286
id01                   14            6      0.4286
id08                    7            3      0.4286
id04                   14            6      0.4286
id07                   14            5      0.3571
id02                   14            4      0.2857
id06                    7            2      0.2857
id03                    7            2      0.2857

# submission_0.6528698289109692.csv 저장 완료
# submission shape:(250, 9)

 예측결과 비교표

    학습sum  학습len  학습mean  테스트sum  테스트len  테스트mean
Q1    223    450  0.4956     132     250   0.5280
Q2    253    450  0.5622     143     250   0.5720
Q3    270    450  0.6000     178     250   0.7120
S1    390    450  0.8667     192     250   0.7680
S2    293    450  0.6511     159     250   0.6360
S3    298    450  0.6622     176     250   0.7040

# k-fold: 5
# train: 392
# OOF 예측 생성
#  oof F1: 0.6662 / [상세] Q1(기상직후수면질):0.6886 Q2(취침전신체적피로):0.6838 Q3(취침전스트레스):0.6779 S2(수면효율):0.6732 S3(수면잠들기시간):0.7171 S1(수면시간):0.5569
# oof_result_0.6528698289109692.csv 저장 완료

In [ ]:
# 평균 F1: 0.6315 / [상세] Q1():0.6647 Q2():0.7867 Q3():0.5636 S2():0.5683 S3():0.7234 S1():0.4823 -> 0.63100
# 평균 F1: 0.6242 / [상세] Q1():0.7030 Q2():0.7395 Q3():0.6085 S2():0.5639 S3():0.6769 S1():0.4531 -> 0.63104
# -------------------------------------------------------------------------------------------------------------
# 평균 F1: 0.6735 / [상세] Q1():0.7304 Q2():0.7689 Q3():0.6661 S2():0.6686 S3():0.6738 S1():0.5333

### post_processing
- 평균 F1: 0.7005 / [상세] Q1(기상직후수면질):0.7496 Q2(취침전신체적피로):0.7882 Q3(취침전스트레스):0.6955 S2(수면효율):0.7086 S3(수면잠들기시간):0.6955 S1(수면시간):0.5657

In [ ]:
# 평균 F1: 0.7005 / [상세] Q1(기상직후수면질):0.7496 Q2(취침전신체적피로):0.7882 Q3(취침전스트레스):0.6955 S2(수면효율):0.7086 S3(수면잠들기시간):0.6955 S1(수면시간):0.5657
def post_processing(df):
  df = df.reset_index(drop=True).copy()
  s1_2_mask = df['S1'] == 2
  df.loc[s1_2_mask, ['Q1', 'Q3', 'S2']] = 1
  df.loc[s1_2_mask, ['Q2', 'S3']] = 0
  return df

submission_valid2 = post_processing(submission_valid)
train['pk'] = train['subject_id']+train['sleep_date']

llm_eval = {}
for col in ['Q1','Q2','Q3','S1','S2','S3']:
  real_y = train.loc[train['pk'].isin(valid_ids['pk']),col].values
  pred_y = submission_valid2[col]
  llm_eval[col] = f1_score(real_y, pred_y, average='macro')

llm_eval

{'Q1': 0.7394540942928041,
 'Q2': 0.7047619047619048,
 'Q3': 0.6955304469553045,
 'S1': 0.5656614577421267,
 'S2': 0.6955260977630489,
 'S3': 0.6411483253588517}

### ===================

### 📌 실험1: 앙상블 가중치

In [ ]:
import itertools

values = [i for i in range(1, 11)]  # 0.1 ~ 1.0 → 1 ~ 10
모든가능한조합 = []

for a, b in itertools.product(values, repeat=2):
    if a + b == 10 and a != b:
        모든가능한조합.append((a / 10, b / 10))

# 결과 출력
print(f"총 경우의 수: {len(모든가능한조합)}")

총 경우의 수: 8

In [ ]:
%%time

# CPU times: user 3h 59min 49s, sys: 26min 28s, total: 4h 26min 18s
# Wall time: 37min 46s

#==== high score ================================================
lgb_params = {
  'n_estimators': 5000, # 5000
  "learning_rate": 0.01, # 0.01
  'lambda_l1': 5, # 5
  'lambda_l2': 1, # 1
  'bagging_fraction': 0.8, # 0.8
  'feature_fraction': 1,
  'n_jobs': -1,
  'verbosity': -1
}
lgb_param_dict = {}
lgb_param_dict['Q1'] = lgb_params.copy()
lgb_param_dict['Q2'] = lgb_params.copy()
lgb_param_dict['S2'] = lgb_params.copy()

lgb_params2 = {
  'boosting_type':'dart',
  'drop_rate': 0.1,
  'skip_drop': 0.6,
  'max_drop': 20,
  # --------------------------
  'min_data_in_leaf': 25,
  'n_estimators': 2000, # 5000
  "learning_rate": 0.01, # 0.01
  'lambda_l1': 5, # 5
  'lambda_l2': 1, # 1
  'bagging_fraction': 0.8, # 0.8
  'feature_fraction': 1,
  'n_jobs': -1,
  'verbosity': -1
}
lgb_param_dict['Q3'] = lgb_params2.copy()
lgb_param_dict['Q3']['max_depth'] = 3

lgb_param_dict['S3'] = lgb_params2.copy()
lgb_param_dict['S3']['skip_drop'] = 0.6

#================================================================
lgb_params3 = {
  'n_estimators': 5000, # 5000
  "learning_rate": 0.01, # 0.01
  'lambda_l1': 2, # 5
  'lambda_l2': 1, # 1
  'bagging_fraction': 0.8, # 0.8
  'feature_fraction': 0.9,
  'n_jobs': -1,
  'verbosity': -1
}
lgb_param_dict['S1'] = lgb_params3.copy()
lgb_param_dict['S1']['skip_drop'] = 0.6

#================================================================
#================================================================
xgb_params = {
  'n_estimators': 1000,  # 1000
  'learning_rate': 0.01, # 0.01
  'reg_lambda': 1,
  'max_depth': 6,
  'min_child_weight': 10, # 10
  'subsample': 0.8 , # 0.8
  'colsample_bytree': 0.8 # 0.8
}
xgb_param_dict = {}
xgb_param_dict['Q1'] = xgb_params.copy()
xgb_param_dict['Q2'] = xgb_params.copy()
xgb_param_dict['Q2']['subsample'] = 0.9
xgb_param_dict['Q2']['reg_lambda'] = 2
xgb_param_dict['Q3'] = xgb_params.copy()
xgb_param_dict['Q3']['subsample'] = 0.9
xgb_param_dict['S1'] = xgb_params.copy()
xgb_param_dict['S1']['subsample'] = 1
xgb_param_dict['S1']['colsample_bytree'] = 0.7
xgb_param_dict['S2'] = xgb_params.copy()
xgb_param_dict['S3'] = xgb_params.copy()

best_topn =  {'Q1': 277, 'Q2': 140, 'Q3': 277, 'S2': 140, 'S3': 50, 'S1':90} # 0.6755

rst1 = {}
for j in 모든가능한조합:

    key = ('lgb', j[0]), ('xgb', j[1])
    print({'lgb': j[0], 'xgb': j[1]})
    meta_weights['Q1'] = {'lgb': j[0], 'xgb': j[1]}
    meta_weights['Q2'] = {'lgb': j[0], 'xgb': j[1]}
    meta_weights['Q3'] = {'lgb': j[0], 'xgb': j[1]}
    meta_weights['S1'] = {'lgb': j[0], 'xgb': j[1]}
    meta_weights['S2'] = {'lgb': j[0], 'xgb': j[1]}
    meta_weights['S3'] = {'lgb': j[0], 'xgb': j[1]}

    submission_final, submission_valid, f1 = run_basemodel(
        train[selected_features], test[selected_features], valid_ids,
        lgb_param_dict, xgb_param_dict,
        meta_weights,
        best_topn,
        vi=False, n_splits=5, random_state=41, submit=False, get_oof=False
    )
    rst1[key] = f1

{'lgb': 0.1, 'xgb': 0.9}
# 평균 F1: 0.6430 / [상세] Q1(기상직후수면질):0.6930 Q2(취침전신체적피로):0.7083 Q3(취침전스트레스):0.6082 S2(수면효율):0.6603 S3(수면잠들기시간):0.6520 S1(수면시간):0.5363

    train  valid
S1
1  0.4978 0.5810
0  0.3178 0.2762
2  0.1844 0.1429

            total_samples  error_count  error_rate
subject_id
id09                   14           10      0.7143
id05                    7            4      0.5714
id10                    7            4      0.5714
id04                   14            7      0.5000
id08                    7            3      0.4286
id01                   14            6      0.4286
id07                   14            5      0.3571
id02                   14            4      0.2857
id06                    7            2      0.2857
id03                    7            2      0.2857

{'lgb': 0.2, 'xgb': 0.8}
# 평균 F1: 0.6432 / [상세] Q1(기상직후수면질):0.7021 Q2(취침전신체적피로):0.7083 Q3(취침전스트레스):0.6082 S2(수면효율):0.6520 S3(수면잠들기시간):0.6520 S1(수면시간):0.5363

    train  valid
S1
1  0.4978 0.5810
0  0.3178 0.2762
2  0.1844 0.1429

            total_samples  error_count  error_rate
subject_id
id09                   14           10      0.7143
id05                    7            4      0.5714
id10                    7            4      0.5714
id04                   14            7      0.5000
id08                    7            3      0.4286
id01                   14            6      0.4286
id07                   14            5      0.3571
id02                   14            4      0.2857
id06                    7            2      0.2857
id03                    7            2      0.2857

{'lgb': 0.3, 'xgb': 0.7}
# 평균 F1: 0.6481 / [상세] Q1(기상직후수면질):0.7021 Q2(취침전신체적피로):0.6977 Q3(취침전스트레스):0.6163 S2(수면효율):0.6654 S3(수면잠들기시간):0.6520 S1(수면시간):0.5552

    train  valid
S1
1  0.4978 0.5619
0  0.3178 0.2952
2  0.1844 0.1429

            total_samples  error_count  error_rate
subject_id
id09                   14           10      0.7143
id05                    7            4      0.5714
id10                    7            3      0.4286
id01                   14            6      0.4286
id08                    7            3      0.4286
id04                   14            6      0.4286
id07                   14            5      0.3571
id02                   14            4      0.2857
id06                    7            2      0.2857
id03                    7            2      0.2857

{'lgb': 0.4, 'xgb': 0.6}
# 평균 F1: 0.6499 / [상세] Q1(기상직후수면질):0.7021 Q2(취침전신체적피로):0.6977 Q3(취침전스트레스):0.6163 S2(수면효율):0.6738 S3(수면잠들기시간):0.6520 S1(수면시간):0.5577

    train  valid
S1
1  0.4978 0.5714
0  0.3178 0.2952
2  0.1844 0.1333

            total_samples  error_count  error_rate
subject_id
id09                   14           10      0.7143
id05                    7            4      0.5714
id10                    7            3      0.4286
id01                   14            6      0.4286
id08                    7            3      0.4286
id04                   14            6      0.4286
id07                   14            5      0.3571
id02                   14            4      0.2857
id06                    7            2      0.2857
id03                    7            2      0.2857

{'lgb': 0.6, 'xgb': 0.4}
# 평균 F1: 0.6420 / [상세] Q1(기상직후수면질):0.6930 Q2(취침전신체적피로):0.6870 Q3(취침전스트레스):0.6163 S2(수면효율):0.6465 S3(수면잠들기시간):0.6603 S1(수면시간):0.5488

    train  valid
S1
1  0.4978 0.5619
0  0.3178 0.2952
2  0.1844 0.1429

            total_samples  error_count  error_rate
subject_id
id09                   14           10      0.7143
id05                    7            4      0.5714
id01                   14            7      0.5000
id10                    7            3      0.4286
id08                    7            3      0.4286
id04                   14            6      0.4286
id02                   14            5      0.3571
id07                   14            5      0.3571
id03                    7            2      0.2857
id06                    7            1      0.1429

{'lgb': 0.7, 'xgb': 0.3}
# 평균 F1: 0.6337 / [상세] Q1(기상직후수면질):0.6828 Q2(취침전신체적피로):0.7154 Q3(취침전스트레스):0.6035 S2(수면효율):0.6101 S3(수면잠들기시간):0.6603 S1(수면시간):0.5300

    train  valid
S1
1  0.4978 0.5810
0  0.3178 0.2762
2  0.1844 0.1429

            total_samples  error_count  error_rate
subject_id
id09                   14           11      0.7857
id05                    7            4      0.5714
id01                   14            7      0.5000
id08                    7            3      0.4286
id07                   14            6      0.4286
id04                   14            6      0.4286
id10                    7            3      0.4286
id02                   14            5      0.3571
id03                    7            2      0.2857
id06                    7            1      0.1429

{'lgb': 0.8, 'xgb': 0.2}
# 평균 F1: 0.6327 / [상세] Q1(기상직후수면질):0.6738 Q2(취침전신체적피로):0.7134 Q3(취침전스트레스):0.6035 S2(수면효율):0.6023 S3(수면잠들기시간):0.6738 S1(수면시간):0.5294

    train  valid
S1
1  0.4978 0.5714
0  0.3178 0.2857
2  0.1844 0.1429

            total_samples  error_count  error_rate
subject_id
id09                   14           11      0.7857
id05                    7            4      0.5714
id01                   14            7      0.5000
id08                    7            3      0.4286
id07                   14            6      0.4286
id04                   14            6      0.4286
id10                    7            3      0.4286
id02                   14            5      0.3571
id03                    7            2      0.2857
id06                    7            1      0.1429

{'lgb': 0.9, 'xgb': 0.1}
# 평균 F1: 0.6383 / [상세] Q1(기상직후수면질):0.6738 Q2(취침전신체적피로):0.7332 Q3(취침전스트레스):0.6035 S2(수면효율):0.6101 S3(수면잠들기시간):0.6870 S1(수면시간):0.5225

    train  valid
S1
1  0.4978 0.5619
0  0.3178 0.2952
2  0.1844 0.1429

            total_samples  error_count  error_rate
subject_id
id09                   14           12      0.8571
id05                    7            4      0.5714
id01                   14            7      0.5000
id08                    7            3      0.4286
id07                   14            6      0.4286
id04                   14            6      0.4286
id10                    7            3      0.4286
id02                   14            5      0.3571
id03                    7            2      0.2857
id06                    7            1      0.1429

CPU times: user 21min 25s, sys: 4.03 s, total: 21min 29s
Wall time: 3min

### 📌 실험2 : 튜닝

In [ ]:
%%time

# 200번 - 1hours

import random
from itertools import product

def generate_random_param_grid(common_params, n_trials=50, seed=42):
    random.seed(seed)

    # 범위 조건에 맞는 값 리스트 생성
    feature_fraction = [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1]  # 0.65 ~ 1.00
    learning_rate = [0.005,0.01,0.02,0.05,0.1,0.5] # 0.005 ~ 0.1
    lambda_l1 = [1,2,3,5,10,15,20,30]  # 1 ~ 10

    # 모든 조합 생성
    all_combinations = list(product(feature_fraction, learning_rate, lambda_l1))

    # 중복 없이 n_trials 개수만 샘플링
    sampled_combinations = random.sample(all_combinations, k=min(n_trials, len(all_combinations)))

    # 파라미터 dict 리스트로 반환
    param_grid = []
    for feature_fraction, learning_rate, lambda_l1 in sampled_combinations:
        params = common_params.copy()
        params['feature_fraction'] = feature_fraction
        params['learning_rate'] = learning_rate
        params['lambda_l1'] = lambda_l1
        param_grid.append(params)

    return param_grid


# ===============
n_trials = 30 #
# ===============

# 평균 F1: 0.6610 / [상세] Q1(기상직후수면질):0.7395 Q2(취침전신체적피로):0.7222 Q3(취침전스트레스):0.6535 S2(수면효율):0.6786 S3(수면잠들기시간):0.6738 S1(수면시간):0.4982
#  oof F1: 0.6677 / [상세] Q1(기상직후수면질):0.7270 Q2(취침전신체적피로):0.6776 Q3(취침전스트레스):0.6653 S2(수면효율):0.6685 S3(수면잠들기시간):0.7129 S1(수면시간):0.5550

drop_features2 = [
  'light_week_type_lag1',
  'activehour_top_bssid',
  'beforebed_top_bssid',
  'week_type','week_type_lag1','light_week_type_lag1',
]
selected_features = [i for i in train.columns if i not in drop_features2]
meta_weights = {'lgb': 0.3, 'xgb': 0.7, 'cat':0} ##  0.6625, oof 0.6687

trial_params = generate_random_param_grid(common_params, n_trials)

rst1 = {}
for i, trial_param in tqdm(enumerate(trial_params), total=len(trial_params), desc="Grid Search"):

  best_param_dict['Q1'] = trial_param.copy()
  best_param_dict['Q2'] = trial_param.copy()
  best_param_dict['Q3'] = trial_param.copy()

  best_param_dict['S1'] = trial_param.copy()
  best_param_dict['S2'] = trial_param.copy()
  best_param_dict['S3'] = trial_param.copy()

  # check
  display(pd.DataFrame(best_param_dict).T[['learning_rate','feature_fraction','lambda_l2']].drop_duplicates())

  submission_final, f1 = run_basemodel(
      train[selected_features], test[selected_features], valid_ids,
      best_param_dict,
      meta_weights,
      n_splits=5, random_state=41, submit=False, get_oof=False
  )
  rst1[i] = (best_param_dict, f1)

### 📌 실험3 : post processing

In [ ]:
def calculate_llm_changes(valid_df, llm_df, target_cols=['Q1','Q2','Q3','S1','S2','S3']):

    # PK 기준으로 inner merge
    merged = pd.merge(valid_df, llm_df, on='pk', suffixes=('_valid', '_llm'))

    # 변경 통계 계산
    change_stats = {}
    total_changes = 0

    for col in target_cols:
        change_count = (merged[f'{col}_valid'] != merged[f'{col}_llm']).sum()
        change_stats[col] = change_count
        total_changes += change_count

    # 결과 요약
    change_stats['Total Changes'] = total_changes
    change_stats['Total Rows'] = len(merged)
    change_stats['Change Rate (%)'] = f"{total_changes/len(merged)*100:.2f}%"

    # 디스플레이용 DataFrame 생성
    change_df = pd.DataFrame({
        'Target': target_cols,
        'Changes': [change_stats[col] for col in target_cols],
        'Change Rate': [f"{change_stats[col]/len(merged)*100:.2f}%" for col in target_cols]
    })

    print(f"\nTotal Modified Rows: {len(merged)}")
    print(f"Total Cell Changes: {total_changes}")
    display(change_df)

In [ ]:
feats = ['sleep_time','sleep_time_lag1','sleep_time_diff','wake_time','wake_time_lag1','wake_time_diff','sleep_duration_llm','sleep_duration_diff','weekday','month','weekend']
a1 = train[['subject_id','sleep_date','sleep_time','sleep_time_lag1','sleep_time_diff','wake_time','wake_time_lag1','wake_time_diff','sleep_duration_llm','sleep_duration_diff','weekday','month','weekend']]
a1[feats] = a1[feats].apply(lambda x: np.round(x,1))
submission_valid_etrainfo = submission_valid.merge(a1,on=['subject_id','sleep_date'],how='left')
submission_valid_etrainfo['pk'] = submission_valid_etrainfo['subject_id']+submission_valid_etrainfo['sleep_date']
submission_valid_etrainfo.head()

,subject_id,sleep_date,lifelog_date,Q1,Q2,Q3,S1,S2,S3,sleep_time,sleep_time_lag1,sleep_time_diff,wake_time,wake_time_lag1,wake_time_diff,sleep_duration_llm,sleep_duration_diff,weekday,month,weekend,pk
0,id01,2024-07-24,2024-07-23,0,1,1,1,1,1,22.3000,23.2000,0.5000,5.2000,5.2000,0.8000,103.0000,17.9000,1,7,0,id012024-07-24
1,id01,2024-07-27,2024-07-26,1,0,1,1,1,1,23.0000,22.3000,-0.3000,7.3000,5.2000,-1.2000,495.0000,-58.1000,4,7,0,id012024-07-27
2,id01,2024-08-18,2024-08-17,1,1,1,1,0,1,22.2000,24.1000,0.2000,6.6000,7.0000,-0.4000,502.0000,-38.2000,5,8,1,id012024-08-18
3,id01,2024-08-19,2024-08-18,0,1,1,0,1,1,21.9000,22.2000,0.6000,5.1000,6.6000,1.1000,434.0000,29.8000,6,8,1,id012024-08-19
4,id01,2024-08-20,2024-08-19,0,0,0,0,1,1,22.4000,21.9000,0.4000,5.2000,5.1000,0.7000,405.0000,12.2000,0,8,0,id012024-08-20

In [ ]:
data_extrainfo = train.copy()
data_extrainfo['pk'] = data_extrainfo['subject_id']+data_extrainfo['sleep_date']
data_extrainfo = data_extrainfo.loc[~data_extrainfo['pk'].isin(submission_valid_etrainfo['pk'].tolist()),submission_valid_etrainfo.columns.tolist()].reset_index(drop=True)
feats = ['sleep_time','sleep_time_lag1','sleep_time_diff','wake_time','wake_time_lag1','wake_time_diff','sleep_duration_llm','sleep_duration_diff','weekday','month','weekend']
data_extrainfo[feats] = data_extrainfo[feats].apply(lambda x: np.round(x,1))
data_extrainfo.head()

,subject_id,sleep_date,lifelog_date,Q1,Q2,Q3,S1,S2,S3,sleep_time,sleep_time_lag1,sleep_time_diff,wake_time,wake_time_lag1,wake_time_diff,sleep_duration_llm,sleep_duration_diff,weekday,month,weekend,pk
0,id01,2024-06-27,2024-06-26,0,0,0,0,0,1,23.4000,-9.0000,-0.3000,5.2000,-9.0000,0.2000,348.0000,29.7000,2,6,0,id012024-06-27
1,id01,2024-06-28,2024-06-27,0,0,0,0,1,1,23.1000,23.4000,0.1000,5.3000,5.2000,0.2000,370.0000,7.7000,3,6,0,id012024-06-28
2,id01,2024-06-29,2024-06-28,1,0,0,1,1,1,23.0000,23.1000,0.2000,5.9000,5.3000,-0.4000,415.0000,-37.3000,4,6,0,id012024-06-29
3,id01,2024-06-30,2024-06-29,1,0,1,2,0,0,21.8000,23.0000,0.4000,5.9000,5.9000,-0.4000,487.0000,-49.0000,5,6,1,id012024-06-30
4,id01,2024-07-01,2024-06-30,0,1,1,1,1,1,22.7000,21.8000,-0.4000,5.2000,5.9000,0.4000,389.0000,49.0000,6,6,1,id012024-07-01

In [ ]:
submission_valid_etrainfo = submission_valid_etrainfo.drop(columns=['pk'])
data_extrainfo = data_extrainfo.drop(columns=['pk'])

In [ ]:
%%time

# CPU times: user 12.2 s, sys: 2.3 s, total: 14.5 s
# Wall time: 13min 25s

system_message = f"""
## 🔈지침: 당신은 베테랑 데이터 분석가 입니다.
- 다음은 사용자의 센서 데이터 기반 수면의 질을 예측하는 모델의 예측값 정보입니다.
- 상식과 과거 패턴을 참고해서 S1 예측값을 보정하시오.

## 🔈문제점(중요!!!!):
- 예측 타겟이 6개 존재(Q1,Q2,Q3,S1,S2,S3)하고, 각각 모델을 만들어서 예측 함
- 예측 타겟 간의 상관 관계가 존재하지만, 이런 부분을 머신러닝 모델 학습 시 충분히 반영되지 못함 -> 머신러닝 예측 모델 학습 시 문제점
- 각 타겟별 모델이 독립적으로 학습되어, Q와 S 간의 상관 관계 (예: Q1이 높으면 S1이 낮음)를 반영하지 못함
- Q1과 S1은 양의 상관관계 존재

## 🔈주의사항:
- 예측값은 6번 연속해서 1 또는 0 값이 나올 확률이 매우 적음 -> 6일 내내 수면의 질이 좋다는 의미인데 현실적으로 매우 드문 경우
- 예측값 6개 Q1, Q2, Q3, S1, S2, S3 모두 0인 경우는 확률적으로 매우 희박함
"""

pred = submission_valid_etrainfo.copy()
data = data_extrainfo.copy()
statistics_data = train.groupby(['subject_id','month'])[['Q1','Q2','Q3','S1','S2','S3']].mean().apply(lambda x: np.round(x,2)).reset_index().to_csv(index=False, sep=",")

results2 = []
parsed_results = []
for subject_id in tqdm(data['subject_id'].unique(), desc="Processing each subject"):
# for subject_id in tqdm(['id01'], desc="Processing each subject"):

    print(f'# subject_id:{subject_id}')

    pred_sub = pred[pred['subject_id'] == subject_id]
    data_sub = data[data['subject_id'] == subject_id]

    # 텍스트 테이블로 변환
    prediction_data = pred_sub.to_csv(index=False, sep=",")
    historical_patterns = data_sub.to_csv(index=False, sep=",")

    user_message = f"""
    # 🔈 예측 타겟 변수
    - Q1: 기상 직후 수면의 질 (0:평균이하, 1:평균이상)
    - Q2: 취침 직전 신체적 피로 수준 (0:높은피로, 1:낮은피로)
    - Q3: 취침 직전 스트레스 수준 (0:높은스트레스, 1:낮은스트레스)
    - S1: 총 수면시간 가이드라인 준수여부(0:미준수,1:부분적준수,2:완전준수)
    - S2: 수면 효율 가이드라인 준수여부 (0:미준수, 1:준수)
    - S3: 수면 잠들기 지연 시간 가이드라인 준수여부 (0:미준수, 1:준수)

    # 🔈독립 변수
    - sleep_time : 취침시간
    - sleep_time_lag1 : 전일 취침시간
    - sleep_time_diff : 평균대비 취침시간 차이 (평균취침시간 - 당일 취침시간)
    - wake_time : 기상시간
    - wake_time_lag1 : 전일 기상시간
    - wake_time_diff : 평균대비 기상시간 차이 (평균기상시간 - 당일 기상시간)
    - sleep_duration_llm : 수면시간
    - sleep_duration_diff : 평균대비 수면시간 차이 (평균수면시간 - 당일 수면시간)

    # 🔈 도메인 노하우
    - 금요일, 토요일에는 수면의 질이 좋을 수 있음 (다음날이 주말이라서, 단 주말에 출근하는 서비스업에 종사하는 사람은 예외)
    - 전일, 또는 전전일 상태가 현재 상태에 영향을 줄 수 있음 (전일 몸이 좋지 않으면 다음날도 몸이 좋지 않는 것과 동일한 원리)
    - 수면시간이 짧거나, 취침시간이 늦거나, 기상시간 빠르면 수면의 질이 좋지 않을 수 있음
    - 반대로 수면시간이 길거나, 취침시간이 빠르거나, 기상시간이 늦으면 수면의 질이 좋을 수 있음
    - 7월~8월 여름에는 날씨 영향으로 수면의 질이 좋지 않을 수 있음
    - 취침 전 전자기기 사용은 수면의 질을 하락 시키는 요인 임
    - S1 총 수면시간을 2 완전준수 했다면 Q1 기상 직후 수면의 질이 좋을 확률이 높음 (논리적으로)

    # 🔈 S1=2인 경우 추가 정보
    - id01  : [S1]이 2인 경우, [Q1, Q3]은 1 (4건/4건)
    - id02  : [S1]이 2인 경우, [S2]은 1 (19건/19건)
    - id03  : [S1]이 2인 경우, [Q1, Q2]은 1 (7건/8건)
    - id04  : [S1]이 2인 경우, [Q1, S2]은 1 (8건/9건)
    - id05  : [S1]이 2인 경우, [Q1, Q3, S2]은 1 [Q2]은 0 (7건/7건)
    - id06  : [S1]이 2인 경우, [Q1]은 0 (15건/15건), [S2,S3]은 1 (15건/15건)
    - id07  : [S1]이 2인 경우, 총 49일 샘플 중 S1이 2인 날이 1일 뿐임 (가장 적음)
    - id08  : [S1]이 2인 경우, [Q1]은 1 (9건/9건)
    - id09  : [S1]이 2인 경우, [S2]은 1 (7건/7건)
    - id010 : [S1]이 2인 경우, [Q1]은 1 (4건/4건)

    # 🔈 subject_id 특징
    - id05는 S2,S3 가이드를 거의 준수하지 않음 -> S2,S3 점수가 매우 낮음 (25%, 13.6%)
    - id06,id02는 S1,S2,S3 가이드를 매우 잘 준수함 -> S1,S2,S3 점수가 매우 높음 (125%, 91%, 95%)
    - id06은 Q1점수가 매우 낮음 (14.6%)
    - id03은 Q1점수가 가장 높음 (84.4%)

    # 🔈 예측모델 타겟별 모델 평가 (F1점수)
    # valid F1: 0.6733 / [상세] Q1(기상직후수면질):0.7496 Q2(취침전신체적피로):0.7485 Q3(취침전스트레스):0.6745 S2(수면효율):0.6786 S3(수면잠들기시간):0.6738 S1(수면시간):0.5148
    # oof F1: 0.6706 / [상세] Q1(기상직후수면질):0.7372 Q2(취침전신체적피로):0.6830 Q3(취침전스트레스):0.6630 S2(수면효율):0.6688 S3(수면잠들기시간):0.7175 S1(수면시간):0.5541

    # 🔈 subject_id별 타겟 평균 (타겟 인코딩, 과적합 주의해서 참고하시오!)
    {statistics_data}

    # 🔈 과거 패턴 (개수:{len(data_sub)})
    {historical_patterns}

    # 🔈 예측 데이터 (개수:{len(pred_sub)})
    {prediction_data}

    # 🔈 작업 지침
    - 예측 타겟 간의 상관 관계를 파악해서 S1 예측값(0,1,2)을 보정하세요.
    - 예측값 보정은 최소 5번 이상 수행하세요.

    # 🔈 답변 출력 형식
    subject_id	sleep_date	lifelog_date	Q1	Q2	Q3	S1	S2	S3
    0	id01	2024-07-31	2024-07-30	0	1	1	1	1	1
    1	id01	2024-08-01	2024-07-31	0	0	0	0	1	1
    2	id01	2024-08-02	2024-08-01	0	0	0	0	1	1
    3	id01	2024-08-03	2024-08-02	1	1	0	1	1	1
    4	id01	2024-08-04	2024-08-03	0	1	1	1	0	1

    # 답변:
    """

    # 질의
    messages = [
        {"role": "system", "content": system_message},
        {"role": "user", "content": user_message}
    ]

    sampling_params = SamplingParams(max_tokens = 38960, temperature = 0, seed=42) # 38960, 10000
    outputs = llm.chat(messages,sampling_params=sampling_params)

    # 텍스트 추출 및 <think> 제거
    result_text = outputs[0].outputs[0].text
    cleaned_text = re.sub(r"<think>.*?</think>", "", result_text, flags=re.DOTALL).strip()

    # 파싱 (탭 구분 텍스트 → DataFrame)
    try:
        from io import StringIO
        df_parsed = pd.read_csv(StringIO(cleaned_text), sep="\t")
        parsed_results.append(df_parsed)

    except Exception as e:
        print(f"[ERROR] Parsing failed for subject {subject_id}: {e}")
        print(result_text[:500])  # 일부 출력

# 모든 subject 결과 병합
submission_llm = pd.concat(parsed_results, ignore_index=True)
submission_llm.to_excel('/content/drive/MyDrive/data/ch2025_data_items/submission_llm.xlsx',index=False)
submission_llm.head()

Processing each subject:   0%|          | 0/10 [00:00<?, ?it/s]

# subject_id:id01
INFO 06-05 12:10:19 [chat_utils.py:419] Detected the chat template content format to be 'string'. You can set `--chat-template-content-format` to override this.

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

# subject_id:id02

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

In [ ]:
train['pk'] = train['subject_id']+train['sleep_date']

submission_llm['pk'] = submission_llm['subject_id']+submission_llm['sleep_date']
submission_valid['pk'] = submission_valid['subject_id']+submission_valid['sleep_date']

a1 = submission_llm.loc[submission_llm['pk'].isin(submission_valid['pk'].unique().tolist()),:]
a2 = submission_valid.loc[~submission_valid['pk'].isin(submission_llm['pk'].unique().tolist()),:]

submission_llm_adj = pd.concat([a1,a2])
submission_llm_adj = submission_llm_adj.sort_values(['subject_id','sleep_date']).reset_index(drop=True)

# LLM 결과 평가
llm_eval = {}
for col in ['Q1','Q2','Q3','S1','S2','S3']:
  real_y = train.loc[train['pk'].isin(valid_ids['pk']),col].values
  pred_y = submission_llm_adj[col]
  llm_eval[col] = f1_score(real_y, pred_y, average='macro')

"""
Q: 복원이 되는지 테스트 하기!

Q1	Q2	Q3	S1	S2	S3
0	0.7083	0.7485	0.6745	0.5148	0.6786	0.6738

Total Modified Rows: 80
Total Cell Changes: 10
Target	Changes	Change Rate
0	Q1	10	12.50%
1	Q2	0	0.00%
2	Q3	0	0.00%
3	S1	0	0.00%
4	S2	0	0.00%
5	S3	0	0.00%

"""

# check
# 평균 F1: 0.6733 / [상세] Q1():0.7496 Q2():0.7485 Q3():0.6745 S1():0.5148 S2():0.6786 S3():0.6738
display(pd.DataFrame.from_dict(llm_eval,orient='index').T)
calculate_llm_changes(submission_valid,submission_llm)

### ===================

### 제출

In [ ]:
a1 = test[['subject_id','sleep_date','sleep_time','sleep_time_lag1','sleep_time_diff','wake_time','wake_time_lag1','wake_time_diff','sleep_duration_llm','sleep_duration_diff']]
submission_final_etrainfo = submission_final.merge(a1,on=['subject_id','sleep_date'],how='left')
submission_final_etrainfo.head()

In [ ]:
%%time

# CPU times: user 12.2 s, sys: 2.3 s, total: 14.5 s
# Wall time: 16min 25s

system_message = f"""
### 🔈지침: 당신은 베테랑 데이터 분석가 입니다.
- 다음은 사용자의 센서 데이터 기반 수면의 질을 예측하는 모델의 예측값 정보입니다.
- 상식과 이전/이후 맥락을 고려해 예측값을 보정하시오.

### 🔈답변 작성 양식
- 답변에 지침내용을 포함하지 않습니다.
"""

data = submission_final_etrainfo.copy()
results2 = []
parsed_results = []
for subject_id in tqdm(data['subject_id'].unique(), desc="Processing each subject"):
# for subject_id in tqdm(['id01'], desc="Processing each subject"):

    print(f'# subject_id:{subject_id}')

    df_sub = data[data['subject_id'] == subject_id]

    # 텍스트 테이블로 변환
    table_text = df_sub.to_csv(index=False, sep="\t")

    user_message = f"""
    # 🔈 수면 관련 변수 정보
    - Q1: 기상 직후 수면의 질 (0:평균이하, 1:평균이상)
    - Q2: 취침 직전 신체적 피로 수준 (0:높은피로, 1:낮은피로)
    - Q3: 취침 직전 스트레스 수준 (0:높은스트레스, 1:낮은스트레스)
    - S1: 총 수면시간 가이드라인 준수여부(0:미준수,1:부분적준수,2:완전준수)
    - S2: 수면 효율 가이드라인 준수여부 (0:미준수, 1:준수)
    - S3: 수면 잠들기 지연 시간 가이드라인 준수여부 (0:미준수, 1:준수)
    - sleep_time_lag1 : 전일 취침시간
    - sleep_time_diff : 평균대비 취침시간 차이 (평균취침시간 - 당일 취침시간)
    - wake_time : 기상시간
    - wake_time_lag1 : 전일 기상시간
    - wake_time_diff : 평균대비 기상시간 차이 (평균기상시간 - 당일 기상시간)
    - sleep_duration_llm : 수면시간
    - sleep_duration_diff : 평균대비 수면시간 차이 (평균수면시간 - 당일 수면시간)

    # 🔈 정보[1]
    - 금요일, 토요일에는 수면의 질이 좋을 수 있음 (다음날이 주말이라서, 단 주말에 출근하는 서비스업에 종사하는 사람은 예외)
    - 전일, 또는 전전일 상태가 현재 상태에 영향을 줄 수 있음 (전일 몸이 좋지 않으면 다음날도 몸이 좋지 않는 것과 동일한 원리)

    # 🔈 정보[2] Q1,Q2,Q3,S1,S2,S3는 서로 다음의 관계가 존재
    - id01  : [S1]이 2인 경우, [Q1, Q3]은 1 (4건/4건)
    - id02  : [S1]이 2인 경우, [S2]은 1 (19건/19건)
    - id03  : [S1]이 2인 경우, [Q1, Q2]은 1 (7건/8건)
    - id04  : [S1]이 2인 경우, [Q1, S2]은 1 (8건/9건)
    - id05  : [S1]이 2인 경우, [Q1, Q3, S2]은 1 [Q2]은 0 (7건/7건)
    - id06  : [S1]이 2인 경우, [Q1]은 0 (15건/15건), [S2,S3]은 1 (15건/15건)
    - id07  : [S1]이 2인 경우, 총 49일 샘플 중 S1이 2인 날이 1일 뿐임 (가장 적음)
    - id08  : [S1]이 2인 경우, [Q1]은 1 (9건/9건)
    - id09  : [S1]이 2인 경우, [S2]은 1 (7건/7건)
    - id010 : [S1]이 2인 경우, [Q1]은 1 (4건/4건)

    # 🔈 예측모델 타겟별 F1점수
    - 전체평균 F1: 0.6709 / [상세] Q1(기상직후수면질):0.7496 Q2(취침전신체적피로):0.7485 Q3(취침전스트레스):0.6745 S2(수면효율):0.6786 S3(수면잠들기시간):0.6738 S1(수면시간):0.5001

    # 🔈 데이터
    {table_text}

    # 🔈 답변 출력 형식
    subject_id	sleep_date	lifelog_date	Q1	Q2	Q3	S1	S2	S3
    0	id01	2024-07-31	2024-07-30	0	1	1	1	1	1
    1	id01	2024-08-01	2024-07-31	0	0	0	0	1	1
    2	id01	2024-08-02	2024-08-01	0	0	0	0	1	1
    3	id01	2024-08-03	2024-08-02	1	1	0	1	1	1
    4	id01	2024-08-04	2024-08-03	0	1	1	1	0	1

    # 답변:
    """

    # 질의
    messages = [
        {"role": "system", "content": system_message},
        {"role": "user", "content": user_message}
    ]

    sampling_params = SamplingParams(max_tokens = 10000,temperature = 0.5)
    outputs = llm.chat(messages,sampling_params=sampling_params)

    # 텍스트 추출 및 <think> 제거
    result_text = outputs[0].outputs[0].text
    cleaned_text = re.sub(r"<think>.*?</think>", "", result_text, flags=re.DOTALL).strip()

    # 파싱 (탭 구분 텍스트 → DataFrame)
    try:
        from io import StringIO
        df_parsed = pd.read_csv(StringIO(cleaned_text), sep="\t")
        parsed_results.append(df_parsed)

    except Exception as e:
        print(f"[ERROR] Parsing failed for subject {subject_id}: {e}")
        print(result_text[:500])  # 일부 출력

# 모든 subject 결과 병합
submission_final_llm = pd.concat(parsed_results, ignore_index=True)
submission_final_llm.to_excel('/content/drive/MyDrive/data/ch2025_data_items/submission_final_llm.xlsx',index=False)
submission_final_llm.head()